package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * ActividadEstado generated by hbm2java
 */
public class ActividadEstado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<Actividad> actividads = new ArrayList<Actividad>(0);
	private List<ActividadHistorial> actividadHistorials = new ArrayList<ActividadHistorial>(0);

	public ActividadEstado() {
	}

	public ActividadEstado(Integer id) {
		this.id = id;
	}

	public ActividadEstado(Integer id, String nombre, List<Actividad> actividads,
			List<ActividadHistorial> actividadHistorials) {
		this.id = id;
		this.nombre = nombre;
		this.actividads = actividads;
		this.actividadHistorials = actividadHistorials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

	public List<ActividadHistorial> getActividadHistorials() {
		return this.actividadHistorials;
	}

	public void setActividadHistorials(List<ActividadHistorial> actividadHistorials) {
		this.actividadHistorials = actividadHistorials;
	}

}
