package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * ActividadXDocumentoTipo generated by hbm2java
 */
public class ActividadXDocumentoTipo implements java.io.Serializable {

	private int id;
	private DocumentoTipo documentoTipo;
	private Actividad actividad;
	private Integer totalEntregados;
	private Integer totalRecibidos;

	public ActividadXDocumentoTipo() {
	}

	public ActividadXDocumentoTipo(int id) {
		this.id = id;
	}

	public ActividadXDocumentoTipo(int id, DocumentoTipo documentoTipo,
			Actividad actividad, Integer totalEntregados, Integer totalRecibidos) {
		this.id = id;
		this.documentoTipo = documentoTipo;
		this.actividad = actividad;
		this.totalEntregados = totalEntregados;
		this.totalRecibidos = totalRecibidos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public DocumentoTipo getDocumentoTipo() {
		return this.documentoTipo;
	}

	public void setDocumentoTipo(DocumentoTipo documentoTipo) {
		this.documentoTipo = documentoTipo;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Integer getTotalEntregados() {
		return this.totalEntregados;
	}

	public void setTotalEntregados(Integer totalEntregados) {
		this.totalEntregados = totalEntregados;
	}

	public Integer getTotalRecibidos() {
		return this.totalRecibidos;
	}

	public void setTotalRecibidos(Integer totalRecibidos) {
		this.totalRecibidos = totalRecibidos;
	}

}
