package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ActividadEstado generated by hbm2java
 */
public class ActividadEstado implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set actividads = new HashSet(0);
	private Set actividadHistorials = new HashSet(0);

	public ActividadEstado() {
	}

	public ActividadEstado(int id) {
		this.id = id;
	}

	public ActividadEstado(int id, String nombre, Set actividads,
			Set actividadHistorials) {
		this.id = id;
		this.nombre = nombre;
		this.actividads = actividads;
		this.actividadHistorials = actividadHistorials;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividads() {
		return this.actividads;
	}

	public void setActividads(Set actividads) {
		this.actividads = actividads;
	}

	public Set getActividadHistorials() {
		return this.actividadHistorials;
	}

	public void setActividadHistorials(Set actividadHistorials) {
		this.actividadHistorials = actividadHistorials;
	}

}
