package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.ActividadTipoDTO;

/**
 * ActividadTipo generated by hbm2java
 */
public class ActividadTipo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set aplicacionXNivelXActividadTipos = new HashSet(0);

	public ActividadTipo() {
	}

	public ActividadTipo(int id) {
		this.id = id;
	}

	public ActividadTipo(int id, String nombre,
			Set aplicacionXNivelXActividadTipos) {
		this.id = id;
		this.nombre = nombre;
		this.aplicacionXNivelXActividadTipos = aplicacionXNivelXActividadTipos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAplicacionXNivelXActividadTipos() {
		return this.aplicacionXNivelXActividadTipos;
	}

	public void setAplicacionXNivelXActividadTipos(
			Set aplicacionXNivelXActividadTipos) {
		this.aplicacionXNivelXActividadTipos = aplicacionXNivelXActividadTipos;
	}

	public ActividadTipoDTO getActividadTipoDTO() {
		ActividadTipoDTO atdto = new ActividadTipoDTO();
		atdto.setId(id);
		atdto.setNombre(nombre);
		return atdto;
	}

}
