package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.ContactoDTO;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private int id;
	private ActividadEstado actividadEstado;
	private Curso curso;
	private ContactoCargo contactoCargo;
	private AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo;
	private Usuario usuario;
	private String comentario;
	private Date fechaInicio;
	private Date fechaTermino;
	private Date fechaInicioPrueba;
	private Date fechaTerminoPrueba;
	private String contactoNombre;
	private String contactoTelefono;
	private String contactoEmail;
	private boolean sinMaterial;
	private Set alumnoXActividads = new HashSet(0);
	private Set usuarioXActividads = new HashSet(0);
	private Set materialHistorials = new HashSet(0);
	private Set materials = new HashSet(0);
	private Set actividadXDocumentoTipos = new HashSet(0);
	private Set actividadHistorials = new HashSet(0);
	private Set transporteXActividads = new HashSet(0);
	private Set documentos = new HashSet(0);
	private Set actividadXIncidencias = new HashSet(0);

	public Actividad() {
	}

	public Actividad(int id, boolean sinMaterial) {
		this.id = id;
		this.sinMaterial = sinMaterial;
	}

	public Actividad(int id, ActividadEstado actividadEstado, Curso curso,
			ContactoCargo contactoCargo,
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo,
			Usuario usuario, String comentario, Date fechaInicio,
			Date fechaTermino, Date fechaInicioPrueba, Date fechaTerminoPrueba,
			String contactoNombre, String contactoTelefono,
			String contactoEmail, boolean sinMaterial, Set alumnoXActividads,
			Set usuarioXActividads, Set materialHistorials, Set materials,
			Set actividadXDocumentoTipos, Set actividadHistorials,
			Set transporteXActividads, Set documentos, Set actividadXIncidencias) {
		this.id = id;
		this.actividadEstado = actividadEstado;
		this.curso = curso;
		this.contactoCargo = contactoCargo;
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
		this.usuario = usuario;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
		this.fechaInicioPrueba = fechaInicioPrueba;
		this.fechaTerminoPrueba = fechaTerminoPrueba;
		this.contactoNombre = contactoNombre;
		this.contactoTelefono = contactoTelefono;
		this.contactoEmail = contactoEmail;
		this.sinMaterial = sinMaterial;
		this.alumnoXActividads = alumnoXActividads;
		this.usuarioXActividads = usuarioXActividads;
		this.materialHistorials = materialHistorials;
		this.materials = materials;
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
		this.actividadHistorials = actividadHistorials;
		this.transporteXActividads = transporteXActividads;
		this.documentos = documentos;
		this.actividadXIncidencias = actividadXIncidencias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public ActividadEstado getActividadEstado() {
		return this.actividadEstado;
	}

	public void setActividadEstado(ActividadEstado actividadEstado) {
		this.actividadEstado = actividadEstado;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public ContactoCargo getContactoCargo() {
		return this.contactoCargo;
	}

	public void setContactoCargo(ContactoCargo contactoCargo) {
		this.contactoCargo = contactoCargo;
	}

	public AplicacionXNivelXActividadTipo getAplicacionXNivelXActividadTipo() {
		return this.aplicacionXNivelXActividadTipo;
	}

	public void setAplicacionXNivelXActividadTipo(
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo) {
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Date getFechaInicioPrueba() {
		return this.fechaInicioPrueba;
	}

	public void setFechaInicioPrueba(Date fechaInicioPrueba) {
		this.fechaInicioPrueba = fechaInicioPrueba;
	}

	public Date getFechaTerminoPrueba() {
		return this.fechaTerminoPrueba;
	}

	public void setFechaTerminoPrueba(Date fechaTerminoPrueba) {
		this.fechaTerminoPrueba = fechaTerminoPrueba;
	}

	public String getContactoNombre() {
		return this.contactoNombre;
	}

	public void setContactoNombre(String contactoNombre) {
		this.contactoNombre = contactoNombre;
	}

	public String getContactoTelefono() {
		return this.contactoTelefono;
	}

	public void setContactoTelefono(String contactoTelefono) {
		this.contactoTelefono = contactoTelefono;
	}

	public String getContactoEmail() {
		return this.contactoEmail;
	}

	public void setContactoEmail(String contactoEmail) {
		this.contactoEmail = contactoEmail;
	}

	public boolean isSinMaterial() {
		return this.sinMaterial;
	}

	public void setSinMaterial(boolean sinMaterial) {
		this.sinMaterial = sinMaterial;
	}

	public Set getAlumnoXActividads() {
		return this.alumnoXActividads;
	}

	public void setAlumnoXActividads(Set alumnoXActividads) {
		this.alumnoXActividads = alumnoXActividads;
	}

	public Set getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(Set usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public Set getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(Set materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public Set getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set materials) {
		this.materials = materials;
	}

	public Set getActividadXDocumentoTipos() {
		return this.actividadXDocumentoTipos;
	}

	public void setActividadXDocumentoTipos(Set actividadXDocumentoTipos) {
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
	}

	public Set getActividadHistorials() {
		return this.actividadHistorials;
	}

	public void setActividadHistorials(Set actividadHistorials) {
		this.actividadHistorials = actividadHistorials;
	}

	public Set getTransporteXActividads() {
		return this.transporteXActividads;
	}

	public void setTransporteXActividads(Set transporteXActividads) {
		this.transporteXActividads = transporteXActividads;
	}

	public Set getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set documentos) {
		this.documentos = documentos;
	}

	public Set getActividadXIncidencias() {
		return this.actividadXIncidencias;
	}

	public void setActividadXIncidencias(Set actividadXIncidencias) {
		this.actividadXIncidencias = actividadXIncidencias;
	}

	public ContactoDTO getContactoDTO() {
		ContactoDTO cdto = new ContactoDTO();
		cdto.setContactoEmail(contactoEmail);
		cdto.setContactoNombre(contactoNombre);
		cdto.setContactoTelefono(contactoTelefono);
		return cdto;
	}

}
