package com.dreamer8.yosimce.server.hibernate.pojo;

import com.dreamer8.yosimce.shared.dto.ContingenciaDTO;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * ActividadXIncidencia generated by hbm2java
 */
public class ActividadXIncidencia implements java.io.Serializable {

	private Integer id;
	private MotivoFalla motivoFalla;
	private Actividad actividad;
	private String motivoDescripcion;
	private Boolean inhabilitaAplicacion;

	public ActividadXIncidencia() {
	}

	public ActividadXIncidencia(Integer id) {
		this.id = id;
	}

	public ActividadXIncidencia(Integer id, MotivoFalla motivoFalla,
			Actividad actividad, String motivoDescripcion,
			Boolean inhabilitaAplicacion) {
		this.id = id;
		this.motivoFalla = motivoFalla;
		this.actividad = actividad;
		this.motivoDescripcion = motivoDescripcion;
		this.inhabilitaAplicacion = inhabilitaAplicacion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MotivoFalla getMotivoFalla() {
		return this.motivoFalla;
	}

	public void setMotivoFalla(MotivoFalla motivoFalla) {
		this.motivoFalla = motivoFalla;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public String getMotivoDescripcion() {
		return this.motivoDescripcion;
	}

	public void setMotivoDescripcion(String motivoDescripcion) {
		this.motivoDescripcion = motivoDescripcion;
	}

	public Boolean getInhabilitaAplicacion() {
		return this.inhabilitaAplicacion;
	}

	public void setInhabilitaAplicacion(Boolean inhabilitaAplicacion) {
		this.inhabilitaAplicacion = inhabilitaAplicacion;
	}

	/**
	 * @return
	 */
	public ContingenciaDTO getContingenciaDTO() {
		ContingenciaDTO cdto = new ContingenciaDTO();
		cdto.setInabilitante(inhabilitaAplicacion);
		cdto.setDetalleContingencia(motivoDescripcion);
		cdto.setTipoContingencia(motivoFalla.getTipoContingenciaDTO());
		return cdto;
	}

}
