package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActividadHistorialId generated by hbm2java
 */
public class ActividadHistorialId implements java.io.Serializable {

	private Integer actividadId;
	private Date fecha;

	public ActividadHistorialId() {
	}

	public ActividadHistorialId(Integer actividadId, Date fecha) {
		this.actividadId = actividadId;
		this.fecha = fecha;
	}

	public Integer getActividadId() {
		return this.actividadId;
	}

	public void setActividadId(Integer actividadId) {
		this.actividadId = actividadId;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActividadHistorialId))
			return false;
		ActividadHistorialId castOther = (ActividadHistorialId) other;

		return (this.getActividadId() == castOther.getActividadId())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getActividadId();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
