package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActividadHistorialId generated by hbm2java
 */
public class ActividadHistorialId implements java.io.Serializable {

	private Integer id;
	private Date fecha;

	public ActividadHistorialId() {
	}

	public ActividadHistorialId(Integer id, Date fecha) {
		this.id = id;
		this.fecha = fecha;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActividadHistorialId))
			return false;
		ActividadHistorialId castOther = (ActividadHistorialId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
