package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * ActividadXDocumentoTipoId generated by hbm2java
 */
public class ActividadXDocumentoTipoId implements java.io.Serializable {

	private Integer actividadId;
	private Integer documentoTipoId;

	public ActividadXDocumentoTipoId() {
	}

	public ActividadXDocumentoTipoId(Integer actividadId, Integer documentoTipoId) {
		this.actividadId = actividadId;
		this.documentoTipoId = documentoTipoId;
	}

	public Integer getActividadId() {
		return this.actividadId;
	}

	public void setActividadId(Integer actividadId) {
		this.actividadId = actividadId;
	}

	public Integer getDocumentoTipoId() {
		return this.documentoTipoId;
	}

	public void setDocumentoTipoId(Integer documentoTipoId) {
		this.documentoTipoId = documentoTipoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActividadXDocumentoTipoId))
			return false;
		ActividadXDocumentoTipoId castOther = (ActividadXDocumentoTipoId) other;

		return (this.getActividadId() == castOther.getActividadId())
				&& (this.getDocumentoTipoId() == castOther.getDocumentoTipoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getActividadId();
		result = 37 * result + this.getDocumentoTipoId();
		return result;
	}

}
