package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

/**
 * Actividad generated by hbm2java
 */
public class Actividad implements java.io.Serializable {

	private Integer id;
	private ActividadEstado actividadEstado;
	private Curso curso;
	private ContactoCargo contactoCargo;
	private AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo;
	private Usuario usuario;
	private String comentario;
	private Date fechaInicio;
	private Date fechaTermino;
	private String contactoNombre;
	private String contactoTelefono;
	private String contactoEmail;
	private List<AlumnoXActividad> alumnoXActividads = new ArrayList<AlumnoXActividad>(0);
	private List<UsuarioXActividad> usuarioXActividads = new ArrayList<UsuarioXActividad>(0);
	private List<MaterialHistorial> materialHistorials = new ArrayList<MaterialHistorial>(0);
	private List<Material> materials = new ArrayList<Material>(0);
	private List<ActividadXDocumentoTipo> actividadXDocumentoTipos = new ArrayList<ActividadXDocumentoTipo>(0);
	private List<ActividadHistorial> actividadHistorials = new ArrayList<ActividadHistorial>(0);
	private List<TransporteXActividad> transporteXActividads = new ArrayList<TransporteXActividad>(0);
	private List<Documento> documentos = new ArrayList<Documento>(0);
	private List<ActividadXIncidencia> actividadXIncidencias = new ArrayList<ActividadXIncidencia>(0);

	public Actividad() {
	}

	public Actividad(Integer id,
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo) {
		this.id = id;
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
	}

	public Actividad(Integer id, ActividadEstado actividadEstado, Curso curso,
			ContactoCargo contactoCargo,
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo,
			Usuario usuario, String comentario, Date fechaInicio,
			Date fechaTermino, String contactoNombre, String contactoTelefono,
			String contactoEmail, List<AlumnoXActividad> alumnoXActividads,
			List<UsuarioXActividad> usuarioXActividads, List<MaterialHistorial> materialHistorials, List<Material> materials,
			List<ActividadXDocumentoTipo> actividadXDocumentoTipos, List<ActividadHistorial> actividadHistorials,
			List<TransporteXActividad> transporteXActividads, List<Documento> documentos, List<ActividadXIncidencia> actividadXIncidencias) {
		this.id = id;
		this.actividadEstado = actividadEstado;
		this.curso = curso;
		this.contactoCargo = contactoCargo;
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
		this.usuario = usuario;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
		this.contactoNombre = contactoNombre;
		this.contactoTelefono = contactoTelefono;
		this.contactoEmail = contactoEmail;
		this.alumnoXActividads = alumnoXActividads;
		this.usuarioXActividads = usuarioXActividads;
		this.materialHistorials = materialHistorials;
		this.materials = materials;
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
		this.actividadHistorials = actividadHistorials;
		this.transporteXActividads = transporteXActividads;
		this.documentos = documentos;
		this.actividadXIncidencias = actividadXIncidencias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ActividadEstado getActividadEstado() {
		return this.actividadEstado;
	}

	public void setActividadEstado(ActividadEstado actividadEstado) {
		this.actividadEstado = actividadEstado;
	}

	public Curso getCurso() {
		return this.curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public ContactoCargo getContactoCargo() {
		return this.contactoCargo;
	}

	public void setContactoCargo(ContactoCargo contactoCargo) {
		this.contactoCargo = contactoCargo;
	}

	public AplicacionXNivelXActividadTipo getAplicacionXNivelXActividadTipo() {
		return this.aplicacionXNivelXActividadTipo;
	}

	public void setAplicacionXNivelXActividadTipo(
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo) {
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public String getContactoNombre() {
		return this.contactoNombre;
	}

	public void setContactoNombre(String contactoNombre) {
		this.contactoNombre = contactoNombre;
	}

	public String getContactoTelefono() {
		return this.contactoTelefono;
	}

	public void setContactoTelefono(String contactoTelefono) {
		this.contactoTelefono = contactoTelefono;
	}

	public String getContactoEmail() {
		return this.contactoEmail;
	}

	public void setContactoEmail(String contactoEmail) {
		this.contactoEmail = contactoEmail;
	}

	public List<AlumnoXActividad> getAlumnoXActividads() {
		return this.alumnoXActividads;
	}

	public void setAlumnoXActividads(List<AlumnoXActividad> alumnoXActividads) {
		this.alumnoXActividads = alumnoXActividads;
	}

	public List<UsuarioXActividad> getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(List<UsuarioXActividad> usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public List<MaterialHistorial> getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(List<MaterialHistorial> materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public List<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(List<Material> materials) {
		this.materials = materials;
	}

	public List<ActividadXDocumentoTipo> getActividadXDocumentoTipos() {
		return this.actividadXDocumentoTipos;
	}

	public void setActividadXDocumentoTipos(List<ActividadXDocumentoTipo> actividadXDocumentoTipos) {
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
	}

	public List<ActividadHistorial> getActividadHistorials() {
		return this.actividadHistorials;
	}

	public void setActividadHistorials(List<ActividadHistorial> actividadHistorials) {
		this.actividadHistorials = actividadHistorials;
	}

	public List<TransporteXActividad> getTransporteXActividads() {
		return this.transporteXActividads;
	}

	public void setTransporteXActividads(List<TransporteXActividad> transporteXActividads) {
		this.transporteXActividads = transporteXActividads;
	}

	public List<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(List<Documento> documentos) {
		this.documentos = documentos;
	}

	public List<ActividadXIncidencia> getActividadXIncidencias() {
		return this.actividadXIncidencias;
	}

	public void setActividadXIncidencias(List<ActividadXIncidencia> actividadXIncidencias) {
		this.actividadXIncidencias = actividadXIncidencias;
	}

}
