package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActividadHistorial generated by hbm2java
 */
public class ActividadHistorial implements java.io.Serializable {

	private ActividadHistorialId id;
	private ActividadEstado actividadEstado;
	private Actividad actividad;
	private Integer modificadorId;
	private String comentario;
	private Date fechaInicio;
	private Date fechaTermino;

	public ActividadHistorial() {
	}

	public ActividadHistorial(ActividadHistorialId id, Actividad actividad) {
		this.id = id;
		this.actividad = actividad;
	}

	public ActividadHistorial(ActividadHistorialId id,
			ActividadEstado actividadEstado, Actividad actividad,
			Integer modificadorId, String comentario, Date fechaInicio,
			Date fechaTermino) {
		this.id = id;
		this.actividadEstado = actividadEstado;
		this.actividad = actividad;
		this.modificadorId = modificadorId;
		this.comentario = comentario;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
	}

	public ActividadHistorialId getId() {
		return this.id;
	}

	public void setId(ActividadHistorialId id) {
		this.id = id;
	}

	public ActividadEstado getActividadEstado() {
		return this.actividadEstado;
	}

	public void setActividadEstado(ActividadEstado actividadEstado) {
		this.actividadEstado = actividadEstado;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Integer getModificadorId() {
		return this.modificadorId;
	}

	public void setModificadorId(Integer modificadorId) {
		this.modificadorId = modificadorId;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

}
