package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ActividadHistorialId generated by hbm2java
 */
public class ActividadHistorialId implements java.io.Serializable {

	private Integer actividadId;
	private Date fecha;

	public ActividadHistorialId() {
	}

	public ActividadHistorialId(Integer actividadId, Date fecha) {
		this.actividadId = actividadId;
		this.fecha = fecha;
	}

	public Integer getActividadId() {
		return this.actividadId;
	}

	public void setActividadId(Integer actividadId) {
		this.actividadId = actividadId;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((actividadId == null) ? 0 : actividadId.hashCode());
		result = prime * result + ((fecha == null) ? 0 : fecha.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ActividadHistorialId other = (ActividadHistorialId) obj;
		if (actividadId == null) {
			if (other.actividadId != null)
				return false;
		} else if (!actividadId.equals(other.actividadId))
			return false;
		if (fecha == null) {
			if (other.fecha != null)
				return false;
		} else if (!fecha.equals(other.fecha))
			return false;
		return true;
	}

}
