package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * AlumnoTipo generated by hbm2java
 */
public class AlumnoTipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<AlumnoXActividad> alumnoXActividads = new ArrayList<AlumnoXActividad>(0);

	public AlumnoTipo() {
	}

	public AlumnoTipo(Integer id) {
		this.id = id;
	}

	public AlumnoTipo(Integer id, String nombre, List<AlumnoXActividad> alumnoXActividads) {
		this.id = id;
		this.nombre = nombre;
		this.alumnoXActividads = alumnoXActividads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<AlumnoXActividad> getAlumnoXActividads() {
		return this.alumnoXActividads;
	}

	public void setAlumnoXActividads(List<AlumnoXActividad> alumnoXActividads) {
		this.alumnoXActividads = alumnoXActividads;
	}

}
