package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * AlumnoXActividadXDocumentoId generated by hbm2java
 */
public class AlumnoXActividadXDocumentoId implements java.io.Serializable {

	private Integer alumnoXActividadId;
	private Integer documentoId;

	public AlumnoXActividadXDocumentoId() {
	}

	public AlumnoXActividadXDocumentoId(Integer alumnoXActividadId, Integer documentoId) {
		this.alumnoXActividadId = alumnoXActividadId;
		this.documentoId = documentoId;
	}

	public Integer getAlumnoXActividadId() {
		return this.alumnoXActividadId;
	}

	public void setAlumnoXActividadId(Integer alumnoXActividadId) {
		this.alumnoXActividadId = alumnoXActividadId;
	}

	public Integer getDocumentoId() {
		return this.documentoId;
	}

	public void setDocumentoId(Integer documentoId) {
		this.documentoId = documentoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlumnoXActividadXDocumentoId))
			return false;
		AlumnoXActividadXDocumentoId castOther = (AlumnoXActividadXDocumentoId) other;

		return (this.getAlumnoXActividadId() == castOther
				.getAlumnoXActividadId())
				&& (this.getDocumentoId() == castOther.getDocumentoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getAlumnoXActividadId();
		result = 37 * result + this.getDocumentoId();
		return result;
	}

}
