package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AlumnoEstado generated by hbm2java
 */
public class AlumnoEstado implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set alumnoXActividads = new HashSet(0);

	public AlumnoEstado() {
	}

	public AlumnoEstado(int id) {
		this.id = id;
	}

	public AlumnoEstado(int id, String nombre, Set alumnoXActividads) {
		this.id = id;
		this.nombre = nombre;
		this.alumnoXActividads = alumnoXActividads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAlumnoXActividads() {
		return this.alumnoXActividads;
	}

	public void setAlumnoXActividads(Set alumnoXActividads) {
		this.alumnoXActividads = alumnoXActividads;
	}

}
