package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AplicacionXEstablecimiento generated by hbm2java
 */
public class AplicacionXEstablecimiento implements java.io.Serializable {

	private Integer id;
	private Aplicacion aplicacion;
	private EstablecimientoTipo establecimientoTipo;
	private Establecimiento establecimiento;
	private String comentario;
	private Date updatedAt;
	private Integer modificadorId;

	public AplicacionXEstablecimiento() {
	}

	public AplicacionXEstablecimiento(Integer id) {
		this.id = id;
	}

	public AplicacionXEstablecimiento(Integer id, Aplicacion aplicacion,
			EstablecimientoTipo establecimientoTipo,
			Establecimiento establecimiento, String comentario, Date updatedAt,
			Integer modificadorId) {
		this.id = id;
		this.aplicacion = aplicacion;
		this.establecimientoTipo = establecimientoTipo;
		this.establecimiento = establecimiento;
		this.comentario = comentario;
		this.updatedAt = updatedAt;
		this.modificadorId = modificadorId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public EstablecimientoTipo getEstablecimientoTipo() {
		return this.establecimientoTipo;
	}

	public void setEstablecimientoTipo(EstablecimientoTipo establecimientoTipo) {
		this.establecimientoTipo = establecimientoTipo;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Integer getModificadorId() {
		return this.modificadorId;
	}

	public void setModificadorId(Integer modificadorId) {
		this.modificadorId = modificadorId;
	}

}
