package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.AplicacionDTO;

/**
 * Aplicacion generated by hbm2java
 */
public class Aplicacion implements java.io.Serializable {

	private int id;
	private String nombre;
	private String slug;
	private Integer tiempoDetencionEstablecimiento;
	private Integer diasPreviosSinMaterial;
	private Set centroRegionals = new HashSet(0);
	private Set aplicacionXNivels = new HashSet(0);
	private Set lugars = new HashSet(0);
	private Set aplicacionXEstablecimientos = new HashSet(0);
	private Set faseXAplicacions = new HashSet(0);
	private Set documentoTipos = new HashSet(0);
	private Set ccCapacitacions = new HashSet(0);
	private Set aplicacionXUsuarioTipos = new HashSet(0);
	private Set documentoEstados = new HashSet(0);

	public Aplicacion() {
	}

	public Aplicacion(int id, String slug) {
		this.id = id;
		this.slug = slug;
	}

	public Aplicacion(int id, String nombre, String slug,
			Integer tiempoDetencionEstablecimiento,
			Integer diasPreviosSinMaterial, Set centroRegionals,
			Set aplicacionXNivels, Set lugars, Set aplicacionXEstablecimientos,
			Set faseXAplicacions, Set documentoTipos, Set ccCapacitacions,
			Set aplicacionXUsuarioTipos, Set documentoEstados) {
		this.id = id;
		this.nombre = nombre;
		this.slug = slug;
		this.tiempoDetencionEstablecimiento = tiempoDetencionEstablecimiento;
		this.diasPreviosSinMaterial = diasPreviosSinMaterial;
		this.centroRegionals = centroRegionals;
		this.aplicacionXNivels = aplicacionXNivels;
		this.lugars = lugars;
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
		this.faseXAplicacions = faseXAplicacions;
		this.documentoTipos = documentoTipos;
		this.ccCapacitacions = ccCapacitacions;
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
		this.documentoEstados = documentoEstados;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getSlug() {
		return this.slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public Integer getTiempoDetencionEstablecimiento() {
		return this.tiempoDetencionEstablecimiento;
	}

	public void setTiempoDetencionEstablecimiento(
			Integer tiempoDetencionEstablecimiento) {
		this.tiempoDetencionEstablecimiento = tiempoDetencionEstablecimiento;
	}

	public Integer getDiasPreviosSinMaterial() {
		return this.diasPreviosSinMaterial;
	}

	public void setDiasPreviosSinMaterial(Integer diasPreviosSinMaterial) {
		this.diasPreviosSinMaterial = diasPreviosSinMaterial;
	}

	public Set getCentroRegionals() {
		return this.centroRegionals;
	}

	public void setCentroRegionals(Set centroRegionals) {
		this.centroRegionals = centroRegionals;
	}

	public Set getAplicacionXNivels() {
		return this.aplicacionXNivels;
	}

	public void setAplicacionXNivels(Set aplicacionXNivels) {
		this.aplicacionXNivels = aplicacionXNivels;
	}

	public Set getLugars() {
		return this.lugars;
	}

	public void setLugars(Set lugars) {
		this.lugars = lugars;
	}

	public Set getAplicacionXEstablecimientos() {
		return this.aplicacionXEstablecimientos;
	}

	public void setAplicacionXEstablecimientos(Set aplicacionXEstablecimientos) {
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
	}

	public Set getFaseXAplicacions() {
		return this.faseXAplicacions;
	}

	public void setFaseXAplicacions(Set faseXAplicacions) {
		this.faseXAplicacions = faseXAplicacions;
	}

	public Set getDocumentoTipos() {
		return this.documentoTipos;
	}

	public void setDocumentoTipos(Set documentoTipos) {
		this.documentoTipos = documentoTipos;
	}

	public Set getCcCapacitacions() {
		return this.ccCapacitacions;
	}

	public void setCcCapacitacions(Set ccCapacitacions) {
		this.ccCapacitacions = ccCapacitacions;
	}

	public Set getAplicacionXUsuarioTipos() {
		return this.aplicacionXUsuarioTipos;
	}

	public void setAplicacionXUsuarioTipos(Set aplicacionXUsuarioTipos) {
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

	public Set getDocumentoEstados() {
		return this.documentoEstados;
	}

	public void setDocumentoEstados(Set documentoEstados) {
		this.documentoEstados = documentoEstados;
	}

	public AplicacionDTO getAplicacionDTO() {
		AplicacionDTO adto = new AplicacionDTO();
		adto.setId(id);
		adto.setNombre(nombre);
		return adto;
	}

}
