package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXNivelXUsuarioTipoXCo generated by hbm2java
 */
public class AplicacionXNivelXUsuarioTipoXCo implements java.io.Serializable {

	private Integer id;
	private AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo;
	private Co co;
	private Integer preseleccion;
	private Integer seleccion;

	public AplicacionXNivelXUsuarioTipoXCo() {
	}

	public AplicacionXNivelXUsuarioTipoXCo(Integer id) {
		this.id = id;
	}

	public AplicacionXNivelXUsuarioTipoXCo(Integer id,
			AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo, Co co,
			Integer preseleccion, Integer seleccion) {
		this.id = id;
		this.aplicacionXNivelXUsuarioTipo = aplicacionXNivelXUsuarioTipo;
		this.co = co;
		this.preseleccion = preseleccion;
		this.seleccion = seleccion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AplicacionXNivelXUsuarioTipo getAplicacionXNivelXUsuarioTipo() {
		return this.aplicacionXNivelXUsuarioTipo;
	}

	public void setAplicacionXNivelXUsuarioTipo(
			AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo) {
		this.aplicacionXNivelXUsuarioTipo = aplicacionXNivelXUsuarioTipo;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public Integer getPreseleccion() {
		return this.preseleccion;
	}

	public void setPreseleccion(Integer preseleccion) {
		this.preseleccion = preseleccion;
	}

	public Integer getSeleccion() {
		return this.seleccion;
	}

	public void setSeleccion(Integer seleccion) {
		this.seleccion = seleccion;
	}

}
