package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionCapacitacion generated by hbm2java
 */
public class AplicacionCapacitacion implements java.io.Serializable {

	private AplicacionCapacitacionId id;

	public AplicacionCapacitacion() {
	}

	public AplicacionCapacitacion(AplicacionCapacitacionId id) {
		this.id = id;
	}

	public AplicacionCapacitacionId getId() {
		return this.id;
	}

	public void setId(AplicacionCapacitacionId id) {
		this.id = id;
	}

}
