package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXNivelXUsuarioTipoXCoId generated by hbm2java
 */
public class AplicacionXNivelXUsuarioTipoXCoId implements java.io.Serializable {

	private Integer aplicacionXNivelUsuarioTipoId;
	private Integer coId;

	public AplicacionXNivelXUsuarioTipoXCoId() {
	}

	public AplicacionXNivelXUsuarioTipoXCoId(Integer aplicacionXNivelUsuarioTipoId,
			Integer coId) {
		this.aplicacionXNivelUsuarioTipoId = aplicacionXNivelUsuarioTipoId;
		this.coId = coId;
	}

	public Integer getAplicacionXNivelUsuarioTipoId() {
		return this.aplicacionXNivelUsuarioTipoId;
	}

	public void setAplicacionXNivelUsuarioTipoId(
			Integer aplicacionXNivelUsuarioTipoId) {
		this.aplicacionXNivelUsuarioTipoId = aplicacionXNivelUsuarioTipoId;
	}

	public Integer getCoId() {
		return this.coId;
	}

	public void setCoId(Integer coId) {
		this.coId = coId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AplicacionXNivelXUsuarioTipoXCoId))
			return false;
		AplicacionXNivelXUsuarioTipoXCoId castOther = (AplicacionXNivelXUsuarioTipoXCoId) other;

		return (this.getAplicacionXNivelUsuarioTipoId() == castOther
				.getAplicacionXNivelUsuarioTipoId())
				&& (this.getCoId() == castOther.getCoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getAplicacionXNivelUsuarioTipoId();
		result = 37 * result + this.getCoId();
		return result;
	}

}
