package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXUsuarioTipoXCarrera generated by hbm2java
 */
public class AplicacionXUsuarioTipoXCarrera implements java.io.Serializable {

	private int id;
	private AplicacionXUsuarioTipo aplicacionXUsuarioTipo;
	private Carrera carrera;
	private Integer puntaje;

	public AplicacionXUsuarioTipoXCarrera() {
	}

	public AplicacionXUsuarioTipoXCarrera(int id) {
		this.id = id;
	}

	public AplicacionXUsuarioTipoXCarrera(int id,
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo, Carrera carrera,
			Integer puntaje) {
		this.id = id;
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
		this.carrera = carrera;
		this.puntaje = puntaje;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AplicacionXUsuarioTipo getAplicacionXUsuarioTipo() {
		return this.aplicacionXUsuarioTipo;
	}

	public void setAplicacionXUsuarioTipo(
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo) {
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Integer getPuntaje() {
		return this.puntaje;
	}

	public void setPuntaje(Integer puntaje) {
		this.puntaje = puntaje;
	}

}
