package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXNivelXUsuarioTipoXComuna generated by hbm2java
 */
public class AplicacionXNivelXUsuarioTipoXComuna implements
		java.io.Serializable {

	private Integer id;
	private AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo;
	private Comuna comuna;
	private Integer preseleccion;

	public AplicacionXNivelXUsuarioTipoXComuna() {
	}

	public AplicacionXNivelXUsuarioTipoXComuna(Integer id) {
		this.id = id;
	}

	public AplicacionXNivelXUsuarioTipoXComuna(Integer id,
			AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo,
			Comuna comuna, Integer preseleccion) {
		this.id = id;
		this.aplicacionXNivelXUsuarioTipo = aplicacionXNivelXUsuarioTipo;
		this.comuna = comuna;
		this.preseleccion = preseleccion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AplicacionXNivelXUsuarioTipo getAplicacionXNivelXUsuarioTipo() {
		return this.aplicacionXNivelXUsuarioTipo;
	}

	public void setAplicacionXNivelXUsuarioTipo(
			AplicacionXNivelXUsuarioTipo aplicacionXNivelXUsuarioTipo) {
		this.aplicacionXNivelXUsuarioTipo = aplicacionXNivelXUsuarioTipo;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public Integer getPreseleccion() {
		return this.preseleccion;
	}

	public void setPreseleccion(Integer preseleccion) {
		this.preseleccion = preseleccion;
	}

}
