package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXUsuarioTipoXPermisoId generated by hbm2java
 */
public class AplicacionXUsuarioTipoXPermisoId implements java.io.Serializable {

	private Integer aplicacionXUsuarioTipoId;
	private Integer permisoId;

	public AplicacionXUsuarioTipoXPermisoId() {
	}

	public AplicacionXUsuarioTipoXPermisoId(Integer aplicacionXUsuarioTipoId,
			Integer permisoId) {
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
		this.permisoId = permisoId;
	}

	public Integer getAplicacionXUsuarioTipoId() {
		return this.aplicacionXUsuarioTipoId;
	}

	public void setAplicacionXUsuarioTipoId(Integer aplicacionXUsuarioTipoId) {
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
	}

	public Integer getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(Integer permisoId) {
		this.permisoId = permisoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AplicacionXUsuarioTipoXPermisoId))
			return false;
		AplicacionXUsuarioTipoXPermisoId castOther = (AplicacionXUsuarioTipoXPermisoId) other;

		return (this.getAplicacionXUsuarioTipoId() == castOther
				.getAplicacionXUsuarioTipoId())
				&& (this.getPermisoId() == castOther.getPermisoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getAplicacionXUsuarioTipoId();
		result = 37 * result + this.getPermisoId();
		return result;
	}

}
