package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AplicacionXUsuarioTipo generated by hbm2java
 */
public class AplicacionXUsuarioTipo implements java.io.Serializable {

	private int id;
	private Aplicacion aplicacion;
	private UsuarioTipo usuarioTipo;
	private Contrato contrato;
	private CarreraEstado carreraEstado;
	private Integer edadMinima;
	private Integer anoIngresoMaximo;
	private Set requisitoXAplicacionXUsuarioTipos = new HashSet(0);
	private Set aplicacionXUsuarioTipoXPermisos = new HashSet(0);
	private Set aplicacionXUsuarioTipoXCarreras = new HashSet(0);

	public AplicacionXUsuarioTipo() {
	}

	public AplicacionXUsuarioTipo(int id) {
		this.id = id;
	}

	public AplicacionXUsuarioTipo(int id, Aplicacion aplicacion,
			UsuarioTipo usuarioTipo, Contrato contrato,
			CarreraEstado carreraEstado, Integer edadMinima,
			Integer anoIngresoMaximo, Set requisitoXAplicacionXUsuarioTipos,
			Set aplicacionXUsuarioTipoXPermisos,
			Set aplicacionXUsuarioTipoXCarreras) {
		this.id = id;
		this.aplicacion = aplicacion;
		this.usuarioTipo = usuarioTipo;
		this.contrato = contrato;
		this.carreraEstado = carreraEstado;
		this.edadMinima = edadMinima;
		this.anoIngresoMaximo = anoIngresoMaximo;
		this.requisitoXAplicacionXUsuarioTipos = requisitoXAplicacionXUsuarioTipos;
		this.aplicacionXUsuarioTipoXPermisos = aplicacionXUsuarioTipoXPermisos;
		this.aplicacionXUsuarioTipoXCarreras = aplicacionXUsuarioTipoXCarreras;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	public CarreraEstado getCarreraEstado() {
		return this.carreraEstado;
	}

	public void setCarreraEstado(CarreraEstado carreraEstado) {
		this.carreraEstado = carreraEstado;
	}

	public Integer getEdadMinima() {
		return this.edadMinima;
	}

	public void setEdadMinima(Integer edadMinima) {
		this.edadMinima = edadMinima;
	}

	public Integer getAnoIngresoMaximo() {
		return this.anoIngresoMaximo;
	}

	public void setAnoIngresoMaximo(Integer anoIngresoMaximo) {
		this.anoIngresoMaximo = anoIngresoMaximo;
	}

	public Set getRequisitoXAplicacionXUsuarioTipos() {
		return this.requisitoXAplicacionXUsuarioTipos;
	}

	public void setRequisitoXAplicacionXUsuarioTipos(
			Set requisitoXAplicacionXUsuarioTipos) {
		this.requisitoXAplicacionXUsuarioTipos = requisitoXAplicacionXUsuarioTipos;
	}

	public Set getAplicacionXUsuarioTipoXPermisos() {
		return this.aplicacionXUsuarioTipoXPermisos;
	}

	public void setAplicacionXUsuarioTipoXPermisos(
			Set aplicacionXUsuarioTipoXPermisos) {
		this.aplicacionXUsuarioTipoXPermisos = aplicacionXUsuarioTipoXPermisos;
	}

	public Set getAplicacionXUsuarioTipoXCarreras() {
		return this.aplicacionXUsuarioTipoXCarreras;
	}

	public void setAplicacionXUsuarioTipoXCarreras(
			Set aplicacionXUsuarioTipoXCarreras) {
		this.aplicacionXUsuarioTipoXCarreras = aplicacionXUsuarioTipoXCarreras;
	}

}
