package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * AplicacionXNivelXUsuarioTipo generated by hbm2java
 */
public class AplicacionXNivelXUsuarioTipo implements java.io.Serializable {

	private int id;
	private UsuarioTipo usuarioTipo;
	private AplicacionXNivel aplicacionXNivel;
	private Integer montoPago;
	private Set avisoXAplicacionXNivelXUsuarioTipos = new HashSet(0);
	private Set archvicoXAplicacionXNivelXUsuarioTipos = new HashSet(0);
	private Set aplicacionXNivelXUsuarioTipoXCos = new HashSet(0);

	public AplicacionXNivelXUsuarioTipo() {
	}

	public AplicacionXNivelXUsuarioTipo(int id) {
		this.id = id;
	}

	public AplicacionXNivelXUsuarioTipo(int id, UsuarioTipo usuarioTipo,
			AplicacionXNivel aplicacionXNivel, Integer montoPago,
			Set avisoXAplicacionXNivelXUsuarioTipos,
			Set archvicoXAplicacionXNivelXUsuarioTipos,
			Set aplicacionXNivelXUsuarioTipoXCos) {
		this.id = id;
		this.usuarioTipo = usuarioTipo;
		this.aplicacionXNivel = aplicacionXNivel;
		this.montoPago = montoPago;
		this.avisoXAplicacionXNivelXUsuarioTipos = avisoXAplicacionXNivelXUsuarioTipos;
		this.archvicoXAplicacionXNivelXUsuarioTipos = archvicoXAplicacionXNivelXUsuarioTipos;
		this.aplicacionXNivelXUsuarioTipoXCos = aplicacionXNivelXUsuarioTipoXCos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public AplicacionXNivel getAplicacionXNivel() {
		return this.aplicacionXNivel;
	}

	public void setAplicacionXNivel(AplicacionXNivel aplicacionXNivel) {
		this.aplicacionXNivel = aplicacionXNivel;
	}

	public Integer getMontoPago() {
		return this.montoPago;
	}

	public void setMontoPago(Integer montoPago) {
		this.montoPago = montoPago;
	}

	public Set getAvisoXAplicacionXNivelXUsuarioTipos() {
		return this.avisoXAplicacionXNivelXUsuarioTipos;
	}

	public void setAvisoXAplicacionXNivelXUsuarioTipos(
			Set avisoXAplicacionXNivelXUsuarioTipos) {
		this.avisoXAplicacionXNivelXUsuarioTipos = avisoXAplicacionXNivelXUsuarioTipos;
	}

	public Set getArchvicoXAplicacionXNivelXUsuarioTipos() {
		return this.archvicoXAplicacionXNivelXUsuarioTipos;
	}

	public void setArchvicoXAplicacionXNivelXUsuarioTipos(
			Set archvicoXAplicacionXNivelXUsuarioTipos) {
		this.archvicoXAplicacionXNivelXUsuarioTipos = archvicoXAplicacionXNivelXUsuarioTipos;
	}

	public Set getAplicacionXNivelXUsuarioTipoXCos() {
		return this.aplicacionXNivelXUsuarioTipoXCos;
	}

	public void setAplicacionXNivelXUsuarioTipoXCos(
			Set aplicacionXNivelXUsuarioTipoXCos) {
		this.aplicacionXNivelXUsuarioTipoXCos = aplicacionXNivelXUsuarioTipoXCos;
	}

}
