package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXUsuarioTipoXCarreraId generated by hbm2java
 */
public class AplicacionXUsuarioTipoXCarreraId implements java.io.Serializable {

	private Integer aplicacionXUsuarioTipoId;
	private Integer carreraId;

	public AplicacionXUsuarioTipoXCarreraId() {
	}

	public AplicacionXUsuarioTipoXCarreraId(Integer aplicacionXUsuarioTipoId,
			Integer carreraId) {
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
		this.carreraId = carreraId;
	}

	public Integer getAplicacionXUsuarioTipoId() {
		return this.aplicacionXUsuarioTipoId;
	}

	public void setAplicacionXUsuarioTipoId(Integer aplicacionXUsuarioTipoId) {
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
	}

	public Integer getCarreraId() {
		return this.carreraId;
	}

	public void setCarreraId(Integer carreraId) {
		this.carreraId = carreraId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AplicacionXUsuarioTipoXCarreraId))
			return false;
		AplicacionXUsuarioTipoXCarreraId castOther = (AplicacionXUsuarioTipoXCarreraId) other;

		return (this.getAplicacionXUsuarioTipoId() == castOther
				.getAplicacionXUsuarioTipoId())
				&& (this.getCarreraId() == castOther.getCarreraId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getAplicacionXUsuarioTipoId();
		result = 37 * result + this.getCarreraId();
		return result;
	}

}
