package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * AplicacionXEstablecimientoId generated by hbm2java
 */
public class AplicacionXEstablecimientoId implements java.io.Serializable {

	private Integer aplicacionId;
	private Integer establecimientoId;

	public AplicacionXEstablecimientoId() {
	}

	public AplicacionXEstablecimientoId(Integer aplicacionId, Integer establecimientoId) {
		this.aplicacionId = aplicacionId;
		this.establecimientoId = establecimientoId;
	}

	public Integer getAplicacionId() {
		return this.aplicacionId;
	}

	public void setAplicacionId(Integer aplicacionId) {
		this.aplicacionId = aplicacionId;
	}

	public Integer getEstablecimientoId() {
		return this.establecimientoId;
	}

	public void setEstablecimientoId(Integer establecimientoId) {
		this.establecimientoId = establecimientoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AplicacionXEstablecimientoId))
			return false;
		AplicacionXEstablecimientoId castOther = (AplicacionXEstablecimientoId) other;

		return (this.getAplicacionId() == castOther.getAplicacionId())
				&& (this.getEstablecimientoId() == castOther
						.getEstablecimientoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getAplicacionId();
		result = 37 * result + this.getEstablecimientoId();
		return result;
	}

}
