package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AplicacionXNivelXActividadTipo generated by hbm2java
 */
public class AplicacionXNivelXActividadTipo implements java.io.Serializable {

	private int id;
	private AplicacionXNivel aplicacionXNivel;
	private ActividadTipo actividadTipo;
	private Date fechaInicio;
	private Date fechaTermino;
	private Set actividads = new HashSet(0);
	private Set rutas = new HashSet(0);
	private Set suplenteXCos = new HashSet(0);

	public AplicacionXNivelXActividadTipo() {
	}

	public AplicacionXNivelXActividadTipo(int id) {
		this.id = id;
	}

	public AplicacionXNivelXActividadTipo(int id,
			AplicacionXNivel aplicacionXNivel, ActividadTipo actividadTipo,
			Date fechaInicio, Date fechaTermino, Set actividads, Set rutas,
			Set suplenteXCos) {
		this.id = id;
		this.aplicacionXNivel = aplicacionXNivel;
		this.actividadTipo = actividadTipo;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
		this.actividads = actividads;
		this.rutas = rutas;
		this.suplenteXCos = suplenteXCos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AplicacionXNivel getAplicacionXNivel() {
		return this.aplicacionXNivel;
	}

	public void setAplicacionXNivel(AplicacionXNivel aplicacionXNivel) {
		this.aplicacionXNivel = aplicacionXNivel;
	}

	public ActividadTipo getActividadTipo() {
		return this.actividadTipo;
	}

	public void setActividadTipo(ActividadTipo actividadTipo) {
		this.actividadTipo = actividadTipo;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Set getActividads() {
		return this.actividads;
	}

	public void setActividads(Set actividads) {
		this.actividads = actividads;
	}

	public Set getRutas() {
		return this.rutas;
	}

	public void setRutas(Set rutas) {
		this.rutas = rutas;
	}

	public Set getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(Set suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

}
