package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.DocumentoDTO;

/**
 * Archivo generated by hbm2java
 */
public class Archivo implements java.io.Serializable {

	private Integer id;
	private String titulo;
	private Date fechaPublicacion;
	private String rutaArchivo;
	private boolean visible;
	private String mimeType;
	private String ipServer;
	private List<GuiaDespacho> guiaDespachos = new ArrayList<GuiaDespacho>(0);
	private List<Documento> documentos = new ArrayList<Documento>(0);
	private List<ArchvicoXAplicacionXNivelXUsuarioTipo> archvicoXAplicacionXNivelXUsuarioTipos = new ArrayList<ArchvicoXAplicacionXNivelXUsuarioTipo>(
			0);

	public Archivo() {
	}

	public Archivo(Integer id, boolean visible) {
		this.id = id;
		this.visible = visible;
	}

	public Archivo(
			Integer id,
			String titulo,
			Date fechaPublicacion,
			String rutaArchivo,
			boolean visible,
			String mimeType,
			String ipServer,
			List<GuiaDespacho> guiaDespachos,
			List<Documento> documentos,
			List<ArchvicoXAplicacionXNivelXUsuarioTipo> archvicoXAplicacionXNivelXUsuarioTipos) {
		this.id = id;
		this.titulo = titulo;
		this.fechaPublicacion = fechaPublicacion;
		this.rutaArchivo = rutaArchivo;
		this.visible = visible;
		this.mimeType = mimeType;
		this.ipServer = ipServer;
		this.guiaDespachos = guiaDespachos;
		this.documentos = documentos;
		this.archvicoXAplicacionXNivelXUsuarioTipos = archvicoXAplicacionXNivelXUsuarioTipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public String getRutaArchivo() {
		return this.rutaArchivo;
	}

	public void setRutaArchivo(String rutaArchivo) {
		this.rutaArchivo = rutaArchivo;
	}

	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public String getIpServer() {
		return this.ipServer;
	}

	public void setIpServer(String ipServer) {
		this.ipServer = ipServer;
	}

	public List<GuiaDespacho> getGuiaDespachos() {
		return this.guiaDespachos;
	}

	public void setGuiaDespachos(List<GuiaDespacho> guiaDespachos) {
		this.guiaDespachos = guiaDespachos;
	}

	public List<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(List<Documento> documentos) {
		this.documentos = documentos;
	}

	public List<ArchvicoXAplicacionXNivelXUsuarioTipo> getArchvicoXAplicacionXNivelXUsuarioTipos() {
		return this.archvicoXAplicacionXNivelXUsuarioTipos;
	}

	public void setArchvicoXAplicacionXNivelXUsuarioTipos(
			List<ArchvicoXAplicacionXNivelXUsuarioTipo> archvicoXAplicacionXNivelXUsuarioTipos) {
		this.archvicoXAplicacionXNivelXUsuarioTipos = archvicoXAplicacionXNivelXUsuarioTipos;
	}

	/**
	 * @param baseURL
	 * @return
	 */
	public DocumentoDTO getDocumentoDTO(String baseURL) {
		DocumentoDTO ddto = new DocumentoDTO();
		ddto.setId(id);
		ddto.setName(titulo);
		ddto.setUrl(baseURL + "/download?id=" + id + "&file=" + titulo);
		return ddto;
	}

}
