package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Aviso generated by hbm2java
 */
public class Aviso implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private String titulo;
	private String texto;
	private Date fechaPublicacion;
	private boolean visible;
	private boolean general;
	private List<AvisoXAplicacionXNivelXUsuarioTipo> avisoXAplicacionXNivelXUsuarioTipos = new ArrayList<AvisoXAplicacionXNivelXUsuarioTipo>(0);

	public Aviso() {
	}

	public Aviso(Integer id, boolean visible, boolean general) {
		this.id = id;
		this.visible = visible;
		this.general = general;
	}

	public Aviso(Integer id, Usuario usuario, String titulo, String texto,
			Date fechaPublicacion, boolean visible, boolean general,
			List<AvisoXAplicacionXNivelXUsuarioTipo> avisoXAplicacionXNivelXUsuarioTipos) {
		this.id = id;
		this.usuario = usuario;
		this.titulo = titulo;
		this.texto = texto;
		this.fechaPublicacion = fechaPublicacion;
		this.visible = visible;
		this.general = general;
		this.avisoXAplicacionXNivelXUsuarioTipos = avisoXAplicacionXNivelXUsuarioTipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public Date getFechaPublicacion() {
		return this.fechaPublicacion;
	}

	public void setFechaPublicacion(Date fechaPublicacion) {
		this.fechaPublicacion = fechaPublicacion;
	}

	public boolean isVisible() {
		return this.visible;
	}

	public void setVisible(boolean visible) {
		this.visible = visible;
	}

	public boolean isGeneral() {
		return this.general;
	}

	public void setGeneral(boolean general) {
		this.general = general;
	}

	public List<AvisoXAplicacionXNivelXUsuarioTipo> getAvisoXAplicacionXNivelXUsuarioTipos() {
		return this.avisoXAplicacionXNivelXUsuarioTipos;
	}

	public void setAvisoXAplicacionXNivelXUsuarioTipos(
			List<AvisoXAplicacionXNivelXUsuarioTipo> avisoXAplicacionXNivelXUsuarioTipos) {
		this.avisoXAplicacionXNivelXUsuarioTipos = avisoXAplicacionXNivelXUsuarioTipos;
	}

}
