package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	private Integer id;
	private Universidad universidad;
	private String nombre;
	private List<Usuario> usuarios = new ArrayList<Usuario>(0);
	private List<AplicacionXUsuarioTipoXCarrera> aplicacionXUsuarioTipoXCarreras = new ArrayList<AplicacionXUsuarioTipoXCarrera>(0);

	public Carrera() {
	}

	public Carrera(Integer id) {
		this.id = id;
	}

	public Carrera(Integer id, Universidad universidad, String nombre,
			List<Usuario> usuarios, List<AplicacionXUsuarioTipoXCarrera> aplicacionXUsuarioTipoXCarreras) {
		this.id = id;
		this.universidad = universidad;
		this.nombre = nombre;
		this.usuarios = usuarios;
		this.aplicacionXUsuarioTipoXCarreras = aplicacionXUsuarioTipoXCarreras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Universidad getUniversidad() {
		return this.universidad;
	}

	public void setUniversidad(Universidad universidad) {
		this.universidad = universidad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public List<AplicacionXUsuarioTipoXCarrera> getAplicacionXUsuarioTipoXCarreras() {
		return this.aplicacionXUsuarioTipoXCarreras;
	}

	public void setAplicacionXUsuarioTipoXCarreras(
			List<AplicacionXUsuarioTipoXCarrera> aplicacionXUsuarioTipoXCarreras) {
		this.aplicacionXUsuarioTipoXCarreras = aplicacionXUsuarioTipoXCarreras;
	}

}
