package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CarreraEstado generated by hbm2java
 */
public class CarreraEstado implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set usuarios = new HashSet(0);
	private Set aplicacionXUsuarioTipos = new HashSet(0);

	public CarreraEstado() {
	}

	public CarreraEstado(int id) {
		this.id = id;
	}

	public CarreraEstado(int id, String nombre, Set usuarios,
			Set aplicacionXUsuarioTipos) {
		this.id = id;
		this.nombre = nombre;
		this.usuarios = usuarios;
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getAplicacionXUsuarioTipos() {
		return this.aplicacionXUsuarioTipos;
	}

	public void setAplicacionXUsuarioTipos(Set aplicacionXUsuarioTipos) {
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

}
