package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CcCapacitacion generated by hbm2java
 */
public class CcCapacitacion implements java.io.Serializable {

	private int id;
	private CcSala ccSala;
	private Aplicacion aplicacion;
	private UsuarioTipo usuarioTipo;
	private CcModulo ccModulo;
	private Date dia;
	private Set usuarioXCcCapacitacions = new HashSet(0);

	public CcCapacitacion() {
	}

	public CcCapacitacion(int id) {
		this.id = id;
	}

	public CcCapacitacion(int id, CcSala ccSala, Aplicacion aplicacion,
			UsuarioTipo usuarioTipo, CcModulo ccModulo, Date dia,
			Set usuarioXCcCapacitacions) {
		this.id = id;
		this.ccSala = ccSala;
		this.aplicacion = aplicacion;
		this.usuarioTipo = usuarioTipo;
		this.ccModulo = ccModulo;
		this.dia = dia;
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CcSala getCcSala() {
		return this.ccSala;
	}

	public void setCcSala(CcSala ccSala) {
		this.ccSala = ccSala;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public CcModulo getCcModulo() {
		return this.ccModulo;
	}

	public void setCcModulo(CcModulo ccModulo) {
		this.ccModulo = ccModulo;
	}

	public Date getDia() {
		return this.dia;
	}

	public void setDia(Date dia) {
		this.dia = dia;
	}

	public Set getUsuarioXCcCapacitacions() {
		return this.usuarioXCcCapacitacions;
	}

	public void setUsuarioXCcCapacitacions(Set usuarioXCcCapacitacions) {
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

}
