package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.ArrayList;
import java.util.List;

/**
 * CcCapacitacion generated by hbm2java
 */
public class CcCapacitacion implements java.io.Serializable {

	private Integer id;
	private CcSala ccSala;
	private UsuarioTipo usuarioTipo;
	private CcModulo ccModulo;
	private Date dia;
	private List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions = new ArrayList<UsuarioXCcCapacitacion>(0);

	public CcCapacitacion() {
	}

	public CcCapacitacion(Integer id) {
		this.id = id;
	}

	public CcCapacitacion(Integer id, CcSala ccSala, UsuarioTipo usuarioTipo,
			CcModulo ccModulo, Date dia, List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions) {
		this.id = id;
		this.ccSala = ccSala;
		this.usuarioTipo = usuarioTipo;
		this.ccModulo = ccModulo;
		this.dia = dia;
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CcSala getCcSala() {
		return this.ccSala;
	}

	public void setCcSala(CcSala ccSala) {
		this.ccSala = ccSala;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public CcModulo getCcModulo() {
		return this.ccModulo;
	}

	public void setCcModulo(CcModulo ccModulo) {
		this.ccModulo = ccModulo;
	}

	public Date getDia() {
		return this.dia;
	}

	public void setDia(Date dia) {
		this.dia = dia;
	}

	public List<UsuarioXCcCapacitacion> getUsuarioXCcCapacitacions() {
		return this.usuarioXCcCapacitacions;
	}

	public void setUsuarioXCcCapacitacions(List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions) {
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

}
