package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CcModulo generated by hbm2java
 */
public class CcModulo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Date horaInicio;
	private Date horaTermino;
	private Set ccCapacitacions = new HashSet(0);

	public CcModulo() {
	}

	public CcModulo(int id) {
		this.id = id;
	}

	public CcModulo(int id, String nombre, Date horaInicio, Date horaTermino,
			Set ccCapacitacions) {
		this.id = id;
		this.nombre = nombre;
		this.horaInicio = horaInicio;
		this.horaTermino = horaTermino;
		this.ccCapacitacions = ccCapacitacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	public Date getHoraTermino() {
		return this.horaTermino;
	}

	public void setHoraTermino(Date horaTermino) {
		this.horaTermino = horaTermino;
	}

	public Set getCcCapacitacions() {
		return this.ccCapacitacions;
	}

	public void setCcCapacitacions(Set ccCapacitacions) {
		this.ccCapacitacions = ccCapacitacions;
	}

}
