package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CcSala generated by hbm2java
 */
public class CcSala implements java.io.Serializable {

	private int id;
	private Cc cc;
	private String nombre;
	private Set ccCapacitacions = new HashSet(0);

	public CcSala() {
	}

	public CcSala(int id) {
		this.id = id;
	}

	public CcSala(int id, Cc cc, String nombre, Set ccCapacitacions) {
		this.id = id;
		this.cc = cc;
		this.nombre = nombre;
		this.ccCapacitacions = ccCapacitacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cc getCc() {
		return this.cc;
	}

	public void setCc(Cc cc) {
		this.cc = cc;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCcCapacitacions() {
		return this.ccCapacitacions;
	}

	public void setCcCapacitacions(Set ccCapacitacions) {
		this.ccCapacitacions = ccCapacitacions;
	}

}
