package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * CcXComuna generated by hbm2java
 */
public class CcXComuna implements java.io.Serializable {

	private int id;
	private Cc cc;
	private Comuna comuna;

	public CcXComuna() {
	}

	public CcXComuna(int id) {
		this.id = id;
	}

	public CcXComuna(int id, Cc cc, Comuna comuna) {
		this.id = id;
		this.cc = cc;
		this.comuna = comuna;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Cc getCc() {
		return this.cc;
	}

	public void setCc(Cc cc) {
		this.cc = cc;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

}
