package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * CcXComuna generated by hbm2java
 */
public class CcXComuna implements java.io.Serializable {

	private Integer id;
	private Cc cc;
	private Comuna comuna;

	public CcXComuna() {
	}

	public CcXComuna(Integer id) {
		this.id = id;
	}

	public CcXComuna(Integer id, Cc cc, Comuna comuna) {
		this.id = id;
		this.cc = cc;
		this.comuna = comuna;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Cc getCc() {
		return this.cc;
	}

	public void setCc(Cc cc) {
		this.cc = cc;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

}
