package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CentroRegional generated by hbm2java
 */
public class CentroRegional implements java.io.Serializable {

	private int id;
	private Aplicacion aplicacion;
	private String nombre;
	private Set zonas = new HashSet(0);
	private Set jrXCentroRegionals = new HashSet(0);

	public CentroRegional() {
	}

	public CentroRegional(int id) {
		this.id = id;
	}

	public CentroRegional(int id, Aplicacion aplicacion, String nombre,
			Set zonas, Set jrXCentroRegionals) {
		this.id = id;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.zonas = zonas;
		this.jrXCentroRegionals = jrXCentroRegionals;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getZonas() {
		return this.zonas;
	}

	public void setZonas(Set zonas) {
		this.zonas = zonas;
	}

	public Set getJrXCentroRegionals() {
		return this.jrXCentroRegionals;
	}

	public void setJrXCentroRegionals(Set jrXCentroRegionals) {
		this.jrXCentroRegionals = jrXCentroRegionals;
	}

}
