package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private int id;
	private String nombre;
	private String codigo;
	private Set rutas = new HashSet(0);

	public Color() {
	}

	public Color(int id) {
		this.id = id;
	}

	public Color(int id, String nombre, String codigo, Set rutas) {
		this.id = id;
		this.nombre = nombre;
		this.codigo = codigo;
		this.rutas = rutas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getRutas() {
		return this.rutas;
	}

	public void setRutas(Set rutas) {
		this.rutas = rutas;
	}

}
