package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Color generated by hbm2java
 */
public class Color implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String codigo;
	private List<Ruta> rutas = new ArrayList<Ruta>(0);

	public Color() {
	}

	public Color(Integer id) {
		this.id = id;
	}

	public Color(Integer id, String nombre, String codigo, List<Ruta> rutas) {
		this.id = id;
		this.nombre = nombre;
		this.codigo = codigo;
		this.rutas = rutas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

}
