package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CompaniaTelefono generated by hbm2java
 */
public class CompaniaTelefono implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set usuarios = new HashSet(0);

	public CompaniaTelefono() {
	}

	public CompaniaTelefono(int id) {
		this.id = id;
	}

	public CompaniaTelefono(int id, String nombre, Set usuarios) {
		this.id = id;
		this.nombre = nombre;
		this.usuarios = usuarios;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
