package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.SectorDTO;

/**
 * Comuna generated by hbm2java
 */
public class Comuna implements java.io.Serializable {

	private int id;
	private Provincia provincia;
	private String nombre;
	private Set ccs = new HashSet(0);
	private Set establecimientos = new HashSet(0);
	private Set cos = new HashSet(0);
	private Set usuarios = new HashSet(0);
	private Set usuarioXComunas = new HashSet(0);
	private Set transportes = new HashSet(0);
	private Set ccXComunas = new HashSet(0);

	public Comuna() {
	}

	public Comuna(int id) {
		this.id = id;
	}

	public Comuna(int id, Provincia provincia, String nombre, Set ccs,
			Set establecimientos, Set cos, Set usuarios, Set usuarioXComunas,
			Set transportes, Set ccXComunas) {
		this.id = id;
		this.provincia = provincia;
		this.nombre = nombre;
		this.ccs = ccs;
		this.establecimientos = establecimientos;
		this.cos = cos;
		this.usuarios = usuarios;
		this.usuarioXComunas = usuarioXComunas;
		this.transportes = transportes;
		this.ccXComunas = ccXComunas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCcs() {
		return this.ccs;
	}

	public void setCcs(Set ccs) {
		this.ccs = ccs;
	}

	public Set getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set establecimientos) {
		this.establecimientos = establecimientos;
	}

	public Set getCos() {
		return this.cos;
	}

	public void setCos(Set cos) {
		this.cos = cos;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getUsuarioXComunas() {
		return this.usuarioXComunas;
	}

	public void setUsuarioXComunas(Set usuarioXComunas) {
		this.usuarioXComunas = usuarioXComunas;
	}

	public Set getTransportes() {
		return this.transportes;
	}

	public void setTransportes(Set transportes) {
		this.transportes = transportes;
	}

	public Set getCcXComunas() {
		return this.ccXComunas;
	}

	public void setCcXComunas(Set ccXComunas) {
		this.ccXComunas = ccXComunas;
	}

	public SectorDTO getSectorDTO() {
		SectorDTO sdto = new SectorDTO();
		sdto.setIdSector(id);
		sdto.setSector(nombre);
		sdto.setTipoSector(SectorDTO.TIPO_COMUNA);
		return sdto;
	}

}
