package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Contrato generated by hbm2java
 */
public class Contrato implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String template;
	private List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos = new ArrayList<AplicacionXUsuarioTipo>(0);

	public Contrato() {
	}

	public Contrato(Integer id) {
		this.id = id;
	}

	public Contrato(Integer id, String nombre, String template,
			List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos) {
		this.id = id;
		this.nombre = nombre;
		this.template = template;
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTemplate() {
		return this.template;
	}

	public void setTemplate(String template) {
		this.template = template;
	}

	public List<AplicacionXUsuarioTipo> getAplicacionXUsuarioTipos() {
		return this.aplicacionXUsuarioTipos;
	}

	public void setAplicacionXUsuarioTipos(List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos) {
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

}
