package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ContactoCargo generated by hbm2java
 */
public class ContactoCargo implements java.io.Serializable {

	private int id;
	private String nombre;
	private boolean base;
	private Set actividads = new HashSet(0);

	public ContactoCargo() {
	}

	public ContactoCargo(int id, boolean base) {
		this.id = id;
		this.base = base;
	}

	public ContactoCargo(int id, String nombre, boolean base, Set actividads) {
		this.id = id;
		this.nombre = nombre;
		this.base = base;
		this.actividads = actividads;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isBase() {
		return this.base;
	}

	public void setBase(boolean base) {
		this.base = base;
	}

	public Set getActividads() {
		return this.actividads;
	}

	public void setActividads(Set actividads) {
		this.actividads = actividads;
	}

}
