package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.CargoDTO;

/**
 * ContactoCargo generated by hbm2java
 */
public class ContactoCargo implements java.io.Serializable {

	public static final String DIRECTOR = "Director";
	public static final String JEFE_UTP = "Jefe UTP";
	public static final String PROFESOR = "Profesor";
	public static final String SECRETARIA = "Secretaria";
	private Integer id;
	private String nombre;
	private boolean base;
	private List<Actividad> actividads = new ArrayList<Actividad>(0);

	public ContactoCargo() {
	}

	public ContactoCargo(Integer id, boolean base) {
		this.id = id;
		this.base = base;
	}

	public ContactoCargo(Integer id, String nombre, boolean base,
			List<Actividad> actividads) {
		this.id = id;
		this.nombre = nombre;
		this.base = base;
		this.actividads = actividads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isBase() {
		return this.base;
	}

	public void setBase(boolean base) {
		this.base = base;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

	/**
	 * @return
	 */
	public CargoDTO getCargoDTO() {
		CargoDTO cdto = new CargoDTO();
		cdto.setId(id);
		cdto.setCargo(nombre);
		return cdto;
	}

}
