package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private Integer id;
	private AplicacionXNivel aplicacionXNivel;
	private Establecimiento establecimiento;
	private String nombre;
	private String codigo;
	private boolean emergente;
	private boolean nee;
	private Integer cantidadAlumnos;
	private List<Actividad> actividads = new ArrayList<Actividad>(0);

	public Curso() {
	}

	public Curso(Integer id, boolean emergente, boolean nee) {
		this.id = id;
		this.emergente = emergente;
		this.nee = nee;
	}

	public Curso(Integer id, AplicacionXNivel aplicacionXNivel,
			Establecimiento establecimiento, String nombre, String codigo,
			boolean emergente, boolean nee, Integer cantidadAlumnos,
			List<Actividad> actividads) {
		this.id = id;
		this.aplicacionXNivel = aplicacionXNivel;
		this.establecimiento = establecimiento;
		this.nombre = nombre;
		this.codigo = codigo;
		this.emergente = emergente;
		this.nee = nee;
		this.cantidadAlumnos = cantidadAlumnos;
		this.actividads = actividads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AplicacionXNivel getAplicacionXNivel() {
		return this.aplicacionXNivel;
	}

	public void setAplicacionXNivel(AplicacionXNivel aplicacionXNivel) {
		this.aplicacionXNivel = aplicacionXNivel;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public boolean isEmergente() {
		return this.emergente;
	}

	public void setEmergente(boolean emergente) {
		this.emergente = emergente;
	}

	public boolean isNee() {
		return this.nee;
	}

	public void setNee(boolean nee) {
		this.nee = nee;
	}

	public Integer getCantidadAlumnos() {
		return this.cantidadAlumnos;
	}

	public void setCantidadAlumnos(Integer cantidadAlumnos) {
		this.cantidadAlumnos = cantidadAlumnos;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

}
