package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Curso generated by hbm2java
 */
public class Curso implements java.io.Serializable {

	private Integer id;
	private Nivel nivel;
	private Establecimiento establecimiento;
	private String nombre;
	private String codigo;
	private Boolean emergente;
	private Boolean nee;
	private List<Actividad> actividads = new ArrayList<Actividad>(0);

	public Curso() {
	}

	public Curso(Integer id) {
		this.id = id;
	}

	public Curso(Integer id, Nivel nivel, Establecimiento establecimiento,
			String nombre, String codigo, Boolean emergente, Boolean nee,
			List<Actividad> actividads) {
		this.id = id;
		this.nivel = nivel;
		this.establecimiento = establecimiento;
		this.nombre = nombre;
		this.codigo = codigo;
		this.emergente = emergente;
		this.nee = nee;
		this.actividads = actividads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Nivel getNivel() {
		return this.nivel;
	}

	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Boolean getEmergente() {
		return this.emergente;
	}

	public void setEmergente(Boolean emergente) {
		this.emergente = emergente;
	}

	public Boolean getNee() {
		return this.nee;
	}

	public void setNee(Boolean nee) {
		this.nee = nee;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

}
