package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoEstado generated by hbm2java
 */
public class DocumentoEstado implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set alumnoXActividadXDocumentos = new HashSet(0);
	private Set aplicacions = new HashSet(0);

	public DocumentoEstado() {
	}

	public DocumentoEstado(int id) {
		this.id = id;
	}

	public DocumentoEstado(int id, String nombre,
			Set alumnoXActividadXDocumentos, Set aplicacions) {
		this.id = id;
		this.nombre = nombre;
		this.alumnoXActividadXDocumentos = alumnoXActividadXDocumentos;
		this.aplicacions = aplicacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAlumnoXActividadXDocumentos() {
		return this.alumnoXActividadXDocumentos;
	}

	public void setAlumnoXActividadXDocumentos(Set alumnoXActividadXDocumentos) {
		this.alumnoXActividadXDocumentos = alumnoXActividadXDocumentos;
	}

	public Set getAplicacions() {
		return this.aplicacions;
	}

	public void setAplicacions(Set aplicacions) {
		this.aplicacions = aplicacions;
	}

}
