package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoTipo generated by hbm2java
 */
public class DocumentoTipo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set actividadXDocumentoTipos = new HashSet(0);
	private Set documentos = new HashSet(0);
	private Set aplicacions = new HashSet(0);

	public DocumentoTipo() {
	}

	public DocumentoTipo(int id) {
		this.id = id;
	}

	public DocumentoTipo(int id, String nombre, Set actividadXDocumentoTipos,
			Set documentos, Set aplicacions) {
		this.id = id;
		this.nombre = nombre;
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
		this.documentos = documentos;
		this.aplicacions = aplicacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadXDocumentoTipos() {
		return this.actividadXDocumentoTipos;
	}

	public void setActividadXDocumentoTipos(Set actividadXDocumentoTipos) {
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
	}

	public Set getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set documentos) {
		this.documentos = documentos;
	}

	public Set getAplicacions() {
		return this.aplicacions;
	}

	public void setAplicacions(Set aplicacions) {
		this.aplicacions = aplicacions;
	}

}
