package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * DocumentoTipo generated by hbm2java
 */
public class DocumentoTipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<ActividadXDocumentoTipo> actividadXDocumentoTipos = new ArrayList<ActividadXDocumentoTipo>(0);
	private List<Documento> documentos = new ArrayList<Documento>(0);
	private List<Aplicacion> aplicacions = new ArrayList<Aplicacion>(0);

	public DocumentoTipo() {
	}

	public DocumentoTipo(Integer id) {
		this.id = id;
	}

	public DocumentoTipo(Integer id, String nombre, List<ActividadXDocumentoTipo> actividadXDocumentoTipos,
			List<Documento> documentos, List<Aplicacion> aplicacions) {
		this.id = id;
		this.nombre = nombre;
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
		this.documentos = documentos;
		this.aplicacions = aplicacions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<ActividadXDocumentoTipo> getActividadXDocumentoTipos() {
		return this.actividadXDocumentoTipos;
	}

	public void setActividadXDocumentoTipos(List<ActividadXDocumentoTipo> actividadXDocumentoTipos) {
		this.actividadXDocumentoTipos = actividadXDocumentoTipos;
	}

	public List<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(List<Documento> documentos) {
		this.documentos = documentos;
	}

	public List<Aplicacion> getAplicacions() {
		return this.aplicacions;
	}

	public void setAplicacions(List<Aplicacion> aplicacions) {
		this.aplicacions = aplicacions;
	}

}
