package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Documento generated by hbm2java
 */
public class Documento implements java.io.Serializable {

	private Integer id;
	private DocumentoTipo documentoTipo;
	private Material material;
	private String codigo;
	private Boolean contingencia;
	private String rutaDocumento;
	private List<AlumnoXActividadXDocumento> alumnoXActividadXDocumentos = new ArrayList<AlumnoXActividadXDocumento>(0);
	private List<Actividad> actividads = new ArrayList<Actividad>(0);

	public Documento() {
	}

	public Documento(Integer id) {
		this.id = id;
	}

	public Documento(Integer id, DocumentoTipo documentoTipo, Material material,
			String codigo, Boolean contingencia, String rutaDocumento,
			List<AlumnoXActividadXDocumento> alumnoXActividadXDocumentos, List<Actividad> actividads) {
		this.id = id;
		this.documentoTipo = documentoTipo;
		this.material = material;
		this.codigo = codigo;
		this.contingencia = contingencia;
		this.rutaDocumento = rutaDocumento;
		this.alumnoXActividadXDocumentos = alumnoXActividadXDocumentos;
		this.actividads = actividads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public DocumentoTipo getDocumentoTipo() {
		return this.documentoTipo;
	}

	public void setDocumentoTipo(DocumentoTipo documentoTipo) {
		this.documentoTipo = documentoTipo;
	}

	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Boolean getContingencia() {
		return this.contingencia;
	}

	public void setContingencia(Boolean contingencia) {
		this.contingencia = contingencia;
	}

	public String getRutaDocumento() {
		return this.rutaDocumento;
	}

	public void setRutaDocumento(String rutaDocumento) {
		this.rutaDocumento = rutaDocumento;
	}

	public List<AlumnoXActividadXDocumento> getAlumnoXActividadXDocumentos() {
		return this.alumnoXActividadXDocumentos;
	}

	public void setAlumnoXActividadXDocumentos(List<AlumnoXActividadXDocumento> alumnoXActividadXDocumentos) {
		this.alumnoXActividadXDocumentos = alumnoXActividadXDocumentos;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

}
