package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Escala generated by hbm2java
 */
public class Escala implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set requisitos = new HashSet(0);
	private Set escalaItems = new HashSet(0);

	public Escala() {
	}

	public Escala(int id) {
		this.id = id;
	}

	public Escala(int id, String nombre, Set requisitos, Set escalaItems) {
		this.id = id;
		this.nombre = nombre;
		this.requisitos = requisitos;
		this.escalaItems = escalaItems;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getRequisitos() {
		return this.requisitos;
	}

	public void setRequisitos(Set requisitos) {
		this.requisitos = requisitos;
	}

	public Set getEscalaItems() {
		return this.escalaItems;
	}

	public void setEscalaItems(Set escalaItems) {
		this.escalaItems = escalaItems;
	}

}
