package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * EscalaItem generated by hbm2java
 */
public class EscalaItem implements java.io.Serializable {

	private int id;
	private Escala escala;
	private Integer valor;
	private String nombre;

	public EscalaItem() {
	}

	public EscalaItem(int id) {
		this.id = id;
	}

	public EscalaItem(int id, Escala escala, Integer valor, String nombre) {
		this.id = id;
		this.escala = escala;
		this.valor = valor;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Escala getEscala() {
		return this.escala;
	}

	public void setEscala(Escala escala) {
		this.escala = escala;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
