package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Escala generated by hbm2java
 */
public class Escala implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<Requisito> requisitos = new ArrayList<Requisito>(0);
	private List<EscalaItem> escalaItems = new ArrayList<EscalaItem>(0);

	public Escala() {
	}

	public Escala(Integer id) {
		this.id = id;
	}

	public Escala(Integer id, String nombre, List<Requisito> requisitos, List<EscalaItem> escalaItems) {
		this.id = id;
		this.nombre = nombre;
		this.requisitos = requisitos;
		this.escalaItems = escalaItems;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Requisito> getRequisitos() {
		return this.requisitos;
	}

	public void setRequisitos(List<Requisito> requisitos) {
		this.requisitos = requisitos;
	}

	public List<EscalaItem> getEscalaItems() {
		return this.escalaItems;
	}

	public void setEscalaItems(List<EscalaItem> escalaItems) {
		this.escalaItems = escalaItems;
	}

}
