package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento implements java.io.Serializable {

	private Integer id;
	private AreaGeografica areaGeografica;
	private Comuna comuna;
	private EstablecimientoRegimen establecimientoRegimen;
	private EstablecimientoEstado establecimientoEstado;
	private EstablecimientoDependencia establecimientoDependencia;
	private String nombre;
	private String telefono;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private String directorNombre;
	private String email;
	private List<UsuarioXEstablecimiento> usuarioXEstablecimientos = new ArrayList<UsuarioXEstablecimiento>(0);
	private List<CoXEstablecimiento> coXEstablecimientos = new ArrayList<CoXEstablecimiento>(0);
	private List<Curso> cursos = new ArrayList<Curso>(0);
	private List<AplicacionXEstablecimiento> aplicacionXEstablecimientos = new ArrayList<AplicacionXEstablecimiento>(0);
	private List<RutaXEstablecimiento> rutaXEstablecimientos = new ArrayList<RutaXEstablecimiento>(0);

	public Establecimiento() {
	}

	public Establecimiento(Integer id) {
		this.id = id;
	}

	public Establecimiento(Integer id, AreaGeografica areaGeografica,
			Comuna comuna, EstablecimientoRegimen establecimientoRegimen,
			EstablecimientoEstado establecimientoEstado,
			EstablecimientoDependencia establecimientoDependencia,
			String nombre, String telefono, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			String directorNombre, String email, List<UsuarioXEstablecimiento> usuarioXEstablecimientos,
			List<CoXEstablecimiento> coXEstablecimientos, List<Curso> cursos,
			List<AplicacionXEstablecimiento> aplicacionXEstablecimientos, List<RutaXEstablecimiento> rutaXEstablecimientos) {
		this.id = id;
		this.areaGeografica = areaGeografica;
		this.comuna = comuna;
		this.establecimientoRegimen = establecimientoRegimen;
		this.establecimientoEstado = establecimientoEstado;
		this.establecimientoDependencia = establecimientoDependencia;
		this.nombre = nombre;
		this.telefono = telefono;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.directorNombre = directorNombre;
		this.email = email;
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
		this.coXEstablecimientos = coXEstablecimientos;
		this.cursos = cursos;
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public AreaGeografica getAreaGeografica() {
		return this.areaGeografica;
	}

	public void setAreaGeografica(AreaGeografica areaGeografica) {
		this.areaGeografica = areaGeografica;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public EstablecimientoRegimen getEstablecimientoRegimen() {
		return this.establecimientoRegimen;
	}

	public void setEstablecimientoRegimen(
			EstablecimientoRegimen establecimientoRegimen) {
		this.establecimientoRegimen = establecimientoRegimen;
	}

	public EstablecimientoEstado getEstablecimientoEstado() {
		return this.establecimientoEstado;
	}

	public void setEstablecimientoEstado(
			EstablecimientoEstado establecimientoEstado) {
		this.establecimientoEstado = establecimientoEstado;
	}

	public EstablecimientoDependencia getEstablecimientoDependencia() {
		return this.establecimientoDependencia;
	}

	public void setEstablecimientoDependencia(
			EstablecimientoDependencia establecimientoDependencia) {
		this.establecimientoDependencia = establecimientoDependencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public String getDirectorNombre() {
		return this.directorNombre;
	}

	public void setDirectorNombre(String directorNombre) {
		this.directorNombre = directorNombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public List<UsuarioXEstablecimiento> getUsuarioXEstablecimientos() {
		return this.usuarioXEstablecimientos;
	}

	public void setUsuarioXEstablecimientos(List<UsuarioXEstablecimiento> usuarioXEstablecimientos) {
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public List<CoXEstablecimiento> getCoXEstablecimientos() {
		return this.coXEstablecimientos;
	}

	public void setCoXEstablecimientos(List<CoXEstablecimiento> coXEstablecimientos) {
		this.coXEstablecimientos = coXEstablecimientos;
	}

	public List<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}

	public List<AplicacionXEstablecimiento> getAplicacionXEstablecimientos() {
		return this.aplicacionXEstablecimientos;
	}

	public void setAplicacionXEstablecimientos(List<AplicacionXEstablecimiento> aplicacionXEstablecimientos) {
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
	}

	public List<RutaXEstablecimiento> getRutaXEstablecimientos() {
		return this.rutaXEstablecimientos;
	}

	public void setRutaXEstablecimientos(List<RutaXEstablecimiento> rutaXEstablecimientos) {
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

}
