package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.EstablecimientoDTO;

/**
 * Establecimiento generated by hbm2java
 */
public class Establecimiento implements java.io.Serializable {

	private int id;
	private AreaGeografica areaGeografica;
	private Comuna comuna;
	private EstablecimientoRegimen establecimientoRegimen;
	private EstablecimientoEstado establecimientoEstado;
	private EstablecimientoDependencia establecimientoDependencia;
	private String nombre;
	private String telefono;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private String directorNombre;
	private String email;
	private Set usuarioXEstablecimientos = new HashSet(0);
	private Set coXEstablecimientos = new HashSet(0);
	private Set cursos = new HashSet(0);
	private Set aplicacionXEstablecimientos = new HashSet(0);
	private Set rutaXEstablecimientos = new HashSet(0);

	public Establecimiento() {
	}

	public Establecimiento(int id) {
		this.id = id;
	}

	public Establecimiento(int id, AreaGeografica areaGeografica,
			Comuna comuna, EstablecimientoRegimen establecimientoRegimen,
			EstablecimientoEstado establecimientoEstado,
			EstablecimientoDependencia establecimientoDependencia,
			String nombre, String telefono, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			String directorNombre, String email, Set usuarioXEstablecimientos,
			Set coXEstablecimientos, Set cursos,
			Set aplicacionXEstablecimientos, Set rutaXEstablecimientos) {
		this.id = id;
		this.areaGeografica = areaGeografica;
		this.comuna = comuna;
		this.establecimientoRegimen = establecimientoRegimen;
		this.establecimientoEstado = establecimientoEstado;
		this.establecimientoDependencia = establecimientoDependencia;
		this.nombre = nombre;
		this.telefono = telefono;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.directorNombre = directorNombre;
		this.email = email;
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
		this.coXEstablecimientos = coXEstablecimientos;
		this.cursos = cursos;
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public AreaGeografica getAreaGeografica() {
		return this.areaGeografica;
	}

	public void setAreaGeografica(AreaGeografica areaGeografica) {
		this.areaGeografica = areaGeografica;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public EstablecimientoRegimen getEstablecimientoRegimen() {
		return this.establecimientoRegimen;
	}

	public void setEstablecimientoRegimen(
			EstablecimientoRegimen establecimientoRegimen) {
		this.establecimientoRegimen = establecimientoRegimen;
	}

	public EstablecimientoEstado getEstablecimientoEstado() {
		return this.establecimientoEstado;
	}

	public void setEstablecimientoEstado(
			EstablecimientoEstado establecimientoEstado) {
		this.establecimientoEstado = establecimientoEstado;
	}

	public EstablecimientoDependencia getEstablecimientoDependencia() {
		return this.establecimientoDependencia;
	}

	public void setEstablecimientoDependencia(
			EstablecimientoDependencia establecimientoDependencia) {
		this.establecimientoDependencia = establecimientoDependencia;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public String getDirectorNombre() {
		return this.directorNombre;
	}

	public void setDirectorNombre(String directorNombre) {
		this.directorNombre = directorNombre;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getUsuarioXEstablecimientos() {
		return this.usuarioXEstablecimientos;
	}

	public void setUsuarioXEstablecimientos(Set usuarioXEstablecimientos) {
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public Set getCoXEstablecimientos() {
		return this.coXEstablecimientos;
	}

	public void setCoXEstablecimientos(Set coXEstablecimientos) {
		this.coXEstablecimientos = coXEstablecimientos;
	}

	public Set getCursos() {
		return this.cursos;
	}

	public void setCursos(Set cursos) {
		this.cursos = cursos;
	}

	public Set getAplicacionXEstablecimientos() {
		return this.aplicacionXEstablecimientos;
	}

	public void setAplicacionXEstablecimientos(Set aplicacionXEstablecimientos) {
		this.aplicacionXEstablecimientos = aplicacionXEstablecimientos;
	}

	public Set getRutaXEstablecimientos() {
		return this.rutaXEstablecimientos;
	}

	public void setRutaXEstablecimientos(Set rutaXEstablecimientos) {
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

	public EstablecimientoDTO getEstablecimientoDTO() {
		EstablecimientoDTO edto = new EstablecimientoDTO();
		edto.setId(id);
		edto.setName(nombre);
		edto.setRbd(Integer.toString(id));
		return edto;
	}

}
