package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Fase generated by hbm2java
 */
public class Fase implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer orden;
	private String accion;
	private String descripcion;
	private Boolean permitirPaso;
	private Boolean final_;
	private Integer aplicacionId;
	private List<FaseXAplicacion> faseXAplicacions = new ArrayList<FaseXAplicacion>(0);

	public Fase() {
	}

	public Fase(Integer id) {
		this.id = id;
	}

	public Fase(Integer id, String nombre, Integer orden, String accion,
			String descripcion, Boolean permitirPaso, Boolean final_,
			Integer aplicacionId, List<FaseXAplicacion> faseXAplicacions) {
		this.id = id;
		this.nombre = nombre;
		this.orden = orden;
		this.accion = accion;
		this.descripcion = descripcion;
		this.permitirPaso = permitirPaso;
		this.final_ = final_;
		this.aplicacionId = aplicacionId;
		this.faseXAplicacions = faseXAplicacions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getPermitirPaso() {
		return this.permitirPaso;
	}

	public void setPermitirPaso(Boolean permitirPaso) {
		this.permitirPaso = permitirPaso;
	}

	public Boolean getFinal_() {
		return this.final_;
	}

	public void setFinal_(Boolean final_) {
		this.final_ = final_;
	}

	public Integer getAplicacionId() {
		return this.aplicacionId;
	}

	public void setAplicacionId(Integer aplicacionId) {
		this.aplicacionId = aplicacionId;
	}

	public List<FaseXAplicacion> getFaseXAplicacions() {
		return this.faseXAplicacions;
	}

	public void setFaseXAplicacions(List<FaseXAplicacion> faseXAplicacions) {
		this.faseXAplicacions = faseXAplicacions;
	}

}
