package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * FaseXAplicacion generated by hbm2java
 */
public class FaseXAplicacion implements java.io.Serializable {

	private Integer id;
	private Fase fase;
	private Aplicacion aplicacion;
	private Integer orden;
	private Date fechaResultado;
	private List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos = new ArrayList<FaseXAplicacionXTestXNivelXUsuarioTipo>(0);
	private List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions = new ArrayList<UsuarioXFaseXAplicacion>(0);

	public FaseXAplicacion() {
	}

	public FaseXAplicacion(Integer id) {
		this.id = id;
	}

	public FaseXAplicacion(Integer id, Fase fase, Aplicacion aplicacion,
			Integer orden, Date fechaResultado,
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos,
			List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions) {
		this.id = id;
		this.fase = fase;
		this.aplicacion = aplicacion;
		this.orden = orden;
		this.fechaResultado = fechaResultado;
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Fase getFase() {
		return this.fase;
	}

	public void setFase(Fase fase) {
		this.fase = fase;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Date getFechaResultado() {
		return this.fechaResultado;
	}

	public void setFechaResultado(Date fechaResultado) {
		this.fechaResultado = fechaResultado;
	}

	public List<FaseXAplicacionXTestXNivelXUsuarioTipo> getFaseXAplicacionXTestXNivelXUsuarioTipos() {
		return this.faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public void setFaseXAplicacionXTestXNivelXUsuarioTipos(
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos) {
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public List<UsuarioXFaseXAplicacion> getUsuarioXFaseXAplicacions() {
		return this.usuarioXFaseXAplicacions;
	}

	public void setUsuarioXFaseXAplicacions(List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions) {
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
	}

}
