package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Fase generated by hbm2java
 */
public class Fase implements java.io.Serializable {

	private int id;
	private String nombre;
	private Integer orden;
	private String accion;
	private String descripcion;
	private Boolean permitirPaso;
	private Boolean final_;
	private Set faseXAplicacions = new HashSet(0);

	public Fase() {
	}

	public Fase(int id) {
		this.id = id;
	}

	public Fase(int id, String nombre, Integer orden, String accion,
			String descripcion, Boolean permitirPaso, Boolean final_,
			Set faseXAplicacions) {
		this.id = id;
		this.nombre = nombre;
		this.orden = orden;
		this.accion = accion;
		this.descripcion = descripcion;
		this.permitirPaso = permitirPaso;
		this.final_ = final_;
		this.faseXAplicacions = faseXAplicacions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public String getAccion() {
		return this.accion;
	}

	public void setAccion(String accion) {
		this.accion = accion;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Boolean getPermitirPaso() {
		return this.permitirPaso;
	}

	public void setPermitirPaso(Boolean permitirPaso) {
		this.permitirPaso = permitirPaso;
	}

	public Boolean getFinal_() {
		return this.final_;
	}

	public void setFinal_(Boolean final_) {
		this.final_ = final_;
	}

	public Set getFaseXAplicacions() {
		return this.faseXAplicacions;
	}

	public void setFaseXAplicacions(Set faseXAplicacions) {
		this.faseXAplicacions = faseXAplicacions;
	}

}
