package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * FaseXAplicacionXTestXNivelXTipoUsuario generated by hbm2java
 */
public class FaseXAplicacionXTestXNivelXTipoUsuario implements
		java.io.Serializable {

	private Integer id;
	private Integer faseXAplicacionId;
	private Integer testId;
	private Integer nivelId;
	private Integer tipoUsuarioId;

	public FaseXAplicacionXTestXNivelXTipoUsuario() {
	}

	public FaseXAplicacionXTestXNivelXTipoUsuario(Integer id) {
		this.id = id;
	}

	public FaseXAplicacionXTestXNivelXTipoUsuario(Integer id,
			Integer faseXAplicacionId, Integer testId, Integer nivelId,
			Integer tipoUsuarioId) {
		this.id = id;
		this.faseXAplicacionId = faseXAplicacionId;
		this.testId = testId;
		this.nivelId = nivelId;
		this.tipoUsuarioId = tipoUsuarioId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getFaseXAplicacionId() {
		return this.faseXAplicacionId;
	}

	public void setFaseXAplicacionId(Integer faseXAplicacionId) {
		this.faseXAplicacionId = faseXAplicacionId;
	}

	public Integer getTestId() {
		return this.testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	public Integer getNivelId() {
		return this.nivelId;
	}

	public void setNivelId(Integer nivelId) {
		this.nivelId = nivelId;
	}

	public Integer getTipoUsuarioId() {
		return this.tipoUsuarioId;
	}

	public void setTipoUsuarioId(Integer tipoUsuarioId) {
		this.tipoUsuarioId = tipoUsuarioId;
	}

}
