package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * GuiaDespacho generated by hbm2java
 */
public class GuiaDespacho implements java.io.Serializable {

	private int id;
	private String codigo;
	private Date fecha;
	private String ruta;
	private Set materialXGuiaDespachos = new HashSet(0);

	public GuiaDespacho() {
	}

	public GuiaDespacho(int id) {
		this.id = id;
	}

	public GuiaDespacho(int id, String codigo, Date fecha, String ruta,
			Set materialXGuiaDespachos) {
		this.id = id;
		this.codigo = codigo;
		this.fecha = fecha;
		this.ruta = ruta;
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	public Set getMaterialXGuiaDespachos() {
		return this.materialXGuiaDespachos;
	}

	public void setMaterialXGuiaDespachos(Set materialXGuiaDespachos) {
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

}
