package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * IncidenciaTipo generated by hbm2java
 */
public class IncidenciaTipo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set motivoFallas = new HashSet(0);

	public IncidenciaTipo() {
	}

	public IncidenciaTipo(int id) {
		this.id = id;
	}

	public IncidenciaTipo(int id, String nombre, Set motivoFallas) {
		this.id = id;
		this.nombre = nombre;
		this.motivoFallas = motivoFallas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMotivoFallas() {
		return this.motivoFallas;
	}

	public void setMotivoFallas(Set motivoFallas) {
		this.motivoFallas = motivoFallas;
	}

}
