package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * InstitucionTipo generated by hbm2java
 */
public class InstitucionTipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<Universidad> universidads = new ArrayList<Universidad>(0);

	public InstitucionTipo() {
	}

	public InstitucionTipo(Integer id) {
		this.id = id;
	}

	public InstitucionTipo(Integer id, String nombre, List<Universidad> universidads) {
		this.id = id;
		this.nombre = nombre;
		this.universidads = universidads;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Universidad> getUniversidads() {
		return this.universidads;
	}

	public void setUniversidads(List<Universidad> universidads) {
		this.universidads = universidads;
	}

}
