package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JoXCo generated by hbm2java
 */
public class JoXCo implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Co co;
	private Date fechaActivacion;
	private Date fechaTermino;
	private Boolean activo;

	public JoXCo() {
	}

	public JoXCo(int id) {
		this.id = id;
	}

	public JoXCo(int id, Usuario usuario, Co co, Date fechaActivacion,
			Date fechaTermino, Boolean activo) {
		this.id = id;
		this.usuario = usuario;
		this.co = co;
		this.fechaActivacion = fechaActivacion;
		this.fechaTermino = fechaTermino;
		this.activo = activo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public Date getFechaActivacion() {
		return this.fechaActivacion;
	}

	public void setFechaActivacion(Date fechaActivacion) {
		this.fechaActivacion = fechaActivacion;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
