package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * JoXCoId generated by hbm2java
 */
public class JoXCoId implements java.io.Serializable {

	private Integer joId;
	private Integer coId;

	public JoXCoId() {
	}

	public JoXCoId(Integer joId, Integer coId) {
		this.joId = joId;
		this.coId = coId;
	}

	public Integer getJoId() {
		return this.joId;
	}

	public void setJoId(Integer joId) {
		this.joId = joId;
	}

	public Integer getCoId() {
		return this.coId;
	}

	public void setCoId(Integer coId) {
		this.coId = coId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JoXCoId))
			return false;
		JoXCoId castOther = (JoXCoId) other;

		return (this.getJoId() == castOther.getJoId())
				&& (this.getCoId() == castOther.getCoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getJoId();
		result = 37 * result + this.getCoId();
		return result;
	}

}
