package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JrXCentroRegional generated by hbm2java
 */
public class JrXCentroRegional implements java.io.Serializable {

	private JrXCentroRegionalId id;
	private Usuario usuario;
	private CentroRegional centroRegional;
	private Date fechaActivacion;
	private Date fechaTermino;
	private Boolean activo;

	public JrXCentroRegional() {
	}

	public JrXCentroRegional(JrXCentroRegionalId id, Usuario usuario,
			CentroRegional centroRegional) {
		this.id = id;
		this.usuario = usuario;
		this.centroRegional = centroRegional;
	}

	public JrXCentroRegional(JrXCentroRegionalId id, Usuario usuario,
			CentroRegional centroRegional, Date fechaActivacion,
			Date fechaTermino, Boolean activo) {
		this.id = id;
		this.usuario = usuario;
		this.centroRegional = centroRegional;
		this.fechaActivacion = fechaActivacion;
		this.fechaTermino = fechaTermino;
		this.activo = activo;
	}

	public JrXCentroRegionalId getId() {
		return this.id;
	}

	public void setId(JrXCentroRegionalId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public CentroRegional getCentroRegional() {
		return this.centroRegional;
	}

	public void setCentroRegional(CentroRegional centroRegional) {
		this.centroRegional = centroRegional;
	}

	public Date getFechaActivacion() {
		return this.fechaActivacion;
	}

	public void setFechaActivacion(Date fechaActivacion) {
		this.fechaActivacion = fechaActivacion;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
