package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * JzXZonaId generated by hbm2java
 */
public class JzXZonaId implements java.io.Serializable {

	private Integer jzId;
	private Integer zonaId;

	public JzXZonaId() {
	}

	public JzXZonaId(Integer jzId, Integer zonaId) {
		this.jzId = jzId;
		this.zonaId = zonaId;
	}

	public Integer getJzId() {
		return this.jzId;
	}

	public void setJzId(Integer jzId) {
		this.jzId = jzId;
	}

	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JzXZonaId))
			return false;
		JzXZonaId castOther = (JzXZonaId) other;

		return (this.getJzId() == castOther.getJzId())
				&& (this.getZonaId() == castOther.getZonaId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getJzId();
		result = 37 * result + this.getZonaId();
		return result;
	}

}
