package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * JzXZona generated by hbm2java
 */
public class JzXZona implements java.io.Serializable {

	private Integer id;
	private Zona zona;
	private Usuario usuario;
	private Date fechaActivacion;
	private Date fechaTermino;
	private Boolean activo;

	public JzXZona() {
	}

	public JzXZona(Integer id) {
		this.id = id;
	}

	public JzXZona(Integer id, Zona zona, Usuario usuario, Date fechaActivacion,
			Date fechaTermino, Boolean activo) {
		this.id = id;
		this.zona = zona;
		this.usuario = usuario;
		this.fechaActivacion = fechaActivacion;
		this.fechaTermino = fechaTermino;
		this.activo = activo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFechaActivacion() {
		return this.fechaActivacion;
	}

	public void setFechaActivacion(Date fechaActivacion) {
		this.fechaActivacion = fechaActivacion;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

}
