package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Lote generated by hbm2java
 */
public class Lote implements java.io.Serializable {

	private Integer id;
	private Date fechaCreacion;
	private String nombre;
	private String comentario;
	private List<Material> materials = new ArrayList<Material>(0);

	public Lote() {
	}

	public Lote(Integer id) {
		this.id = id;
	}

	public Lote(Integer id, Date fechaCreacion, String nombre, String comentario,
			List<Material> materials) {
		this.id = id;
		this.fechaCreacion = fechaCreacion;
		this.nombre = nombre;
		this.comentario = comentario;
		this.materials = materials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public List<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(List<Material> materials) {
		this.materials = materials;
	}

}
