package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Lugar generated by hbm2java
 */
public class Lugar implements java.io.Serializable {

	private int id;
	private Aplicacion aplicacion;
	private String nombre;
	private Set materialHistorialsForDestinoId = new HashSet(0);
	private Set materialHistorialsForOrigenId = new HashSet(0);

	public Lugar() {
	}

	public Lugar(int id) {
		this.id = id;
	}

	public Lugar(int id, Aplicacion aplicacion, String nombre,
			Set materialHistorialsForDestinoId,
			Set materialHistorialsForOrigenId) {
		this.id = id;
		this.aplicacion = aplicacion;
		this.nombre = nombre;
		this.materialHistorialsForDestinoId = materialHistorialsForDestinoId;
		this.materialHistorialsForOrigenId = materialHistorialsForOrigenId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Aplicacion getAplicacion() {
		return this.aplicacion;
	}

	public void setAplicacion(Aplicacion aplicacion) {
		this.aplicacion = aplicacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMaterialHistorialsForDestinoId() {
		return this.materialHistorialsForDestinoId;
	}

	public void setMaterialHistorialsForDestinoId(
			Set materialHistorialsForDestinoId) {
		this.materialHistorialsForDestinoId = materialHistorialsForDestinoId;
	}

	public Set getMaterialHistorialsForOrigenId() {
		return this.materialHistorialsForOrigenId;
	}

	public void setMaterialHistorialsForOrigenId(
			Set materialHistorialsForOrigenId) {
		this.materialHistorialsForOrigenId = materialHistorialsForOrigenId;
	}

}
