package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Lugar generated by hbm2java
 */
public class Lugar implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List materialHistorialsForDestinoId = new ArrayList(0);
	private List materialHistorialsForOrigenId = new ArrayList(0);

	public Lugar() {
	}

	public Lugar(Integer id) {
		this.id = id;
	}

	public Lugar(Integer id, String nombre, List materialHistorialsForDestinoId,
			List materialHistorialsForOrigenId) {
		this.id = id;
		this.nombre = nombre;
		this.materialHistorialsForDestinoId = materialHistorialsForDestinoId;
		this.materialHistorialsForOrigenId = materialHistorialsForOrigenId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List getMaterialHistorialsForDestinoId() {
		return this.materialHistorialsForDestinoId;
	}

	public void setMaterialHistorialsForDestinoId(
			List materialHistorialsForDestinoId) {
		this.materialHistorialsForDestinoId = materialHistorialsForDestinoId;
	}

	public List getMaterialHistorialsForOrigenId() {
		return this.materialHistorialsForOrigenId;
	}

	public void setMaterialHistorialsForOrigenId(
			List materialHistorialsForOrigenId) {
		this.materialHistorialsForOrigenId = materialHistorialsForOrigenId;
	}

}
