package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	private Integer id;
	private Co co;
	private MaterialTipo materialTipo;
	private String codigo;
	private List<Cc> ccs = new ArrayList<Cc>(0);
	private List<Lote> lotes = new ArrayList<Lote>(0);
	private List<Actividad> actividads = new ArrayList<Actividad>(0);
	private List<Documento> documentos = new ArrayList<Documento>(0);
	private List<MaterialHistorial> materialHistorials = new ArrayList<MaterialHistorial>(0);
	private List<MaterialXGuiaDespacho> materialXGuiaDespachos = new ArrayList<MaterialXGuiaDespacho>(0);

	public Material() {
	}

	public Material(Integer id) {
		this.id = id;
	}

	public Material(Integer id, Co co, MaterialTipo materialTipo, String codigo,
			List<Cc> ccs, List<Lote> lotes, List<Actividad> actividads, List<Documento> documentos,
			List<MaterialHistorial> materialHistorials, List<MaterialXGuiaDespacho> materialXGuiaDespachos) {
		this.id = id;
		this.co = co;
		this.materialTipo = materialTipo;
		this.codigo = codigo;
		this.ccs = ccs;
		this.lotes = lotes;
		this.actividads = actividads;
		this.documentos = documentos;
		this.materialHistorials = materialHistorials;
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public MaterialTipo getMaterialTipo() {
		return this.materialTipo;
	}

	public void setMaterialTipo(MaterialTipo materialTipo) {
		this.materialTipo = materialTipo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public List<Cc> getCcs() {
		return this.ccs;
	}

	public void setCcs(List<Cc> ccs) {
		this.ccs = ccs;
	}

	public List<Lote> getLotes() {
		return this.lotes;
	}

	public void setLotes(List<Lote> lotes) {
		this.lotes = lotes;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

	public List<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(List<Documento> documentos) {
		this.documentos = documentos;
	}

	public List<MaterialHistorial> getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(List<MaterialHistorial> materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public List<MaterialXGuiaDespacho> getMaterialXGuiaDespachos() {
		return this.materialXGuiaDespachos;
	}

	public void setMaterialXGuiaDespachos(List<MaterialXGuiaDespacho> materialXGuiaDespachos) {
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

}
