package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * MaterialHistorial generated by hbm2java
 */
public class MaterialHistorial implements java.io.Serializable {

	private MaterialHistorialId id;
	private Lugar lugarByDestinoId;
	private Usuario usuario;
	private Lugar lugarByOrigenId;
	private Actividad actividad;
	private Material material;
	private Co co;
	private MaterialEstado materialEstado;
	private Integer modificadorId;

	public MaterialHistorial() {
	}

	public MaterialHistorial(MaterialHistorialId id, Material material) {
		this.id = id;
		this.material = material;
	}

	public MaterialHistorial(MaterialHistorialId id, Lugar lugarByDestinoId,
			Usuario usuario, Lugar lugarByOrigenId, Actividad actividad,
			Material material, Co co, MaterialEstado materialEstado,
			Integer modificadorId) {
		this.id = id;
		this.lugarByDestinoId = lugarByDestinoId;
		this.usuario = usuario;
		this.lugarByOrigenId = lugarByOrigenId;
		this.actividad = actividad;
		this.material = material;
		this.co = co;
		this.materialEstado = materialEstado;
		this.modificadorId = modificadorId;
	}

	public MaterialHistorialId getId() {
		return this.id;
	}

	public void setId(MaterialHistorialId id) {
		this.id = id;
	}

	public Lugar getLugarByDestinoId() {
		return this.lugarByDestinoId;
	}

	public void setLugarByDestinoId(Lugar lugarByDestinoId) {
		this.lugarByDestinoId = lugarByDestinoId;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Lugar getLugarByOrigenId() {
		return this.lugarByOrigenId;
	}

	public void setLugarByOrigenId(Lugar lugarByOrigenId) {
		this.lugarByOrigenId = lugarByOrigenId;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public Material getMaterial() {
		return this.material;
	}

	public void setMaterial(Material material) {
		this.material = material;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public MaterialEstado getMaterialEstado() {
		return this.materialEstado;
	}

	public void setMaterialEstado(MaterialEstado materialEstado) {
		this.materialEstado = materialEstado;
	}

	public Integer getModificadorId() {
		return this.modificadorId;
	}

	public void setModificadorId(Integer modificadorId) {
		this.modificadorId = modificadorId;
	}

}
