package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * MaterialEstado generated by hbm2java
 */
public class MaterialEstado implements java.io.Serializable {

	public static final String EN_CAMINO = "En Camino";
	public static final String EN_EL_LUGAR = "En el Lugar";
	public static final String MARCADO_PARA_SALIR = "Marcado para Salir";
	public static final String DESAPARECIDA = "Desaparecida";

	private Integer id;
	private String nombre;
	private List<MaterialHistorial> materialHistorials = new ArrayList<MaterialHistorial>(
			0);

	public MaterialEstado() {
	}

	public MaterialEstado(Integer id) {
		this.id = id;
	}

	public MaterialEstado(Integer id, String nombre,
			List<MaterialHistorial> materialHistorials) {
		this.id = id;
		this.nombre = nombre;
		this.materialHistorials = materialHistorials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<MaterialHistorial> getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(List<MaterialHistorial> materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

}
