package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * MaterialTipo generated by hbm2java
 */
public class MaterialTipo implements java.io.Serializable {
	
	public static final String CAJA_CURSO_DIA = "Caja Curso-Día";
	public static final String COMPLEMENTARIO = "Complementario";
//	public static final String CONTINGENCIA = "Contingencia";
	public static final String CAPACITACION = "Capacitación";
	public static final String PENDRIVE = "Pendrive";
	public static final String NEE = "NEE";

	private Integer id;
	private String nombre;
	private List<Material> materials = new ArrayList<Material>(0);

	public MaterialTipo() {
	}

	public MaterialTipo(Integer id) {
		this.id = id;
	}

	public MaterialTipo(Integer id, String nombre, List<Material> materials) {
		this.id = id;
		this.nombre = nombre;
		this.materials = materials;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Material> getMaterials() {
		return this.materials;
	}

	public void setMaterials(List<Material> materials) {
		this.materials = materials;
	}

}
