package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Material generated by hbm2java
 */
public class Material implements java.io.Serializable {

	private int id;
	private Co co;
	private MaterialTipo materialTipo;
	private String codigo;
	private Set ccs = new HashSet(0);
	private Set actividads = new HashSet(0);
	private Set documentos = new HashSet(0);
	private Set materialHistorials = new HashSet(0);
	private Set materialXGuiaDespachos = new HashSet(0);

	public Material() {
	}

	public Material(int id) {
		this.id = id;
	}

	public Material(int id, Co co, MaterialTipo materialTipo, String codigo,
			Set ccs, Set actividads, Set documentos, Set materialHistorials,
			Set materialXGuiaDespachos) {
		this.id = id;
		this.co = co;
		this.materialTipo = materialTipo;
		this.codigo = codigo;
		this.ccs = ccs;
		this.actividads = actividads;
		this.documentos = documentos;
		this.materialHistorials = materialHistorials;
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public MaterialTipo getMaterialTipo() {
		return this.materialTipo;
	}

	public void setMaterialTipo(MaterialTipo materialTipo) {
		this.materialTipo = materialTipo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getCcs() {
		return this.ccs;
	}

	public void setCcs(Set ccs) {
		this.ccs = ccs;
	}

	public Set getActividads() {
		return this.actividads;
	}

	public void setActividads(Set actividads) {
		this.actividads = actividads;
	}

	public Set getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set documentos) {
		this.documentos = documentos;
	}

	public Set getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(Set materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public Set getMaterialXGuiaDespachos() {
		return this.materialXGuiaDespachos;
	}

	public void setMaterialXGuiaDespachos(Set materialXGuiaDespachos) {
		this.materialXGuiaDespachos = materialXGuiaDespachos;
	}

}
