package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MaterialHistorialId generated by hbm2java
 */
public class MaterialHistorialId implements java.io.Serializable {

	private int materialId;
	private Date fecha;

	public MaterialHistorialId() {
	}

	public MaterialHistorialId(int materialId, Date fecha) {
		this.materialId = materialId;
		this.fecha = fecha;
	}

	public int getMaterialId() {
		return this.materialId;
	}

	public void setMaterialId(int materialId) {
		this.materialId = materialId;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MaterialHistorialId))
			return false;
		MaterialHistorialId castOther = (MaterialHistorialId) other;

		return (this.getMaterialId() == castOther.getMaterialId())
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null && castOther.getFecha() != null && this
						.getFecha().equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaterialId();
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
