package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MaterialTipo generated by hbm2java
 */
public class MaterialTipo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set materials = new HashSet(0);

	public MaterialTipo() {
	}

	public MaterialTipo(int id) {
		this.id = id;
	}

	public MaterialTipo(int id, String nombre, Set materials) {
		this.id = id;
		this.nombre = nombre;
		this.materials = materials;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getMaterials() {
		return this.materials;
	}

	public void setMaterials(Set materials) {
		this.materials = materials;
	}

}
