package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private MensajeTipo mensajeTipo;
	private Date fecha;
	private String mensaje;

	public Mensaje() {
	}

	public Mensaje(Integer id) {
		this.id = id;
	}

	public Mensaje(Integer id, Usuario usuario, MensajeTipo mensajeTipo,
			Date fecha, String mensaje) {
		this.id = id;
		this.usuario = usuario;
		this.mensajeTipo = mensajeTipo;
		this.fecha = fecha;
		this.mensaje = mensaje;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public MensajeTipo getMensajeTipo() {
		return this.mensajeTipo;
	}

	public void setMensajeTipo(MensajeTipo mensajeTipo) {
		this.mensajeTipo = mensajeTipo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}

}
