package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * MotivoFalla generated by hbm2java
 */
public class MotivoFalla implements java.io.Serializable {

	private int id;
	private IncidenciaTipo incidenciaTipo;
	private String nombre;
	private Set actividadXIncidencias = new HashSet(0);

	public MotivoFalla() {
	}

	public MotivoFalla(int id) {
		this.id = id;
	}

	public MotivoFalla(int id, IncidenciaTipo incidenciaTipo, String nombre,
			Set actividadXIncidencias) {
		this.id = id;
		this.incidenciaTipo = incidenciaTipo;
		this.nombre = nombre;
		this.actividadXIncidencias = actividadXIncidencias;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public IncidenciaTipo getIncidenciaTipo() {
		return this.incidenciaTipo;
	}

	public void setIncidenciaTipo(IncidenciaTipo incidenciaTipo) {
		this.incidenciaTipo = incidenciaTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getActividadXIncidencias() {
		return this.actividadXIncidencias;
	}

	public void setActividadXIncidencias(Set actividadXIncidencias) {
		this.actividadXIncidencias = actividadXIncidencias;
	}

}
