package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.NivelDTO;

/**
 * Nivel generated by hbm2java
 */
public class Nivel implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set aplicacionXNivels = new HashSet(0);
	private Set usuarios = new HashSet(0);
	private Set faseXAplicacionXTestXNivelXTipoUsuarios = new HashSet(0);
	private Set cursos = new HashSet(0);

	public Nivel() {
	}

	public Nivel(int id) {
		this.id = id;
	}

	public Nivel(int id, String nombre, Set aplicacionXNivels, Set usuarios,
			Set faseXAplicacionXTestXNivelXTipoUsuarios, Set cursos) {
		this.id = id;
		this.nombre = nombre;
		this.aplicacionXNivels = aplicacionXNivels;
		this.usuarios = usuarios;
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
		this.cursos = cursos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getAplicacionXNivels() {
		return this.aplicacionXNivels;
	}

	public void setAplicacionXNivels(Set aplicacionXNivels) {
		this.aplicacionXNivels = aplicacionXNivels;
	}

	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

	public Set getFaseXAplicacionXTestXNivelXTipoUsuarios() {
		return this.faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public void setFaseXAplicacionXTestXNivelXTipoUsuarios(
			Set faseXAplicacionXTestXNivelXTipoUsuarios) {
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public Set getCursos() {
		return this.cursos;
	}

	public void setCursos(Set cursos) {
		this.cursos = cursos;
	}

	public NivelDTO getNivelDTO() {
		NivelDTO ndto = new NivelDTO();
		ndto.setId(id);
		ndto.setNombre(nombre);
		return ndto;
	}

}
