package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Nivel generated by hbm2java
 */
public class Nivel implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<AplicacionXNivel> aplicacionXNivels = new ArrayList<AplicacionXNivel>(0);
	private List<Usuario> usuarios = new ArrayList<Usuario>(0);
	private List<FaseXAplicacionXTestXNivelXTipoUsuario> faseXAplicacionXTestXNivelXTipoUsuarios = new ArrayList<FaseXAplicacionXTestXNivelXTipoUsuario>(0);
	private List<Curso> cursos = new ArrayList<Curso>(0);

	public Nivel() {
	}

	public Nivel(Integer id) {
		this.id = id;
	}

	public Nivel(Integer id, String nombre, List<AplicacionXNivel> aplicacionXNivels, List<Usuario> usuarios,
			List<FaseXAplicacionXTestXNivelXTipoUsuario> faseXAplicacionXTestXNivelXTipoUsuarios, List<Curso> cursos) {
		this.id = id;
		this.nombre = nombre;
		this.aplicacionXNivels = aplicacionXNivels;
		this.usuarios = usuarios;
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
		this.cursos = cursos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<AplicacionXNivel> getAplicacionXNivels() {
		return this.aplicacionXNivels;
	}

	public void setAplicacionXNivels(List<AplicacionXNivel> aplicacionXNivels) {
		this.aplicacionXNivels = aplicacionXNivels;
	}

	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public List<FaseXAplicacionXTestXNivelXTipoUsuario> getFaseXAplicacionXTestXNivelXTipoUsuarios() {
		return this.faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public void setFaseXAplicacionXTestXNivelXTipoUsuarios(
			List<FaseXAplicacionXTestXNivelXTipoUsuario> faseXAplicacionXTestXNivelXTipoUsuarios) {
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public List<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}

}
