package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.NivelDTO;

/**
 * Nivel generated by hbm2java
 */
public class Nivel implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos = new ArrayList<FaseXAplicacionXTestXNivelXUsuarioTipo>(0);
	private List<AplicacionXNivel> aplicacionXNivels = new ArrayList<AplicacionXNivel>(0);
	private List<Usuario> usuarios = new ArrayList<Usuario>(0);
	private List<Curso> cursos = new ArrayList<Curso>(0);

	public Nivel() {
	}

	public Nivel(Integer id) {
		this.id = id;
	}

	public Nivel(Integer id, String nombre,
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos, List<AplicacionXNivel> aplicacionXNivels,
			List<Usuario> usuarios, List<Curso> cursos) {
		this.id = id;
		this.nombre = nombre;
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
		this.aplicacionXNivels = aplicacionXNivels;
		this.usuarios = usuarios;
		this.cursos = cursos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<FaseXAplicacionXTestXNivelXUsuarioTipo> getFaseXAplicacionXTestXNivelXUsuarioTipos() {
		return this.faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public void setFaseXAplicacionXTestXNivelXUsuarioTipos(
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos) {
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public List<AplicacionXNivel> getAplicacionXNivels() {
		return this.aplicacionXNivels;
	}

	public void setAplicacionXNivels(List<AplicacionXNivel> aplicacionXNivels) {
		this.aplicacionXNivels = aplicacionXNivels;
	}

	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	public List<Curso> getCursos() {
		return this.cursos;
	}

	public void setCursos(List<Curso> cursos) {
		this.cursos = cursos;
	}

	public NivelDTO getNivelDTO() {
		NivelDTO ndto = new NivelDTO();
		ndto.setId(id);
		ndto.setNombre(nombre);
		return ndto;
	}
}
