package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.SectorDTO;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private int id;
	private Region region;
	private String nombre;
	private Set comunas = new HashSet(0);

	public Provincia() {
	}

	public Provincia(int id) {
		this.id = id;
	}

	public Provincia(int id, Region region, String nombre, Set comunas) {
		this.id = id;
		this.region = region;
		this.nombre = nombre;
		this.comunas = comunas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getComunas() {
		return this.comunas;
	}

	public void setComunas(Set comunas) {
		this.comunas = comunas;
	}

	public SectorDTO getSectorDTO() {
		SectorDTO sdto = new SectorDTO();
		sdto.setIdSector(id);
		sdto.setSector(nombre);
		sdto.setTipoSector(SectorDTO.TIPO_PROVINCIA);
		return sdto;
	}

}
