package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.SectorDTO;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private Integer id;
	private Region region;
	private String nombre;
	private List<Comuna> comunas = new ArrayList<Comuna>(0);

	public Provincia() {
	}

	public Provincia(Integer id) {
		this.id = id;
	}

	public Provincia(Integer id, Region region, String nombre, List<Comuna> comunas) {
		this.id = id;
		this.region = region;
		this.nombre = nombre;
		this.comunas = comunas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Comuna> getComunas() {
		return this.comunas;
	}

	public void setComunas(List<Comuna> comunas) {
		this.comunas = comunas;
	}

	public SectorDTO getSectorDTO() {
		SectorDTO sdto = new SectorDTO();
		sdto.setIdSector(id);
		sdto.setSector(nombre);
		sdto.setTipoSector(SectorDTO.TIPO_PROVINCIA);
		return sdto;
	}

}
