package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.SectorDTO;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<Provincia> provincias = new ArrayList<Provincia>(0);

	public Region() {
	}

	public Region(Integer id) {
		this.id = id;
	}

	public Region(Integer id, String nombre, List<Provincia> provincias) {
		this.id = id;
		this.nombre = nombre;
		this.provincias = provincias;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<Provincia> getProvincias() {
		return this.provincias;
	}

	public void setProvincias(List<Provincia> provincias) {
		this.provincias = provincias;
	}

	public SectorDTO getSectorDTO() {
		SectorDTO sdto = new SectorDTO();
		sdto.setIdSector(id);
		sdto.setSector(nombre);
		sdto.setTipoSector(SectorDTO.TIPO_REGION);
		return sdto;
	}

}
