package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * RequisitoXAplicacionXUsuarioTipo generated by hbm2java
 */
public class RequisitoXAplicacionXUsuarioTipo implements java.io.Serializable {

	private Integer id;
	private Requisito requisito;
	private AplicacionXUsuarioTipo aplicacionXUsuarioTipo;
	private Integer parametro;
	private boolean obligatorio;
	private Boolean ordenAprobacion;
	private BigDecimal factor;
	private List requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId = new ArrayList(
			0);
	private List requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId = new ArrayList(
			0);

	public RequisitoXAplicacionXUsuarioTipo() {
	}

	public RequisitoXAplicacionXUsuarioTipo(Integer id, boolean obligatorio) {
		this.id = id;
		this.obligatorio = obligatorio;
	}

	public RequisitoXAplicacionXUsuarioTipo(Integer id, Requisito requisito,
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo, Integer parametro,
			boolean obligatorio, Boolean ordenAprobacion, BigDecimal factor,
			List requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId,
			List requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId) {
		this.id = id;
		this.requisito = requisito;
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
		this.parametro = parametro;
		this.obligatorio = obligatorio;
		this.ordenAprobacion = ordenAprobacion;
		this.factor = factor;
		this.requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId = requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId;
		this.requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId = requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	public AplicacionXUsuarioTipo getAplicacionXUsuarioTipo() {
		return this.aplicacionXUsuarioTipo;
	}

	public void setAplicacionXUsuarioTipo(
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo) {
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
	}

	public Integer getParametro() {
		return this.parametro;
	}

	public void setParametro(Integer parametro) {
		this.parametro = parametro;
	}

	public boolean isObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	public Boolean getOrdenAprobacion() {
		return this.ordenAprobacion;
	}

	public void setOrdenAprobacion(Boolean ordenAprobacion) {
		this.ordenAprobacion = ordenAprobacion;
	}

	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

	public List getRequisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId() {
		return this.requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId;
	}

	public void setRequisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId(
			List requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId) {
		this.requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId = requisitoXAplicacionXUsuarioTiposForRequisitoAlternativoId;
	}

	public List getRequisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId() {
		return this.requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

	public void setRequisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId(
			List requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId) {
		this.requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId = requisitoXAplicacionXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

}
