package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * RequisitoXUsuarioTipo generated by hbm2java
 */
public class RequisitoXUsuarioTipo implements java.io.Serializable {

	private Integer id;
	private Integer requisitoId;
	private Integer aplicacionXUsuarioTipoId;
	private Integer parametro;
	private Boolean obligatorio;
	private Boolean ordenAprobacion;
	private BigDecimal factor;

	public RequisitoXUsuarioTipo() {
	}

	public RequisitoXUsuarioTipo(Integer id) {
		this.id = id;
	}

	public RequisitoXUsuarioTipo(Integer id, Integer requisitoId,
			Integer aplicacionXUsuarioTipoId, Integer parametro,
			Boolean obligatorio, Boolean ordenAprobacion, BigDecimal factor) {
		this.id = id;
		this.requisitoId = requisitoId;
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
		this.parametro = parametro;
		this.obligatorio = obligatorio;
		this.ordenAprobacion = ordenAprobacion;
		this.factor = factor;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getRequisitoId() {
		return this.requisitoId;
	}

	public void setRequisitoId(Integer requisitoId) {
		this.requisitoId = requisitoId;
	}

	public Integer getAplicacionXUsuarioTipoId() {
		return this.aplicacionXUsuarioTipoId;
	}

	public void setAplicacionXUsuarioTipoId(Integer aplicacionXUsuarioTipoId) {
		this.aplicacionXUsuarioTipoId = aplicacionXUsuarioTipoId;
	}

	public Integer getParametro() {
		return this.parametro;
	}

	public void setParametro(Integer parametro) {
		this.parametro = parametro;
	}

	public Boolean getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	public Boolean getOrdenAprobacion() {
		return this.ordenAprobacion;
	}

	public void setOrdenAprobacion(Boolean ordenAprobacion) {
		this.ordenAprobacion = ordenAprobacion;
	}

	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

}
