package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * RequisitoXUsuarioTipo generated by hbm2java
 */
public class RequisitoXUsuarioTipo implements java.io.Serializable {

	private Integer id;
	private Requisito requisito;
	private AplicacionXUsuarioTipo aplicacionXUsuarioTipo;
	private Integer parametro;
	private Boolean obligatorio;
	private Boolean ordenAprobacion;
	private BigDecimal factor;
	private List requisitoXUsuarioTiposForRequisitoAlternativoId = new ArrayList(0);
	private List requisitoXUsuarioTiposForRequisitoXUsuarioTipoId = new ArrayList(
			0);

	public RequisitoXUsuarioTipo() {
	}

	public RequisitoXUsuarioTipo(Integer id) {
		this.id = id;
	}

	public RequisitoXUsuarioTipo(Integer id, Requisito requisito,
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo, Integer parametro,
			Boolean obligatorio, Boolean ordenAprobacion, BigDecimal factor,
			List requisitoXUsuarioTiposForRequisitoAlternativoId,
			List requisitoXUsuarioTiposForRequisitoXUsuarioTipoId) {
		this.id = id;
		this.requisito = requisito;
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
		this.parametro = parametro;
		this.obligatorio = obligatorio;
		this.ordenAprobacion = ordenAprobacion;
		this.factor = factor;
		this.requisitoXUsuarioTiposForRequisitoAlternativoId = requisitoXUsuarioTiposForRequisitoAlternativoId;
		this.requisitoXUsuarioTiposForRequisitoXUsuarioTipoId = requisitoXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	public AplicacionXUsuarioTipo getAplicacionXUsuarioTipo() {
		return this.aplicacionXUsuarioTipo;
	}

	public void setAplicacionXUsuarioTipo(
			AplicacionXUsuarioTipo aplicacionXUsuarioTipo) {
		this.aplicacionXUsuarioTipo = aplicacionXUsuarioTipo;
	}

	public Integer getParametro() {
		return this.parametro;
	}

	public void setParametro(Integer parametro) {
		this.parametro = parametro;
	}

	public Boolean getObligatorio() {
		return this.obligatorio;
	}

	public void setObligatorio(Boolean obligatorio) {
		this.obligatorio = obligatorio;
	}

	public Boolean getOrdenAprobacion() {
		return this.ordenAprobacion;
	}

	public void setOrdenAprobacion(Boolean ordenAprobacion) {
		this.ordenAprobacion = ordenAprobacion;
	}

	public BigDecimal getFactor() {
		return this.factor;
	}

	public void setFactor(BigDecimal factor) {
		this.factor = factor;
	}

	public List getRequisitoXUsuarioTiposForRequisitoAlternativoId() {
		return this.requisitoXUsuarioTiposForRequisitoAlternativoId;
	}

	public void setRequisitoXUsuarioTiposForRequisitoAlternativoId(
			List requisitoXUsuarioTiposForRequisitoAlternativoId) {
		this.requisitoXUsuarioTiposForRequisitoAlternativoId = requisitoXUsuarioTiposForRequisitoAlternativoId;
	}

	public List getRequisitoXUsuarioTiposForRequisitoXUsuarioTipoId() {
		return this.requisitoXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

	public void setRequisitoXUsuarioTiposForRequisitoXUsuarioTipoId(
			List requisitoXUsuarioTiposForRequisitoXUsuarioTipoId) {
		this.requisitoXUsuarioTiposForRequisitoXUsuarioTipoId = requisitoXUsuarioTiposForRequisitoXUsuarioTipoId;
	}

}
