package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * Requisito generated by hbm2java
 */
public class Requisito implements java.io.Serializable {

	private Integer id;
	private Escala escala;
	private String nombre;
	private String pregunta;
	private Integer valorMinimo;
	private Integer valorMaximo;
	private List<RequisitoXAplicacionXUsuarioTipo> requisitoXAplicacionXUsuarioTipos = new ArrayList<RequisitoXAplicacionXUsuarioTipo>(0);
	private List<UsuarioXRequisito> usuarioXRequisitos = new ArrayList<UsuarioXRequisito>(0);

	public Requisito() {
	}

	public Requisito(Integer id) {
		this.id = id;
	}

	public Requisito(Integer id, Escala escala, String nombre, String pregunta,
			Integer valorMinimo, Integer valorMaximo,
			List<RequisitoXAplicacionXUsuarioTipo> requisitoXAplicacionXUsuarioTipos, List<UsuarioXRequisito> usuarioXRequisitos) {
		this.id = id;
		this.escala = escala;
		this.nombre = nombre;
		this.pregunta = pregunta;
		this.valorMinimo = valorMinimo;
		this.valorMaximo = valorMaximo;
		this.requisitoXAplicacionXUsuarioTipos = requisitoXAplicacionXUsuarioTipos;
		this.usuarioXRequisitos = usuarioXRequisitos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Escala getEscala() {
		return this.escala;
	}

	public void setEscala(Escala escala) {
		this.escala = escala;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getPregunta() {
		return this.pregunta;
	}

	public void setPregunta(String pregunta) {
		this.pregunta = pregunta;
	}

	public Integer getValorMinimo() {
		return this.valorMinimo;
	}

	public void setValorMinimo(Integer valorMinimo) {
		this.valorMinimo = valorMinimo;
	}

	public Integer getValorMaximo() {
		return this.valorMaximo;
	}

	public void setValorMaximo(Integer valorMaximo) {
		this.valorMaximo = valorMaximo;
	}

	public List<RequisitoXAplicacionXUsuarioTipo> getRequisitoXAplicacionXUsuarioTipos() {
		return this.requisitoXAplicacionXUsuarioTipos;
	}

	public void setRequisitoXAplicacionXUsuarioTipos(
			List<RequisitoXAplicacionXUsuarioTipo> requisitoXAplicacionXUsuarioTipos) {
		this.requisitoXAplicacionXUsuarioTipos = requisitoXAplicacionXUsuarioTipos;
	}

	public List<UsuarioXRequisito> getUsuarioXRequisitos() {
		return this.usuarioXRequisitos;
	}

	public void setUsuarioXRequisitos(List<UsuarioXRequisito> usuarioXRequisitos) {
		this.usuarioXRequisitos = usuarioXRequisitos;
	}

}
