package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * Sesion generated by hbm2java
 */
public class Sesion implements java.io.Serializable {

	private String sessionId;
	private Usuario usuario;
	private Integer sessionTime;
	private String sessionValue;

	public Sesion() {
	}

	public Sesion(String sessionId) {
		this.sessionId = sessionId;
	}

	public Sesion(String sessionId, Usuario usuario, Integer sessionTime,
			String sessionValue) {
		this.sessionId = sessionId;
		this.usuario = usuario;
		this.sessionTime = sessionTime;
		this.sessionValue = sessionValue;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Integer getSessionTime() {
		return this.sessionTime;
	}

	public void setSessionTime(Integer sessionTime) {
		this.sessionTime = sessionTime;
	}

	public String getSessionValue() {
		return this.sessionValue;
	}

	public void setSessionValue(String sessionValue) {
		this.sessionValue = sessionValue;
	}

}
