package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * SuplenteXCo generated by hbm2java
 */
public class SuplenteXCo implements java.io.Serializable {

	private int id;
	private UsuarioSeleccion usuarioSeleccion;
	private UsuarioEstado usuarioEstado;
	private AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo;
	private Usuario usuario;
	private Co co;
	private boolean asistencia;
	private boolean reemplazando;
	private Integer evaluacion;
	private String comentario;

	public SuplenteXCo() {
	}

	public SuplenteXCo(int id, boolean asistencia, boolean reemplazando) {
		this.id = id;
		this.asistencia = asistencia;
		this.reemplazando = reemplazando;
	}

	public SuplenteXCo(int id, UsuarioSeleccion usuarioSeleccion,
			UsuarioEstado usuarioEstado,
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo,
			Usuario usuario, Co co, boolean asistencia, boolean reemplazando,
			Integer evaluacion, String comentario) {
		this.id = id;
		this.usuarioSeleccion = usuarioSeleccion;
		this.usuarioEstado = usuarioEstado;
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
		this.usuario = usuario;
		this.co = co;
		this.asistencia = asistencia;
		this.reemplazando = reemplazando;
		this.evaluacion = evaluacion;
		this.comentario = comentario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public UsuarioSeleccion getUsuarioSeleccion() {
		return this.usuarioSeleccion;
	}

	public void setUsuarioSeleccion(UsuarioSeleccion usuarioSeleccion) {
		this.usuarioSeleccion = usuarioSeleccion;
	}

	public UsuarioEstado getUsuarioEstado() {
		return this.usuarioEstado;
	}

	public void setUsuarioEstado(UsuarioEstado usuarioEstado) {
		this.usuarioEstado = usuarioEstado;
	}

	public AplicacionXNivelXActividadTipo getAplicacionXNivelXActividadTipo() {
		return this.aplicacionXNivelXActividadTipo;
	}

	public void setAplicacionXNivelXActividadTipo(
			AplicacionXNivelXActividadTipo aplicacionXNivelXActividadTipo) {
		this.aplicacionXNivelXActividadTipo = aplicacionXNivelXActividadTipo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public boolean isAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(boolean asistencia) {
		this.asistencia = asistencia;
	}

	public boolean isReemplazando() {
		return this.reemplazando;
	}

	public void setReemplazando(boolean reemplazando) {
		this.reemplazando = reemplazando;
	}

	public Integer getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(Integer evaluacion) {
		this.evaluacion = evaluacion;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
