package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * TestPreguntaAlternativa generated by hbm2java
 */
public class TestPreguntaAlternativa implements java.io.Serializable {

	private int id;
	private TestPregunta testPregunta;
	private Character NAlternativa;
	private String nombre;

	public TestPreguntaAlternativa() {
	}

	public TestPreguntaAlternativa(int id) {
		this.id = id;
	}

	public TestPreguntaAlternativa(int id, TestPregunta testPregunta,
			Character NAlternativa, String nombre) {
		this.id = id;
		this.testPregunta = testPregunta;
		this.NAlternativa = NAlternativa;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public TestPregunta getTestPregunta() {
		return this.testPregunta;
	}

	public void setTestPregunta(TestPregunta testPregunta) {
		this.testPregunta = testPregunta;
	}

	public Character getNAlternativa() {
		return this.NAlternativa;
	}

	public void setNAlternativa(Character NAlternativa) {
		this.NAlternativa = NAlternativa;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
