package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TestCompetencia generated by hbm2java
 */
public class TestCompetencia implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Integer peso;
	private Integer criterioCritico;
	private Integer criterioBien;
	private List<TestPregunta> testPreguntas = new ArrayList<TestPregunta>(0);

	public TestCompetencia() {
	}

	public TestCompetencia(Integer id) {
		this.id = id;
	}

	public TestCompetencia(Integer id, String nombre, Integer peso,
			Integer criterioCritico, Integer criterioBien, List<TestPregunta> testPreguntas) {
		this.id = id;
		this.nombre = nombre;
		this.peso = peso;
		this.criterioCritico = criterioCritico;
		this.criterioBien = criterioBien;
		this.testPreguntas = testPreguntas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPeso() {
		return this.peso;
	}

	public void setPeso(Integer peso) {
		this.peso = peso;
	}

	public Integer getCriterioCritico() {
		return this.criterioCritico;
	}

	public void setCriterioCritico(Integer criterioCritico) {
		this.criterioCritico = criterioCritico;
	}

	public Integer getCriterioBien() {
		return this.criterioBien;
	}

	public void setCriterioBien(Integer criterioBien) {
		this.criterioBien = criterioBien;
	}

	public List<TestPregunta> getTestPreguntas() {
		return this.testPreguntas;
	}

	public void setTestPreguntas(List<TestPregunta> testPreguntas) {
		this.testPreguntas = testPreguntas;
	}

}
