package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TestCompetencia generated by hbm2java
 */
public class TestCompetencia implements java.io.Serializable {

	private int id;
	private String nombre;
	private Integer peso;
	private Integer criterioCritico;
	private Integer criterioBien;
	private Set testPreguntas = new HashSet(0);

	public TestCompetencia() {
	}

	public TestCompetencia(int id) {
		this.id = id;
	}

	public TestCompetencia(int id, String nombre, Integer peso,
			Integer criterioCritico, Integer criterioBien, Set testPreguntas) {
		this.id = id;
		this.nombre = nombre;
		this.peso = peso;
		this.criterioCritico = criterioCritico;
		this.criterioBien = criterioBien;
		this.testPreguntas = testPreguntas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPeso() {
		return this.peso;
	}

	public void setPeso(Integer peso) {
		this.peso = peso;
	}

	public Integer getCriterioCritico() {
		return this.criterioCritico;
	}

	public void setCriterioCritico(Integer criterioCritico) {
		this.criterioCritico = criterioCritico;
	}

	public Integer getCriterioBien() {
		return this.criterioBien;
	}

	public void setCriterioBien(Integer criterioBien) {
		this.criterioBien = criterioBien;
	}

	public Set getTestPreguntas() {
		return this.testPreguntas;
	}

	public void setTestPreguntas(Set testPreguntas) {
		this.testPreguntas = testPreguntas;
	}

}
