package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TestPregunta generated by hbm2java
 */
public class TestPregunta implements java.io.Serializable {

	private int id;
	private Test test;
	private TestCompetencia testCompetencia;
	private Integer NPregunta;
	private String nombre;
	private Character alternativaCorrecta;
	private Boolean sentido;
	private String imagen;
	private Set testPreguntaOpcions = new HashSet(0);
	private Set testPreguntaAlternativas = new HashSet(0);
	private Set usuarioXTestRespuestas = new HashSet(0);

	public TestPregunta() {
	}

	public TestPregunta(int id) {
		this.id = id;
	}

	public TestPregunta(int id, Test test, TestCompetencia testCompetencia,
			Integer NPregunta, String nombre, Character alternativaCorrecta,
			Boolean sentido, String imagen, Set testPreguntaOpcions,
			Set testPreguntaAlternativas, Set usuarioXTestRespuestas) {
		this.id = id;
		this.test = test;
		this.testCompetencia = testCompetencia;
		this.NPregunta = NPregunta;
		this.nombre = nombre;
		this.alternativaCorrecta = alternativaCorrecta;
		this.sentido = sentido;
		this.imagen = imagen;
		this.testPreguntaOpcions = testPreguntaOpcions;
		this.testPreguntaAlternativas = testPreguntaAlternativas;
		this.usuarioXTestRespuestas = usuarioXTestRespuestas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public TestCompetencia getTestCompetencia() {
		return this.testCompetencia;
	}

	public void setTestCompetencia(TestCompetencia testCompetencia) {
		this.testCompetencia = testCompetencia;
	}

	public Integer getNPregunta() {
		return this.NPregunta;
	}

	public void setNPregunta(Integer NPregunta) {
		this.NPregunta = NPregunta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Character getAlternativaCorrecta() {
		return this.alternativaCorrecta;
	}

	public void setAlternativaCorrecta(Character alternativaCorrecta) {
		this.alternativaCorrecta = alternativaCorrecta;
	}

	public Boolean getSentido() {
		return this.sentido;
	}

	public void setSentido(Boolean sentido) {
		this.sentido = sentido;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Set getTestPreguntaOpcions() {
		return this.testPreguntaOpcions;
	}

	public void setTestPreguntaOpcions(Set testPreguntaOpcions) {
		this.testPreguntaOpcions = testPreguntaOpcions;
	}

	public Set getTestPreguntaAlternativas() {
		return this.testPreguntaAlternativas;
	}

	public void setTestPreguntaAlternativas(Set testPreguntaAlternativas) {
		this.testPreguntaAlternativas = testPreguntaAlternativas;
	}

	public Set getUsuarioXTestRespuestas() {
		return this.usuarioXTestRespuestas;
	}

	public void setUsuarioXTestRespuestas(Set usuarioXTestRespuestas) {
		this.usuarioXTestRespuestas = usuarioXTestRespuestas;
	}

}
