package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TransporteTipo generated by hbm2java
 */
public class TransporteTipo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set trasladoModos = new HashSet(0);
	private Set transportes = new HashSet(0);

	public TransporteTipo() {
	}

	public TransporteTipo(int id) {
		this.id = id;
	}

	public TransporteTipo(int id, String nombre, Set trasladoModos,
			Set transportes) {
		this.id = id;
		this.nombre = nombre;
		this.trasladoModos = trasladoModos;
		this.transportes = transportes;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getTrasladoModos() {
		return this.trasladoModos;
	}

	public void setTrasladoModos(Set trasladoModos) {
		this.trasladoModos = trasladoModos;
	}

	public Set getTransportes() {
		return this.transportes;
	}

	public void setTransportes(Set transportes) {
		this.transportes = transportes;
	}

}
