package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TransporteTipo generated by hbm2java
 */
public class TransporteTipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos = new ArrayList<TrasladoModoXTransporteTipo>(0);
	private List<Transporte> transportes = new ArrayList<Transporte>(0);

	public TransporteTipo() {
	}

	public TransporteTipo(Integer id) {
		this.id = id;
	}

	public TransporteTipo(Integer id, String nombre,
			List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos, List<Transporte> transportes) {
		this.id = id;
		this.nombre = nombre;
		this.trasladoModoXTransporteTipos = trasladoModoXTransporteTipos;
		this.transportes = transportes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<TrasladoModoXTransporteTipo> getTrasladoModoXTransporteTipos() {
		return this.trasladoModoXTransporteTipos;
	}

	public void setTrasladoModoXTransporteTipos(List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos) {
		this.trasladoModoXTransporteTipos = trasladoModoXTransporteTipos;
	}

	public List<Transporte> getTransportes() {
		return this.transportes;
	}

	public void setTransportes(List<Transporte> transportes) {
		this.transportes = transportes;
	}

}
