package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Transporte generated by hbm2java
 */
public class Transporte implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private TransporteTipo transporteTipo;
	private Comuna comuna;
	private String patente;
	private Integer ano;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private String choferNombre;
	private Integer choferCelular;
	private Set transporteXActividads = new HashSet(0);
	private Set transporteXAplicacionXNivels = new HashSet(0);

	public Transporte() {
	}

	public Transporte(int id) {
		this.id = id;
	}

	public Transporte(int id, Usuario usuario, TransporteTipo transporteTipo,
			Comuna comuna, String patente, Integer ano, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			String choferNombre, Integer choferCelular,
			Set transporteXActividads, Set transporteXAplicacionXNivels) {
		this.id = id;
		this.usuario = usuario;
		this.transporteTipo = transporteTipo;
		this.comuna = comuna;
		this.patente = patente;
		this.ano = ano;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.choferNombre = choferNombre;
		this.choferCelular = choferCelular;
		this.transporteXActividads = transporteXActividads;
		this.transporteXAplicacionXNivels = transporteXAplicacionXNivels;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public TransporteTipo getTransporteTipo() {
		return this.transporteTipo;
	}

	public void setTransporteTipo(TransporteTipo transporteTipo) {
		this.transporteTipo = transporteTipo;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	public Integer getAno() {
		return this.ano;
	}

	public void setAno(Integer ano) {
		this.ano = ano;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public String getChoferNombre() {
		return this.choferNombre;
	}

	public void setChoferNombre(String choferNombre) {
		this.choferNombre = choferNombre;
	}

	public Integer getChoferCelular() {
		return this.choferCelular;
	}

	public void setChoferCelular(Integer choferCelular) {
		this.choferCelular = choferCelular;
	}

	public Set getTransporteXActividads() {
		return this.transporteXActividads;
	}

	public void setTransporteXActividads(Set transporteXActividads) {
		this.transporteXActividads = transporteXActividads;
	}

	public Set getTransporteXAplicacionXNivels() {
		return this.transporteXAplicacionXNivels;
	}

	public void setTransporteXAplicacionXNivels(Set transporteXAplicacionXNivels) {
		this.transporteXAplicacionXNivels = transporteXAplicacionXNivels;
	}

}
