package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TransporteTipo generated by hbm2java
 */
public class TransporteTipo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<TrasladoModo> trasladoModos = new ArrayList<TrasladoModo>(0);
	private List<Transporte> transportes = new ArrayList<Transporte>(0);

	public TransporteTipo() {
	}

	public TransporteTipo(Integer id) {
		this.id = id;
	}

	public TransporteTipo(Integer id, String nombre, List<TrasladoModo> trasladoModos,
			List<Transporte> transportes) {
		this.id = id;
		this.nombre = nombre;
		this.trasladoModos = trasladoModos;
		this.transportes = transportes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<TrasladoModo> getTrasladoModos() {
		return this.trasladoModos;
	}

	public void setTrasladoModos(List<TrasladoModo> trasladoModos) {
		this.trasladoModos = trasladoModos;
	}

	public List<Transporte> getTransportes() {
		return this.transportes;
	}

	public void setTransportes(List<Transporte> transportes) {
		this.transportes = transportes;
	}

}
