package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TrasladoModo generated by hbm2java
 */
public class TrasladoModo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String icono;
	private List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos = new ArrayList<TrasladoModoXTransporteTipo>(0);
	private List<Ruta> rutas = new ArrayList<Ruta>(0);

	public TrasladoModo() {
	}

	public TrasladoModo(Integer id) {
		this.id = id;
	}

	public TrasladoModo(Integer id, String nombre, String icono,
			List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos, List<Ruta> rutas) {
		this.id = id;
		this.nombre = nombre;
		this.icono = icono;
		this.trasladoModoXTransporteTipos = trasladoModoXTransporteTipos;
		this.rutas = rutas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	public List<TrasladoModoXTransporteTipo> getTrasladoModoXTransporteTipos() {
		return this.trasladoModoXTransporteTipos;
	}

	public void setTrasladoModoXTransporteTipos(List<TrasladoModoXTransporteTipo> trasladoModoXTransporteTipos) {
		this.trasladoModoXTransporteTipos = trasladoModoXTransporteTipos;
	}

	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

}
