package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * TrasladoModo generated by hbm2java
 */
public class TrasladoModo implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<TransporteTipo> transporteTipos = new ArrayList<TransporteTipo>(0);
	private List<Ruta> rutas = new ArrayList<Ruta>(0);

	public TrasladoModo() {
	}

	public TrasladoModo(Integer id) {
		this.id = id;
	}

	public TrasladoModo(Integer id, String nombre, List<TransporteTipo> transporteTipos, List<Ruta> rutas) {
		this.id = id;
		this.nombre = nombre;
		this.transporteTipos = transporteTipos;
		this.rutas = rutas;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<TransporteTipo> getTransporteTipos() {
		return this.transporteTipos;
	}

	public void setTransporteTipos(List<TransporteTipo> transporteTipos) {
		this.transporteTipos = transporteTipos;
	}

	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

}
