package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TrasladoModo generated by hbm2java
 */
public class TrasladoModo implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set transporteTipos = new HashSet(0);
	private Set rutas = new HashSet(0);

	public TrasladoModo() {
	}

	public TrasladoModo(int id) {
		this.id = id;
	}

	public TrasladoModo(int id, String nombre, Set transporteTipos, Set rutas) {
		this.id = id;
		this.nombre = nombre;
		this.transporteTipos = transporteTipos;
		this.rutas = rutas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getTransporteTipos() {
		return this.transporteTipos;
	}

	public void setTransporteTipos(Set transporteTipos) {
		this.transporteTipos = transporteTipos;
	}

	public Set getRutas() {
		return this.rutas;
	}

	public void setRutas(Set rutas) {
		this.rutas = rutas;
	}

}
