package com.dreamer8.yosimce.server.hibernate.pojo;

import com.dreamer8.yosimce.shared.dto.EvaluacionUsuarioDTO;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXActividad generated by hbm2java
 */
public class UsuarioXActividad implements java.io.Serializable {

	private Integer id;
	private UsuarioSeleccion usuarioSeleccion;
	private Actividad actividad;
	private UsuarioEstado usuarioEstado;
	private Usuario usuario;
	private Boolean asistencia;
	private Integer notaPresentacionPersonal;
	private Integer notaPuntualidad;
	private Integer notaLlenadoFormularios;
	private Integer notaDespempeno;
	private String comentario;

	public UsuarioXActividad() {
	}

	public UsuarioXActividad(Integer id, Boolean asistencia) {
		this.id = id;
		this.asistencia = asistencia;
	}

	public UsuarioXActividad(Integer id, UsuarioSeleccion usuarioSeleccion,
			Actividad actividad, UsuarioEstado usuarioEstado, Usuario usuario,
			Boolean asistencia, Integer notaPresentacionPersonal,
			Integer notaPuntualidad, Integer notaLlenadoFormularios,
			Integer notaDespempeno, String comentario) {
		this.id = id;
		this.usuarioSeleccion = usuarioSeleccion;
		this.actividad = actividad;
		this.usuarioEstado = usuarioEstado;
		this.usuario = usuario;
		this.asistencia = asistencia;
		this.notaPresentacionPersonal = notaPresentacionPersonal;
		this.notaPuntualidad = notaPuntualidad;
		this.notaLlenadoFormularios = notaLlenadoFormularios;
		this.notaDespempeno = notaDespempeno;
		this.comentario = comentario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuarioSeleccion getUsuarioSeleccion() {
		return this.usuarioSeleccion;
	}

	public void setUsuarioSeleccion(UsuarioSeleccion usuarioSeleccion) {
		this.usuarioSeleccion = usuarioSeleccion;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public UsuarioEstado getUsuarioEstado() {
		return this.usuarioEstado;
	}

	public void setUsuarioEstado(UsuarioEstado usuarioEstado) {
		this.usuarioEstado = usuarioEstado;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Boolean isAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Boolean asistencia) {
		this.asistencia = asistencia;
	}

	public Integer getNotaPresentacionPersonal() {
		return this.notaPresentacionPersonal;
	}

	public void setNotaPresentacionPersonal(Integer notaPresentacionPersonal) {
		this.notaPresentacionPersonal = notaPresentacionPersonal;
	}

	public Integer getNotaPuntualidad() {
		return this.notaPuntualidad;
	}

	public void setNotaPuntualidad(Integer notaPuntualidad) {
		this.notaPuntualidad = notaPuntualidad;
	}

	public Integer getNotaLlenadoFormularios() {
		return this.notaLlenadoFormularios;
	}

	public void setNotaLlenadoFormularios(Integer notaLlenadoFormularios) {
		this.notaLlenadoFormularios = notaLlenadoFormularios;
	}

	public Integer getNotaDespempeno() {
		return this.notaDespempeno;
	}

	public void setNotaDespempeno(Integer notaDespempeno) {
		this.notaDespempeno = notaDespempeno;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	public EvaluacionUsuarioDTO getEvaluacionUsuarioDTO() {
		EvaluacionUsuarioDTO eudto = new EvaluacionUsuarioDTO();
		eudto.setFormulario(notaLlenadoFormularios);
		eudto.setGeneral(notaDespempeno);
		eudto.setPresentacionPersonal(notaPresentacionPersonal);
		eudto.setPuntualidad(notaPuntualidad);
		eudto.setUsuario(usuarioSeleccion.getUsuarioXAplicacionXNivel()
				.getUsuario().getUserDTO());
		return eudto;
	}

}
