package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXComuna generated by hbm2java
 */
public class UsuarioXComuna implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Comuna comuna;
	private Integer prioridad;

	public UsuarioXComuna() {
	}

	public UsuarioXComuna(int id) {
		this.id = id;
	}

	public UsuarioXComuna(int id, Usuario usuario, Comuna comuna,
			Integer prioridad) {
		this.id = id;
		this.usuario = usuario;
		this.comuna = comuna;
		this.prioridad = prioridad;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
