package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsuarioDisponibilidad generated by hbm2java
 */
public class UsuarioDisponibilidad implements java.io.Serializable {

	private Integer id;
	private UsuarioXAplicacionXNivel usuarioXAplicacionXNivel;
	private Date fecha;
	private boolean disponible;

	public UsuarioDisponibilidad() {
	}

	public UsuarioDisponibilidad(Integer id,
			UsuarioXAplicacionXNivel usuarioXAplicacionXNivel, Date fecha,
			boolean disponible) {
		this.id = id;
		this.usuarioXAplicacionXNivel = usuarioXAplicacionXNivel;
		this.fecha = fecha;
		this.disponible = disponible;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuarioXAplicacionXNivel getUsuarioXAplicacionXNivel() {
		return this.usuarioXAplicacionXNivel;
	}

	public void setUsuarioXAplicacionXNivel(
			UsuarioXAplicacionXNivel usuarioXAplicacionXNivel) {
		this.usuarioXAplicacionXNivel = usuarioXAplicacionXNivel;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean isDisponible() {
		return this.disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

}
