package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXCoId generated by hbm2java
 */
public class UsuarioXCoId implements java.io.Serializable {

	private Integer usuarioId;
	private Integer coId;

	public UsuarioXCoId() {
	}

	public UsuarioXCoId(Integer usuarioId, Integer coId) {
		this.usuarioId = usuarioId;
		this.coId = coId;
	}

	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Integer getCoId() {
		return this.coId;
	}

	public void setCoId(Integer coId) {
		this.coId = coId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioXCoId))
			return false;
		UsuarioXCoId castOther = (UsuarioXCoId) other;

		return (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getCoId() == castOther.getCoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getUsuarioId();
		result = 37 * result + this.getCoId();
		return result;
	}

}
