package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXRequisito generated by hbm2java
 */
public class UsuarioXRequisito implements java.io.Serializable {

	private UsuarioXRequisitoId id;
	private Usuario usuario;
	private Requisito requisito;
	private Integer valor;

	public UsuarioXRequisito() {
	}

	public UsuarioXRequisito(UsuarioXRequisitoId id, Usuario usuario,
			Requisito requisito) {
		this.id = id;
		this.usuario = usuario;
		this.requisito = requisito;
	}

	public UsuarioXRequisito(UsuarioXRequisitoId id, Usuario usuario,
			Requisito requisito, Integer valor) {
		this.id = id;
		this.usuario = usuario;
		this.requisito = requisito;
		this.valor = valor;
	}

	public UsuarioXRequisitoId getId() {
		return this.id;
	}

	public void setId(UsuarioXRequisitoId id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Requisito getRequisito() {
		return this.requisito;
	}

	public void setRequisito(Requisito requisito) {
		this.requisito = requisito;
	}

	public Integer getValor() {
		return this.valor;
	}

	public void setValor(Integer valor) {
		this.valor = valor;
	}

}
