package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-07-2013 11:03:56 PM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXActividad generated by hbm2java
 */
public class UsuarioXActividad implements java.io.Serializable {

	private Integer id;
	private UsuarioSeleccion usuarioSeleccion;
	private Actividad actividad;
	private UsuarioEstado usuarioEstado;
	private Usuario usuario;
	private Boolean asistencia;
	private Integer evaluacion;
	private String comentario;

	public UsuarioXActividad() {
	}

	public UsuarioXActividad(Integer id) {
		this.id = id;
	}

	public UsuarioXActividad(Integer id, UsuarioSeleccion usuarioSeleccion,
			Actividad actividad, UsuarioEstado usuarioEstado, Usuario usuario,
			Boolean asistencia, Integer evaluacion, String comentario) {
		this.id = id;
		this.usuarioSeleccion = usuarioSeleccion;
		this.actividad = actividad;
		this.usuarioEstado = usuarioEstado;
		this.usuario = usuario;
		this.asistencia = asistencia;
		this.evaluacion = evaluacion;
		this.comentario = comentario;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuarioSeleccion getUsuarioSeleccion() {
		return this.usuarioSeleccion;
	}

	public void setUsuarioSeleccion(UsuarioSeleccion usuarioSeleccion) {
		this.usuarioSeleccion = usuarioSeleccion;
	}

	public Actividad getActividad() {
		return this.actividad;
	}

	public void setActividad(Actividad actividad) {
		this.actividad = actividad;
	}

	public UsuarioEstado getUsuarioEstado() {
		return this.usuarioEstado;
	}

	public void setUsuarioEstado(UsuarioEstado usuarioEstado) {
		this.usuarioEstado = usuarioEstado;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Boolean getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Boolean asistencia) {
		this.asistencia = asistencia;
	}

	public Integer getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(Integer evaluacion) {
		this.evaluacion = evaluacion;
	}

	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

}
