package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioEstado generated by hbm2java
 */
public class UsuarioEstado implements java.io.Serializable {

	private int id;
	private String nombre;
	private Set usuarioXActividads = new HashSet(0);
	private Set suplenteXCos = new HashSet(0);

	public UsuarioEstado() {
	}

	public UsuarioEstado(int id) {
		this.id = id;
	}

	public UsuarioEstado(int id, String nombre, Set usuarioXActividads,
			Set suplenteXCos) {
		this.id = id;
		this.nombre = nombre;
		this.usuarioXActividads = usuarioXActividads;
		this.suplenteXCos = suplenteXCos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(Set usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public Set getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(Set suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

}
