package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXCcCapacitacionId generated by hbm2java
 */
public class UsuarioXCcCapacitacionId implements java.io.Serializable {

	private Integer usuarioId;
	private Integer ccCapacitacionId;

	public UsuarioXCcCapacitacionId() {
	}

	public UsuarioXCcCapacitacionId(Integer usuarioId, Integer ccCapacitacionId) {
		this.usuarioId = usuarioId;
		this.ccCapacitacionId = ccCapacitacionId;
	}

	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Integer getCcCapacitacionId() {
		return this.ccCapacitacionId;
	}

	public void setCcCapacitacionId(Integer ccCapacitacionId) {
		this.ccCapacitacionId = ccCapacitacionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioXCcCapacitacionId))
			return false;
		UsuarioXCcCapacitacionId castOther = (UsuarioXCcCapacitacionId) other;

		return (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getCcCapacitacionId() == castOther
						.getCcCapacitacionId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getUsuarioId();
		result = 37 * result + this.getCcCapacitacionId();
		return result;
	}

}
