package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

/**
 * UsuarioEstado generated by hbm2java
 */
public class UsuarioEstado implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private List<UsuarioXActividad> usuarioXActividads = new ArrayList<UsuarioXActividad>(0);
	private List<SuplenteXCo> suplenteXCos = new ArrayList<SuplenteXCo>(0);

	public UsuarioEstado() {
	}

	public UsuarioEstado(Integer id) {
		this.id = id;
	}

	public UsuarioEstado(Integer id, String nombre, List<UsuarioXActividad> usuarioXActividads,
			List<SuplenteXCo> suplenteXCos) {
		this.id = id;
		this.nombre = nombre;
		this.usuarioXActividads = usuarioXActividads;
		this.suplenteXCos = suplenteXCos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public List<UsuarioXActividad> getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(List<UsuarioXActividad> usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public List<SuplenteXCo> getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(List<SuplenteXCo> suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

}
