package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXFaseXAplicacionId generated by hbm2java
 */
public class UsuarioXFaseXAplicacionId implements java.io.Serializable {

	private Integer usuarioId;
	private Integer faseXAplicacionId;

	public UsuarioXFaseXAplicacionId() {
	}

	public UsuarioXFaseXAplicacionId(Integer usuarioId, Integer faseXAplicacionId) {
		this.usuarioId = usuarioId;
		this.faseXAplicacionId = faseXAplicacionId;
	}

	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Integer getFaseXAplicacionId() {
		return this.faseXAplicacionId;
	}

	public void setFaseXAplicacionId(Integer faseXAplicacionId) {
		this.faseXAplicacionId = faseXAplicacionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioXFaseXAplicacionId))
			return false;
		UsuarioXFaseXAplicacionId castOther = (UsuarioXFaseXAplicacionId) other;

		return (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getFaseXAplicacionId() == castOther
						.getFaseXAplicacionId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getUsuarioId();
		result = 37 * result + this.getFaseXAplicacionId();
		return result;
	}

}
