package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.dreamer8.yosimce.shared.dto.SupervisorDTO;
import com.dreamer8.yosimce.shared.dto.UserDTO;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int id;
	private CompaniaTelefono companiaTelefono;
	private CarreraEstado carreraEstado;
	private Carrera carrera;
	private Sexo sexo;
	private Comuna comuna;
	private String username;
	private String salt;
	private String password;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String email;
	private String celular;
	private boolean smartphone;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private Integer carreraAnoIngreso;
	private Date fechaNacimiento;
	private boolean aceptaConfidencialidad;
	private Date fechaAceptacion;
	private String usernameCanonical;
	private String emailCanonical;
	private boolean enabled;
	private Date lastLogin;
	private boolean locked;
	private boolean expired;
	private Date expiresAt;
	private String confirmationToken;
	private Date passwordRequestedAt;
	private String roles;
	private boolean credentialsExpired;
	private Date credentialsExpireAt;
	private Set usuarioXTests = new HashSet(0);
	private Set usuarioXFaseXAplicacions = new HashSet(0);
	private Set usuarioXAplicacionXNivels = new HashSet(0);
	private Set nivels = new HashSet(0);
	private Set usuarioXCos = new HashSet(0);
	private Set historialCambioses = new HashSet(0);
	private Set avisos = new HashSet(0);
	private Set usuarioXRequisitos = new HashSet(0);
	private Set transportes = new HashSet(0);
	private Set actividads = new HashSet(0);
	private Set materialHistorials = new HashSet(0);
	private Set rutaXEstablecimientos = new HashSet(0);
	private Set suplenteXCos = new HashSet(0);
	private Set jrXCentroRegionals = new HashSet(0);
	private Set mensajes = new HashSet(0);
	private Set sesions = new HashSet(0);
	private Set usuarioXComunas = new HashSet(0);
	private Set usuarioXCcCapacitacions = new HashSet(0);
	private Set usuarioXActividads = new HashSet(0);
	private Set jzXZonas = new HashSet(0);
	private Set rutas = new HashSet(0);
	private Set joXCos = new HashSet(0);
	private Set usuarioXEstablecimientos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int id, String username, String salt, String password,
			String email, String celular, boolean smartphone,
			boolean aceptaConfidencialidad, String usernameCanonical,
			String emailCanonical, boolean enabled, boolean locked,
			boolean expired, String roles, boolean credentialsExpired) {
		this.id = id;
		this.username = username;
		this.salt = salt;
		this.password = password;
		this.email = email;
		this.celular = celular;
		this.smartphone = smartphone;
		this.aceptaConfidencialidad = aceptaConfidencialidad;
		this.usernameCanonical = usernameCanonical;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.locked = locked;
		this.expired = expired;
		this.roles = roles;
		this.credentialsExpired = credentialsExpired;
	}

	public Usuario(int id, CompaniaTelefono companiaTelefono,
			CarreraEstado carreraEstado, Carrera carrera, Sexo sexo,
			Comuna comuna, String username, String salt, String password,
			String nombres, String apellidoPaterno, String apellidoMaterno,
			String email, String celular, boolean smartphone, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			Integer carreraAnoIngreso, Date fechaNacimiento,
			boolean aceptaConfidencialidad, Date fechaAceptacion,
			String usernameCanonical, String emailCanonical, boolean enabled,
			Date lastLogin, boolean locked, boolean expired, Date expiresAt,
			String confirmationToken, Date passwordRequestedAt, String roles,
			boolean credentialsExpired, Date credentialsExpireAt,
			Set usuarioXTests, Set usuarioXFaseXAplicacions,
			Set usuarioXAplicacionXNivels, Set nivels, Set usuarioXCos,
			Set historialCambioses, Set avisos, Set usuarioXRequisitos,
			Set transportes, Set actividads, Set materialHistorials,
			Set rutaXEstablecimientos, Set suplenteXCos,
			Set jrXCentroRegionals, Set mensajes, Set sesions,
			Set usuarioXComunas, Set usuarioXCcCapacitacions,
			Set usuarioXActividads, Set jzXZonas, Set rutas, Set joXCos,
			Set usuarioXEstablecimientos) {
		this.id = id;
		this.companiaTelefono = companiaTelefono;
		this.carreraEstado = carreraEstado;
		this.carrera = carrera;
		this.sexo = sexo;
		this.comuna = comuna;
		this.username = username;
		this.salt = salt;
		this.password = password;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.email = email;
		this.celular = celular;
		this.smartphone = smartphone;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.carreraAnoIngreso = carreraAnoIngreso;
		this.fechaNacimiento = fechaNacimiento;
		this.aceptaConfidencialidad = aceptaConfidencialidad;
		this.fechaAceptacion = fechaAceptacion;
		this.usernameCanonical = usernameCanonical;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.lastLogin = lastLogin;
		this.locked = locked;
		this.expired = expired;
		this.expiresAt = expiresAt;
		this.confirmationToken = confirmationToken;
		this.passwordRequestedAt = passwordRequestedAt;
		this.roles = roles;
		this.credentialsExpired = credentialsExpired;
		this.credentialsExpireAt = credentialsExpireAt;
		this.usuarioXTests = usuarioXTests;
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
		this.usuarioXAplicacionXNivels = usuarioXAplicacionXNivels;
		this.nivels = nivels;
		this.usuarioXCos = usuarioXCos;
		this.historialCambioses = historialCambioses;
		this.avisos = avisos;
		this.usuarioXRequisitos = usuarioXRequisitos;
		this.transportes = transportes;
		this.actividads = actividads;
		this.materialHistorials = materialHistorials;
		this.rutaXEstablecimientos = rutaXEstablecimientos;
		this.suplenteXCos = suplenteXCos;
		this.jrXCentroRegionals = jrXCentroRegionals;
		this.mensajes = mensajes;
		this.sesions = sesions;
		this.usuarioXComunas = usuarioXComunas;
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
		this.usuarioXActividads = usuarioXActividads;
		this.jzXZonas = jzXZonas;
		this.rutas = rutas;
		this.joXCos = joXCos;
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CompaniaTelefono getCompaniaTelefono() {
		return this.companiaTelefono;
	}

	public void setCompaniaTelefono(CompaniaTelefono companiaTelefono) {
		this.companiaTelefono = companiaTelefono;
	}

	public CarreraEstado getCarreraEstado() {
		return this.carreraEstado;
	}

	public void setCarreraEstado(CarreraEstado carreraEstado) {
		this.carreraEstado = carreraEstado;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public boolean isSmartphone() {
		return this.smartphone;
	}

	public void setSmartphone(boolean smartphone) {
		this.smartphone = smartphone;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public Integer getCarreraAnoIngreso() {
		return this.carreraAnoIngreso;
	}

	public void setCarreraAnoIngreso(Integer carreraAnoIngreso) {
		this.carreraAnoIngreso = carreraAnoIngreso;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public boolean isAceptaConfidencialidad() {
		return this.aceptaConfidencialidad;
	}

	public void setAceptaConfidencialidad(boolean aceptaConfidencialidad) {
		this.aceptaConfidencialidad = aceptaConfidencialidad;
	}

	public Date getFechaAceptacion() {
		return this.fechaAceptacion;
	}

	public void setFechaAceptacion(Date fechaAceptacion) {
		this.fechaAceptacion = fechaAceptacion;
	}

	public String getUsernameCanonical() {
		return this.usernameCanonical;
	}

	public void setUsernameCanonical(String usernameCanonical) {
		this.usernameCanonical = usernameCanonical;
	}

	public String getEmailCanonical() {
		return this.emailCanonical;
	}

	public void setEmailCanonical(String emailCanonical) {
		this.emailCanonical = emailCanonical;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public boolean isExpired() {
		return this.expired;
	}

	public void setExpired(boolean expired) {
		this.expired = expired;
	}

	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public String getConfirmationToken() {
		return this.confirmationToken;
	}

	public void setConfirmationToken(String confirmationToken) {
		this.confirmationToken = confirmationToken;
	}

	public Date getPasswordRequestedAt() {
		return this.passwordRequestedAt;
	}

	public void setPasswordRequestedAt(Date passwordRequestedAt) {
		this.passwordRequestedAt = passwordRequestedAt;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public boolean isCredentialsExpired() {
		return this.credentialsExpired;
	}

	public void setCredentialsExpired(boolean credentialsExpired) {
		this.credentialsExpired = credentialsExpired;
	}

	public Date getCredentialsExpireAt() {
		return this.credentialsExpireAt;
	}

	public void setCredentialsExpireAt(Date credentialsExpireAt) {
		this.credentialsExpireAt = credentialsExpireAt;
	}

	public Set getUsuarioXTests() {
		return this.usuarioXTests;
	}

	public void setUsuarioXTests(Set usuarioXTests) {
		this.usuarioXTests = usuarioXTests;
	}

	public Set getUsuarioXFaseXAplicacions() {
		return this.usuarioXFaseXAplicacions;
	}

	public void setUsuarioXFaseXAplicacions(Set usuarioXFaseXAplicacions) {
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
	}

	public Set getUsuarioXAplicacionXNivels() {
		return this.usuarioXAplicacionXNivels;
	}

	public void setUsuarioXAplicacionXNivels(Set usuarioXAplicacionXNivels) {
		this.usuarioXAplicacionXNivels = usuarioXAplicacionXNivels;
	}

	public Set getNivels() {
		return this.nivels;
	}

	public void setNivels(Set nivels) {
		this.nivels = nivels;
	}

	public Set getUsuarioXCos() {
		return this.usuarioXCos;
	}

	public void setUsuarioXCos(Set usuarioXCos) {
		this.usuarioXCos = usuarioXCos;
	}

	public Set getHistorialCambioses() {
		return this.historialCambioses;
	}

	public void setHistorialCambioses(Set historialCambioses) {
		this.historialCambioses = historialCambioses;
	}

	public Set getAvisos() {
		return this.avisos;
	}

	public void setAvisos(Set avisos) {
		this.avisos = avisos;
	}

	public Set getUsuarioXRequisitos() {
		return this.usuarioXRequisitos;
	}

	public void setUsuarioXRequisitos(Set usuarioXRequisitos) {
		this.usuarioXRequisitos = usuarioXRequisitos;
	}

	public Set getTransportes() {
		return this.transportes;
	}

	public void setTransportes(Set transportes) {
		this.transportes = transportes;
	}

	public Set getActividads() {
		return this.actividads;
	}

	public void setActividads(Set actividads) {
		this.actividads = actividads;
	}

	public Set getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(Set materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public Set getRutaXEstablecimientos() {
		return this.rutaXEstablecimientos;
	}

	public void setRutaXEstablecimientos(Set rutaXEstablecimientos) {
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

	public Set getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(Set suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

	public Set getJrXCentroRegionals() {
		return this.jrXCentroRegionals;
	}

	public void setJrXCentroRegionals(Set jrXCentroRegionals) {
		this.jrXCentroRegionals = jrXCentroRegionals;
	}

	public Set getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set mensajes) {
		this.mensajes = mensajes;
	}

	public Set getSesions() {
		return this.sesions;
	}

	public void setSesions(Set sesions) {
		this.sesions = sesions;
	}

	public Set getUsuarioXComunas() {
		return this.usuarioXComunas;
	}

	public void setUsuarioXComunas(Set usuarioXComunas) {
		this.usuarioXComunas = usuarioXComunas;
	}

	public Set getUsuarioXCcCapacitacions() {
		return this.usuarioXCcCapacitacions;
	}

	public void setUsuarioXCcCapacitacions(Set usuarioXCcCapacitacions) {
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

	public Set getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(Set usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public Set getJzXZonas() {
		return this.jzXZonas;
	}

	public void setJzXZonas(Set jzXZonas) {
		this.jzXZonas = jzXZonas;
	}

	public Set getRutas() {
		return this.rutas;
	}

	public void setRutas(Set rutas) {
		this.rutas = rutas;
	}

	public Set getJoXCos() {
		return this.joXCos;
	}

	public void setJoXCos(Set joXCos) {
		this.joXCos = joXCos;
	}

	public Set getUsuarioXEstablecimientos() {
		return this.usuarioXEstablecimientos;
	}

	public void setUsuarioXEstablecimientos(Set usuarioXEstablecimientos) {
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public UserDTO getUserDTO() {
		UserDTO udto = new UserDTO();
		udto.setId(id);
		udto.setEmail(email);
		udto.setUsername(username);
		udto.setNombres(nombres);
		udto.setApellidoPaterno(apellidoPaterno);
		udto.setApellidoMaterno(apellidoMaterno);
		return udto;
	}

	/**
	 * @return
	 */
	public SupervisorDTO getSupervisorDTO() {
		SupervisorDTO sdto = new SupervisorDTO();
		sdto.setId(id);
		sdto.setEmail(email);
		sdto.setNombres(nombres);
		sdto.setApellidoPaterno(apellidoPaterno);
		sdto.setApellidoMaterno(apellidoMaterno);
		return sdto;
	}

}
