package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXCo generated by hbm2java
 */
public class UsuarioXCo implements java.io.Serializable {

	private Integer id;
	private Usuario usuario;
	private Co co;
	private Integer distancia;
	private Integer tiempo;
	private Integer prioridad;

	public UsuarioXCo() {
	}

	public UsuarioXCo(Integer id) {
		this.id = id;
	}

	public UsuarioXCo(Integer id, Usuario usuario, Co co, Integer distancia,
			Integer tiempo, Integer prioridad) {
		this.id = id;
		this.usuario = usuario;
		this.co = co;
		this.distancia = distancia;
		this.tiempo = tiempo;
		this.prioridad = prioridad;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Co getCo() {
		return this.co;
	}

	public void setCo(Co co) {
		this.co = co;
	}

	public Integer getDistancia() {
		return this.distancia;
	}

	public void setDistancia(Integer distancia) {
		this.distancia = distancia;
	}

	public Integer getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Integer tiempo) {
		this.tiempo = tiempo;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
