package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.EmplazamientoDTO;
import com.dreamer8.yosimce.shared.dto.TipoUsuarioDTO;

/**
 * UsuarioTipo generated by hbm2java
 */
public class UsuarioTipo implements java.io.Serializable {

	public static final String ADMINISTRADOR = "Administrador";
	public static final String MINISTERIO = "Ministerio";
	public static final String MINISTERIO_TIC = "Ministerio TIC";
	public static final String JEFE_PROYECTO = "Jefe de Proyecto";
	public static final String JEFE_REGIONAL = "Jefe Regional";
	public static final String JEFE_ZONAL = "Jefe Zonal";
	public static final String LOGISTICA_Y_SOPORTE = "Encargado de Logística y Soporte Técnico";
	public static final String JEFE_CENTRO_OPERACIONES = "Jefe de Centro de Operaciones";
	public static final String SUPERVISOR = "Supervisor";
	public static final String EXAMINADOR = "Examinador";
	public static final String EXAMINADOR_NEE = "Examinador NEE";
	public static final String EXAMINADOR_SUPLENTE = "Examinador Suplente";
	public static final String SUPERVISOR_LISTA_ESPERA = "Supervisor Lista de Espera";
	public static final String EXAMINADOR_LISTA_ESPERA = "Examinador Lista de Espera";
	public static final String OPERADOR_CENTRO_LLAMADOS = "Operador Centro de Llamados";
	public static final String CAPACITADOR = "Capacitador";
	public static final String EDITOR = "Editor";
	public static final String COORDINADOR_COMPUTACION = "Coordinador Empresa Computación";

	private Integer id;
	private UsuarioTipo usuarioTipo;
	private String nombre;
	private boolean firmaContrato;
	private Integer ccCapacidad;
	private String rol;
	private List<CcCapacitacion> ccCapacitacions = new ArrayList<CcCapacitacion>(
			0);
	private List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos = new ArrayList<FaseXAplicacionXTestXNivelXUsuarioTipo>(
			0);
	private List<AplicacionXNivelXUsuarioTipo> aplicacionXNivelXUsuarioTipos = new ArrayList<AplicacionXNivelXUsuarioTipo>(
			0);
	private List<UsuarioPreseleccion> usuarioPreseleccions = new ArrayList<UsuarioPreseleccion>(
			0);
	private List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos = new ArrayList<AplicacionXUsuarioTipo>(
			0);
	private List<UsuarioTipo> usuarioTipos = new ArrayList<UsuarioTipo>(0);
	private List<UsuarioSeleccion> usuarioSeleccions = new ArrayList<UsuarioSeleccion>(
			0);

	public UsuarioTipo() {
	}

	public UsuarioTipo(Integer id, boolean firmaContrato) {
		this.id = id;
		this.firmaContrato = firmaContrato;
	}

	public UsuarioTipo(
			Integer id,
			UsuarioTipo usuarioTipo,
			String nombre,
			boolean firmaContrato,
			Integer ccCapacidad,
			String rol,
			List<CcCapacitacion> ccCapacitacions,
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos,
			List<AplicacionXNivelXUsuarioTipo> aplicacionXNivelXUsuarioTipos,
			List<UsuarioPreseleccion> usuarioPreseleccions,
			List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos,
			List<UsuarioTipo> usuarioTipos,
			List<UsuarioSeleccion> usuarioSeleccions) {
		this.id = id;
		this.usuarioTipo = usuarioTipo;
		this.nombre = nombre;
		this.firmaContrato = firmaContrato;
		this.ccCapacidad = ccCapacidad;
		this.rol = rol;
		this.ccCapacitacions = ccCapacitacions;
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
		this.aplicacionXNivelXUsuarioTipos = aplicacionXNivelXUsuarioTipos;
		this.usuarioPreseleccions = usuarioPreseleccions;
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
		this.usuarioTipos = usuarioTipos;
		this.usuarioSeleccions = usuarioSeleccions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isFirmaContrato() {
		return this.firmaContrato;
	}

	public void setFirmaContrato(boolean firmaContrato) {
		this.firmaContrato = firmaContrato;
	}

	public Integer getCcCapacidad() {
		return this.ccCapacidad;
	}

	public void setCcCapacidad(Integer ccCapacidad) {
		this.ccCapacidad = ccCapacidad;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public List<CcCapacitacion> getCcCapacitacions() {
		return this.ccCapacitacions;
	}

	public void setCcCapacitacions(List<CcCapacitacion> ccCapacitacions) {
		this.ccCapacitacions = ccCapacitacions;
	}

	public List<FaseXAplicacionXTestXNivelXUsuarioTipo> getFaseXAplicacionXTestXNivelXUsuarioTipos() {
		return this.faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public void setFaseXAplicacionXTestXNivelXUsuarioTipos(
			List<FaseXAplicacionXTestXNivelXUsuarioTipo> faseXAplicacionXTestXNivelXUsuarioTipos) {
		this.faseXAplicacionXTestXNivelXUsuarioTipos = faseXAplicacionXTestXNivelXUsuarioTipos;
	}

	public List<AplicacionXNivelXUsuarioTipo> getAplicacionXNivelXUsuarioTipos() {
		return this.aplicacionXNivelXUsuarioTipos;
	}

	public void setAplicacionXNivelXUsuarioTipos(
			List<AplicacionXNivelXUsuarioTipo> aplicacionXNivelXUsuarioTipos) {
		this.aplicacionXNivelXUsuarioTipos = aplicacionXNivelXUsuarioTipos;
	}

	public List<UsuarioPreseleccion> getUsuarioPreseleccions() {
		return this.usuarioPreseleccions;
	}

	public void setUsuarioPreseleccions(
			List<UsuarioPreseleccion> usuarioPreseleccions) {
		this.usuarioPreseleccions = usuarioPreseleccions;
	}

	public List<AplicacionXUsuarioTipo> getAplicacionXUsuarioTipos() {
		return this.aplicacionXUsuarioTipos;
	}

	public void setAplicacionXUsuarioTipos(
			List<AplicacionXUsuarioTipo> aplicacionXUsuarioTipos) {
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

	public List<UsuarioTipo> getUsuarioTipos() {
		return this.usuarioTipos;
	}

	public void setUsuarioTipos(List<UsuarioTipo> usuarioTipos) {
		this.usuarioTipos = usuarioTipos;
	}

	public List<UsuarioSeleccion> getUsuarioSeleccions() {
		return this.usuarioSeleccions;
	}

	public void setUsuarioSeleccions(List<UsuarioSeleccion> usuarioSeleccions) {
		this.usuarioSeleccions = usuarioSeleccions;
	}

	public TipoUsuarioDTO getTipoUsuarioDTO() {
		TipoUsuarioDTO tudto = new TipoUsuarioDTO();
		tudto.setId(id);
		tudto.setTipoUsuario(nombre);
		if (nombre.equals(JEFE_CENTRO_OPERACIONES)) {
			tudto.setTipoEmplazamientoAsociado(EmplazamientoDTO.CENTRO_OPERACIONAL);
		} else if (nombre.equals(JEFE_ZONAL)) {
			tudto.setTipoEmplazamientoAsociado(EmplazamientoDTO.ZONA);
		} else if (nombre.equals(JEFE_REGIONAL)) {
			tudto.setTipoEmplazamientoAsociado(EmplazamientoDTO.CENTRO_REGIONAL);
		}
		return tudto;
	}

}
