package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioCapacitacion generated by hbm2java
 */
public class UsuarioCapacitacion implements java.io.Serializable {

	private UsuarioCapacitacionId id;

	public UsuarioCapacitacion() {
	}

	public UsuarioCapacitacion(UsuarioCapacitacionId id) {
		this.id = id;
	}

	public UsuarioCapacitacionId getId() {
		return this.id;
	}

	public void setId(UsuarioCapacitacionId id) {
		this.id = id;
	}

}
