package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXRequisitoId generated by hbm2java
 */
public class UsuarioXRequisitoId implements java.io.Serializable {

	private Integer usuarioId;
	private Integer requisitoId;

	public UsuarioXRequisitoId() {
	}

	public UsuarioXRequisitoId(Integer usuarioId, Integer requisitoId) {
		this.usuarioId = usuarioId;
		this.requisitoId = requisitoId;
	}

	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	public Integer getRequisitoId() {
		return this.requisitoId;
	}

	public void setRequisitoId(Integer requisitoId) {
		this.requisitoId = requisitoId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioXRequisitoId))
			return false;
		UsuarioXRequisitoId castOther = (UsuarioXRequisitoId) other;

		return (this.getUsuarioId() == castOther.getUsuarioId())
				&& (this.getRequisitoId() == castOther.getRequisitoId());
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + this.getUsuarioId();
		result = 37 * result + this.getRequisitoId();
		return result;
	}

}
