package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioXAplicacionXNivel generated by hbm2java
 */
public class UsuarioXAplicacionXNivel implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private AplicacionXNivel aplicacionXNivel;
	private Set usuarioSeleccions = new HashSet(0);
	private Set usuarioPreseleccions = new HashSet(0);

	public UsuarioXAplicacionXNivel() {
	}

	public UsuarioXAplicacionXNivel(int id) {
		this.id = id;
	}

	public UsuarioXAplicacionXNivel(int id, Usuario usuario,
			AplicacionXNivel aplicacionXNivel, Set usuarioSeleccions,
			Set usuarioPreseleccions) {
		this.id = id;
		this.usuario = usuario;
		this.aplicacionXNivel = aplicacionXNivel;
		this.usuarioSeleccions = usuarioSeleccions;
		this.usuarioPreseleccions = usuarioPreseleccions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public AplicacionXNivel getAplicacionXNivel() {
		return this.aplicacionXNivel;
	}

	public void setAplicacionXNivel(AplicacionXNivel aplicacionXNivel) {
		this.aplicacionXNivel = aplicacionXNivel;
	}

	public Set getUsuarioSeleccions() {
		return this.usuarioSeleccions;
	}

	public void setUsuarioSeleccions(Set usuarioSeleccions) {
		this.usuarioSeleccions = usuarioSeleccions;
	}

	public Set getUsuarioPreseleccions() {
		return this.usuarioPreseleccions;
	}

	public void setUsuarioPreseleccions(Set usuarioPreseleccions) {
		this.usuarioPreseleccions = usuarioPreseleccions;
	}

}
