package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioXTest generated by hbm2java
 */
public class UsuarioXTest implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Test test;
	private Integer intento;
	private Date fechaInicio;
	private Date fechaTermino;
	private Integer buenas;
	private Integer omitidas;
	private Integer malas;
	private BigDecimal evaluacion;
	private Set usuarioXTestRespuestas = new HashSet(0);

	public UsuarioXTest() {
	}

	public UsuarioXTest(int id) {
		this.id = id;
	}

	public UsuarioXTest(int id, Usuario usuario, Test test, Integer intento,
			Date fechaInicio, Date fechaTermino, Integer buenas,
			Integer omitidas, Integer malas, BigDecimal evaluacion,
			Set usuarioXTestRespuestas) {
		this.id = id;
		this.usuario = usuario;
		this.test = test;
		this.intento = intento;
		this.fechaInicio = fechaInicio;
		this.fechaTermino = fechaTermino;
		this.buenas = buenas;
		this.omitidas = omitidas;
		this.malas = malas;
		this.evaluacion = evaluacion;
		this.usuarioXTestRespuestas = usuarioXTestRespuestas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Test getTest() {
		return this.test;
	}

	public void setTest(Test test) {
		this.test = test;
	}

	public Integer getIntento() {
		return this.intento;
	}

	public void setIntento(Integer intento) {
		this.intento = intento;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaTermino() {
		return this.fechaTermino;
	}

	public void setFechaTermino(Date fechaTermino) {
		this.fechaTermino = fechaTermino;
	}

	public Integer getBuenas() {
		return this.buenas;
	}

	public void setBuenas(Integer buenas) {
		this.buenas = buenas;
	}

	public Integer getOmitidas() {
		return this.omitidas;
	}

	public void setOmitidas(Integer omitidas) {
		this.omitidas = omitidas;
	}

	public Integer getMalas() {
		return this.malas;
	}

	public void setMalas(Integer malas) {
		this.malas = malas;
	}

	public BigDecimal getEvaluacion() {
		return this.evaluacion;
	}

	public void setEvaluacion(BigDecimal evaluacion) {
		this.evaluacion = evaluacion;
	}

	public Set getUsuarioXTestRespuestas() {
		return this.usuarioXTestRespuestas;
	}

	public void setUsuarioXTestRespuestas(Set usuarioXTestRespuestas) {
		this.usuarioXTestRespuestas = usuarioXTestRespuestas;
	}

}
