package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 05-08-2013 03:58:39 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * UsuarioSeleccion generated by hbm2java
 */
public class UsuarioSeleccion implements java.io.Serializable {

	private Integer id;
	private UsuarioTipo usuarioTipo;
	private UsuarioXAplicacionXNivel usuarioXAplicacionXNivel;
	private Integer montoPago;
	private boolean pagado;
	private boolean contratoFirmado;
	private Date fechaFirma;
	private boolean asistencia;
	private List<UsuarioXActividad> usuarioXActividads = new ArrayList<UsuarioXActividad>(0);
	private List<SuplenteXCo> suplenteXCos = new ArrayList<SuplenteXCo>(0);

	public UsuarioSeleccion() {
	}

	public UsuarioSeleccion(Integer id, boolean pagado, boolean contratoFirmado,
			boolean asistencia) {
		this.id = id;
		this.pagado = pagado;
		this.contratoFirmado = contratoFirmado;
		this.asistencia = asistencia;
	}

	public UsuarioSeleccion(Integer id, UsuarioTipo usuarioTipo,
			UsuarioXAplicacionXNivel usuarioXAplicacionXNivel,
			Integer montoPago, boolean pagado, boolean contratoFirmado,
			Date fechaFirma, boolean asistencia, List<UsuarioXActividad> usuarioXActividads,
			List<SuplenteXCo> suplenteXCos) {
		this.id = id;
		this.usuarioTipo = usuarioTipo;
		this.usuarioXAplicacionXNivel = usuarioXAplicacionXNivel;
		this.montoPago = montoPago;
		this.pagado = pagado;
		this.contratoFirmado = contratoFirmado;
		this.fechaFirma = fechaFirma;
		this.asistencia = asistencia;
		this.usuarioXActividads = usuarioXActividads;
		this.suplenteXCos = suplenteXCos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public UsuarioTipo getUsuarioTipo() {
		return this.usuarioTipo;
	}

	public void setUsuarioTipo(UsuarioTipo usuarioTipo) {
		this.usuarioTipo = usuarioTipo;
	}

	public UsuarioXAplicacionXNivel getUsuarioXAplicacionXNivel() {
		return this.usuarioXAplicacionXNivel;
	}

	public void setUsuarioXAplicacionXNivel(
			UsuarioXAplicacionXNivel usuarioXAplicacionXNivel) {
		this.usuarioXAplicacionXNivel = usuarioXAplicacionXNivel;
	}

	public Integer getMontoPago() {
		return this.montoPago;
	}

	public void setMontoPago(Integer montoPago) {
		this.montoPago = montoPago;
	}

	public boolean isPagado() {
		return this.pagado;
	}

	public void setPagado(boolean pagado) {
		this.pagado = pagado;
	}

	public boolean isContratoFirmado() {
		return this.contratoFirmado;
	}

	public void setContratoFirmado(boolean contratoFirmado) {
		this.contratoFirmado = contratoFirmado;
	}

	public Date getFechaFirma() {
		return this.fechaFirma;
	}

	public void setFechaFirma(Date fechaFirma) {
		this.fechaFirma = fechaFirma;
	}

	public boolean isAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(boolean asistencia) {
		this.asistencia = asistencia;
	}

	public List<UsuarioXActividad> getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(List<UsuarioXActividad> usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public List<SuplenteXCo> getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(List<SuplenteXCo> suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

}
