package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * UsuarioCapacitacionId generated by hbm2java
 */
public class UsuarioCapacitacionId implements java.io.Serializable {

	private Integer id;
	private Integer sexoId;
	private String username;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String email;
	private Integer usuarioTipoId;
	private String celular;
	private Integer companiaTelefonoId;
	private Boolean smartphone;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private Integer comunaId;
	private Date fechaNacimiento;
	private String usernameCanonical;
	private String emailCanonical;
	private Boolean enabled;
	private Date lastLogin;
	private Boolean locked;
	private Boolean expired;
	private Date expiresAt;
	private String roles;
	private Boolean credentialsExpired;
	private Date credentialsExpireAt;

	public UsuarioCapacitacionId() {
	}

	public UsuarioCapacitacionId(Integer id, Integer sexoId, String username,
			String nombres, String apellidoPaterno, String apellidoMaterno,
			String email, Integer usuarioTipoId, String celular,
			Integer companiaTelefonoId, Boolean smartphone, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			Integer comunaId, Date fechaNacimiento, String usernameCanonical,
			String emailCanonical, Boolean enabled, Date lastLogin,
			Boolean locked, Boolean expired, Date expiresAt, String roles,
			Boolean credentialsExpired, Date credentialsExpireAt) {
		this.id = id;
		this.sexoId = sexoId;
		this.username = username;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.email = email;
		this.usuarioTipoId = usuarioTipoId;
		this.celular = celular;
		this.companiaTelefonoId = companiaTelefonoId;
		this.smartphone = smartphone;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.comunaId = comunaId;
		this.fechaNacimiento = fechaNacimiento;
		this.usernameCanonical = usernameCanonical;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.lastLogin = lastLogin;
		this.locked = locked;
		this.expired = expired;
		this.expiresAt = expiresAt;
		this.roles = roles;
		this.credentialsExpired = credentialsExpired;
		this.credentialsExpireAt = credentialsExpireAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSexoId() {
		return this.sexoId;
	}

	public void setSexoId(Integer sexoId) {
		this.sexoId = sexoId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getUsuarioTipoId() {
		return this.usuarioTipoId;
	}

	public void setUsuarioTipoId(Integer usuarioTipoId) {
		this.usuarioTipoId = usuarioTipoId;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public Integer getCompaniaTelefonoId() {
		return this.companiaTelefonoId;
	}

	public void setCompaniaTelefonoId(Integer companiaTelefonoId) {
		this.companiaTelefonoId = companiaTelefonoId;
	}

	public Boolean getSmartphone() {
		return this.smartphone;
	}

	public void setSmartphone(Boolean smartphone) {
		this.smartphone = smartphone;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public Integer getComunaId() {
		return this.comunaId;
	}

	public void setComunaId(Integer comunaId) {
		this.comunaId = comunaId;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getUsernameCanonical() {
		return this.usernameCanonical;
	}

	public void setUsernameCanonical(String usernameCanonical) {
		this.usernameCanonical = usernameCanonical;
	}

	public String getEmailCanonical() {
		return this.emailCanonical;
	}

	public void setEmailCanonical(String emailCanonical) {
		this.emailCanonical = emailCanonical;
	}

	public Boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(Boolean locked) {
		this.locked = locked;
	}

	public Boolean getExpired() {
		return this.expired;
	}

	public void setExpired(Boolean expired) {
		this.expired = expired;
	}

	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public Boolean getCredentialsExpired() {
		return this.credentialsExpired;
	}

	public void setCredentialsExpired(Boolean credentialsExpired) {
		this.credentialsExpired = credentialsExpired;
	}

	public Date getCredentialsExpireAt() {
		return this.credentialsExpireAt;
	}

	public void setCredentialsExpireAt(Date credentialsExpireAt) {
		this.credentialsExpireAt = credentialsExpireAt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioCapacitacionId))
			return false;
		UsuarioCapacitacionId castOther = (UsuarioCapacitacionId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getSexoId() == castOther.getSexoId()) || (this
						.getSexoId() != null && castOther.getSexoId() != null && this
						.getSexoId().equals(castOther.getSexoId())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())))
				&& ((this.getNombres() == castOther.getNombres()) || (this
						.getNombres() != null && castOther.getNombres() != null && this
						.getNombres().equals(castOther.getNombres())))
				&& ((this.getApellidoPaterno() == castOther
						.getApellidoPaterno()) || (this.getApellidoPaterno() != null
						&& castOther.getApellidoPaterno() != null && this
						.getApellidoPaterno().equals(
								castOther.getApellidoPaterno())))
				&& ((this.getApellidoMaterno() == castOther
						.getApellidoMaterno()) || (this.getApellidoMaterno() != null
						&& castOther.getApellidoMaterno() != null && this
						.getApellidoMaterno().equals(
								castOther.getApellidoMaterno())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getUsuarioTipoId() == castOther.getUsuarioTipoId()) || (this
						.getUsuarioTipoId() != null
						&& castOther.getUsuarioTipoId() != null && this
						.getUsuarioTipoId()
						.equals(castOther.getUsuarioTipoId())))
				&& ((this.getCelular() == castOther.getCelular()) || (this
						.getCelular() != null && castOther.getCelular() != null && this
						.getCelular().equals(castOther.getCelular())))
				&& ((this.getCompaniaTelefonoId() == castOther
						.getCompaniaTelefonoId()) || (this
						.getCompaniaTelefonoId() != null
						&& castOther.getCompaniaTelefonoId() != null && this
						.getCompaniaTelefonoId().equals(
								castOther.getCompaniaTelefonoId())))
				&& ((this.getSmartphone() == castOther.getSmartphone()) || (this
						.getSmartphone() != null
						&& castOther.getSmartphone() != null && this
						.getSmartphone().equals(castOther.getSmartphone())))
				&& ((this.getDireccion() == castOther.getDireccion()) || (this
						.getDireccion() != null
						&& castOther.getDireccion() != null && this
						.getDireccion().equals(castOther.getDireccion())))
				&& ((this.getDireccionLatitud() == castOther
						.getDireccionLatitud()) || (this.getDireccionLatitud() != null
						&& castOther.getDireccionLatitud() != null && this
						.getDireccionLatitud().equals(
								castOther.getDireccionLatitud())))
				&& ((this.getDireccionLongitud() == castOther
						.getDireccionLongitud()) || (this
						.getDireccionLongitud() != null
						&& castOther.getDireccionLongitud() != null && this
						.getDireccionLongitud().equals(
								castOther.getDireccionLongitud())))
				&& ((this.getComunaId() == castOther.getComunaId()) || (this
						.getComunaId() != null
						&& castOther.getComunaId() != null && this
						.getComunaId().equals(castOther.getComunaId())))
				&& ((this.getFechaNacimiento() == castOther
						.getFechaNacimiento()) || (this.getFechaNacimiento() != null
						&& castOther.getFechaNacimiento() != null && this
						.getFechaNacimiento().equals(
								castOther.getFechaNacimiento())))
				&& ((this.getUsernameCanonical() == castOther
						.getUsernameCanonical()) || (this
						.getUsernameCanonical() != null
						&& castOther.getUsernameCanonical() != null && this
						.getUsernameCanonical().equals(
								castOther.getUsernameCanonical())))
				&& ((this.getEmailCanonical() == castOther.getEmailCanonical()) || (this
						.getEmailCanonical() != null
						&& castOther.getEmailCanonical() != null && this
						.getEmailCanonical().equals(
								castOther.getEmailCanonical())))
				&& ((this.getEnabled() == castOther.getEnabled()) || (this
						.getEnabled() != null && castOther.getEnabled() != null && this
						.getEnabled().equals(castOther.getEnabled())))
				&& ((this.getLastLogin() == castOther.getLastLogin()) || (this
						.getLastLogin() != null
						&& castOther.getLastLogin() != null && this
						.getLastLogin().equals(castOther.getLastLogin())))
				&& ((this.getLocked() == castOther.getLocked()) || (this
						.getLocked() != null && castOther.getLocked() != null && this
						.getLocked().equals(castOther.getLocked())))
				&& ((this.getExpired() == castOther.getExpired()) || (this
						.getExpired() != null && castOther.getExpired() != null && this
						.getExpired().equals(castOther.getExpired())))
				&& ((this.getExpiresAt() == castOther.getExpiresAt()) || (this
						.getExpiresAt() != null
						&& castOther.getExpiresAt() != null && this
						.getExpiresAt().equals(castOther.getExpiresAt())))
				&& ((this.getRoles() == castOther.getRoles()) || (this
						.getRoles() != null && castOther.getRoles() != null && this
						.getRoles().equals(castOther.getRoles())))
				&& ((this.getCredentialsExpired() == castOther
						.getCredentialsExpired()) || (this
						.getCredentialsExpired() != null
						&& castOther.getCredentialsExpired() != null && this
						.getCredentialsExpired().equals(
								castOther.getCredentialsExpired())))
				&& ((this.getCredentialsExpireAt() == castOther
						.getCredentialsExpireAt()) || (this
						.getCredentialsExpireAt() != null
						&& castOther.getCredentialsExpireAt() != null && this
						.getCredentialsExpireAt().equals(
								castOther.getCredentialsExpireAt())));
	}

	public int hashCode() {
		Integer result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getSexoId() == null ? 0 : this.getSexoId().hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getNombres() == null ? 0 : this.getNombres().hashCode());
		result = 37
				* result
				+ (getApellidoPaterno() == null ? 0 : this.getApellidoPaterno()
						.hashCode());
		result = 37
				* result
				+ (getApellidoMaterno() == null ? 0 : this.getApellidoMaterno()
						.hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37
				* result
				+ (getUsuarioTipoId() == null ? 0 : this.getUsuarioTipoId()
						.hashCode());
		result = 37 * result
				+ (getCelular() == null ? 0 : this.getCelular().hashCode());
		result = 37
				* result
				+ (getCompaniaTelefonoId() == null ? 0 : this
						.getCompaniaTelefonoId().hashCode());
		result = 37
				* result
				+ (getSmartphone() == null ? 0 : this.getSmartphone()
						.hashCode());
		result = 37 * result
				+ (getDireccion() == null ? 0 : this.getDireccion().hashCode());
		result = 37
				* result
				+ (getDireccionLatitud() == null ? 0 : this
						.getDireccionLatitud().hashCode());
		result = 37
				* result
				+ (getDireccionLongitud() == null ? 0 : this
						.getDireccionLongitud().hashCode());
		result = 37 * result
				+ (getComunaId() == null ? 0 : this.getComunaId().hashCode());
		result = 37
				* result
				+ (getFechaNacimiento() == null ? 0 : this.getFechaNacimiento()
						.hashCode());
		result = 37
				* result
				+ (getUsernameCanonical() == null ? 0 : this
						.getUsernameCanonical().hashCode());
		result = 37
				* result
				+ (getEmailCanonical() == null ? 0 : this.getEmailCanonical()
						.hashCode());
		result = 37 * result
				+ (getEnabled() == null ? 0 : this.getEnabled().hashCode());
		result = 37 * result
				+ (getLastLogin() == null ? 0 : this.getLastLogin().hashCode());
		result = 37 * result
				+ (getLocked() == null ? 0 : this.getLocked().hashCode());
		result = 37 * result
				+ (getExpired() == null ? 0 : this.getExpired().hashCode());
		result = 37 * result
				+ (getExpiresAt() == null ? 0 : this.getExpiresAt().hashCode());
		result = 37 * result
				+ (getRoles() == null ? 0 : this.getRoles().hashCode());
		result = 37
				* result
				+ (getCredentialsExpired() == null ? 0 : this
						.getCredentialsExpired().hashCode());
		result = 37
				* result
				+ (getCredentialsExpireAt() == null ? 0 : this
						.getCredentialsExpireAt().hashCode());
		return result;
	}

}
