package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 12-07-2013 05:32:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXTestRespuesta generated by hbm2java
 */
public class UsuarioXTestRespuesta implements java.io.Serializable {

	private Integer id;
	private TestPregunta testPregunta;
	private UsuarioXTest usuarioXTest;
	private Character respuesta;
	private Integer correccion;

	public UsuarioXTestRespuesta() {
	}

	public UsuarioXTestRespuesta(Integer id) {
		this.id = id;
	}

	public UsuarioXTestRespuesta(Integer id, TestPregunta testPregunta,
			UsuarioXTest usuarioXTest, Character respuesta, Integer correccion) {
		this.id = id;
		this.testPregunta = testPregunta;
		this.usuarioXTest = usuarioXTest;
		this.respuesta = respuesta;
		this.correccion = correccion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TestPregunta getTestPregunta() {
		return this.testPregunta;
	}

	public void setTestPregunta(TestPregunta testPregunta) {
		this.testPregunta = testPregunta;
	}

	public UsuarioXTest getUsuarioXTest() {
		return this.usuarioXTest;
	}

	public void setUsuarioXTest(UsuarioXTest usuarioXTest) {
		this.usuarioXTest = usuarioXTest;
	}

	public Character getRespuesta() {
		return this.respuesta;
	}

	public void setRespuesta(Character respuesta) {
		this.respuesta = respuesta;
	}

	public Integer getCorreccion() {
		return this.correccion;
	}

	public void setCorreccion(Integer correccion) {
		this.correccion = correccion;
	}

}
