package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 16-08-2013 05:13:17 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.dreamer8.yosimce.shared.dto.SupervisorDTO;
import com.dreamer8.yosimce.shared.dto.UserDTO;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer id;
	private CompaniaTelefono companiaTelefono;
	private CarreraEstado carreraEstado;
	private Carrera carrera;
	private Sexo sexo;
	private Comuna comuna;
	private String username;
	private String salt;
	private String password;
	private String nombres;
	private String apellidoPaterno;
	private String apellidoMaterno;
	private String email;
	private String celular;
	private boolean smartphone;
	private String direccion;
	private BigDecimal direccionLatitud;
	private BigDecimal direccionLongitud;
	private Integer carreraAnoIngreso;
	private Date fechaNacimiento;
	private boolean aceptaConfidencialidad;
	private Date fechaAceptacion;
	private String usernameCanonical;
	private String emailCanonical;
	private boolean enabled;
	private Date lastLogin;
	private boolean locked;
	private boolean expired;
	private Date expiresAt;
	private String confirmationToken;
	private Date passwordRequestedAt;
	private String roles;
	private boolean credentialsExpired;
	private Date credentialsExpireAt;
	private List<UsuarioXTest> usuarioXTests = new ArrayList<UsuarioXTest>(0);
	private List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions = new ArrayList<UsuarioXFaseXAplicacion>(0);
	private List<UsuarioXAplicacionXNivel> usuarioXAplicacionXNivels = new ArrayList<UsuarioXAplicacionXNivel>(0);
	private List<Nivel> nivels = new ArrayList<Nivel>(0);
	private List<UsuarioXCo> usuarioXCos = new ArrayList<UsuarioXCo>(0);
	private List<HistorialCambios> historialCambios = new ArrayList<HistorialCambios>(0);
	private List<Aviso> avisos = new ArrayList<Aviso>(0);
	private List<UsuarioXRequisito> usuarioXRequisitos = new ArrayList<UsuarioXRequisito>(0);
	private List<Transporte> transportes = new ArrayList<Transporte>(0);
	private List<Actividad> actividads = new ArrayList<Actividad>(0);
	private List<MaterialHistorial> materialHistorials = new ArrayList<MaterialHistorial>(0);
	private List<RutaXEstablecimiento> rutaXEstablecimientos = new ArrayList<RutaXEstablecimiento>(0);
	private List<SuplenteXCo> suplenteXCos = new ArrayList<SuplenteXCo>(0);
	private List<JrXCentroRegional> jrXCentroRegionals = new ArrayList<JrXCentroRegional>(0);
	private List<Mensaje> mensajes = new ArrayList<Mensaje>(0);
	private List<Sesion> sesions = new ArrayList<Sesion>(0);
	private List<UsuarioXComuna> usuarioXComunas = new ArrayList<UsuarioXComuna>(0);
	private List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions = new ArrayList<UsuarioXCcCapacitacion>(0);
	private List<UsuarioXActividad> usuarioXActividads = new ArrayList<UsuarioXActividad>(0);
	private List<JzXZona> jzXZonas = new ArrayList<JzXZona>(0);
	private List<Ruta> rutas = new ArrayList<Ruta>(0);
	private List<JoXCo> joXCos = new ArrayList<JoXCo>(0);
	private List<UsuarioXEstablecimiento> usuarioXEstablecimientos = new ArrayList<UsuarioXEstablecimiento>(0);

	public Usuario() {
	}

	public Usuario(Integer id, String username, String salt, String password,
			String email, String celular, boolean smartphone,
			boolean aceptaConfidencialidad, String usernameCanonical,
			String emailCanonical, boolean enabled, boolean locked,
			boolean expired, String roles, boolean credentialsExpired) {
		this.id = id;
		this.username = username;
		this.salt = salt;
		this.password = password;
		this.email = email;
		this.celular = celular;
		this.smartphone = smartphone;
		this.aceptaConfidencialidad = aceptaConfidencialidad;
		this.usernameCanonical = usernameCanonical;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.locked = locked;
		this.expired = expired;
		this.roles = roles;
		this.credentialsExpired = credentialsExpired;
	}

	public Usuario(Integer id, CompaniaTelefono companiaTelefono,
			CarreraEstado carreraEstado, Carrera carrera, Sexo sexo,
			Comuna comuna, String username, String salt, String password,
			String nombres, String apellidoPaterno, String apellidoMaterno,
			String email, String celular, boolean smartphone, String direccion,
			BigDecimal direccionLatitud, BigDecimal direccionLongitud,
			Integer carreraAnoIngreso, Date fechaNacimiento,
			boolean aceptaConfidencialidad, Date fechaAceptacion,
			String usernameCanonical, String emailCanonical, boolean enabled,
			Date lastLogin, boolean locked, boolean expired, Date expiresAt,
			String confirmationToken, Date passwordRequestedAt, String roles,
			boolean credentialsExpired, Date credentialsExpireAt,
			List<UsuarioXTest> usuarioXTests, List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions,
			List<UsuarioXAplicacionXNivel> usuarioXAplicacionXNivels, List<Nivel> nivels, List<UsuarioXCo> usuarioXCos,
			List<HistorialCambios> historialCambios, List<Aviso> avisos, List<UsuarioXRequisito> usuarioXRequisitos,
			List<Transporte> transportes, List<Actividad> actividads, List<MaterialHistorial> materialHistorials,
			List<RutaXEstablecimiento> rutaXEstablecimientos, List<SuplenteXCo> suplenteXCos,
			List<JrXCentroRegional> jrXCentroRegionals, List<Mensaje> mensajes, List<Sesion> sesions,
			List<UsuarioXComuna> usuarioXComunas, List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions,
			List<UsuarioXActividad> usuarioXActividads, List<JzXZona> jzXZonas, List<Ruta> rutas, List<JoXCo> joXCos,
			List<UsuarioXEstablecimiento> usuarioXEstablecimientos) {
		this.id = id;
		this.companiaTelefono = companiaTelefono;
		this.carreraEstado = carreraEstado;
		this.carrera = carrera;
		this.sexo = sexo;
		this.comuna = comuna;
		this.username = username;
		this.salt = salt;
		this.password = password;
		this.nombres = nombres;
		this.apellidoPaterno = apellidoPaterno;
		this.apellidoMaterno = apellidoMaterno;
		this.email = email;
		this.celular = celular;
		this.smartphone = smartphone;
		this.direccion = direccion;
		this.direccionLatitud = direccionLatitud;
		this.direccionLongitud = direccionLongitud;
		this.carreraAnoIngreso = carreraAnoIngreso;
		this.fechaNacimiento = fechaNacimiento;
		this.aceptaConfidencialidad = aceptaConfidencialidad;
		this.fechaAceptacion = fechaAceptacion;
		this.usernameCanonical = usernameCanonical;
		this.emailCanonical = emailCanonical;
		this.enabled = enabled;
		this.lastLogin = lastLogin;
		this.locked = locked;
		this.expired = expired;
		this.expiresAt = expiresAt;
		this.confirmationToken = confirmationToken;
		this.passwordRequestedAt = passwordRequestedAt;
		this.roles = roles;
		this.credentialsExpired = credentialsExpired;
		this.credentialsExpireAt = credentialsExpireAt;
		this.usuarioXTests = usuarioXTests;
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
		this.usuarioXAplicacionXNivels = usuarioXAplicacionXNivels;
		this.nivels = nivels;
		this.usuarioXCos = usuarioXCos;
		this.historialCambios = historialCambios;
		this.avisos = avisos;
		this.usuarioXRequisitos = usuarioXRequisitos;
		this.transportes = transportes;
		this.actividads = actividads;
		this.materialHistorials = materialHistorials;
		this.rutaXEstablecimientos = rutaXEstablecimientos;
		this.suplenteXCos = suplenteXCos;
		this.jrXCentroRegionals = jrXCentroRegionals;
		this.mensajes = mensajes;
		this.sesions = sesions;
		this.usuarioXComunas = usuarioXComunas;
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
		this.usuarioXActividads = usuarioXActividads;
		this.jzXZonas = jzXZonas;
		this.rutas = rutas;
		this.joXCos = joXCos;
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CompaniaTelefono getCompaniaTelefono() {
		return this.companiaTelefono;
	}

	public void setCompaniaTelefono(CompaniaTelefono companiaTelefono) {
		this.companiaTelefono = companiaTelefono;
	}

	public CarreraEstado getCarreraEstado() {
		return this.carreraEstado;
	}

	public void setCarreraEstado(CarreraEstado carreraEstado) {
		this.carreraEstado = carreraEstado;
	}

	public Carrera getCarrera() {
		return this.carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	public Comuna getComuna() {
		return this.comuna;
	}

	public void setComuna(Comuna comuna) {
		this.comuna = comuna;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidoPaterno() {
		return this.apellidoPaterno;
	}

	public void setApellidoPaterno(String apellidoPaterno) {
		this.apellidoPaterno = apellidoPaterno;
	}

	public String getApellidoMaterno() {
		return this.apellidoMaterno;
	}

	public void setApellidoMaterno(String apellidoMaterno) {
		this.apellidoMaterno = apellidoMaterno;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public boolean isSmartphone() {
		return this.smartphone;
	}

	public void setSmartphone(boolean smartphone) {
		this.smartphone = smartphone;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public BigDecimal getDireccionLatitud() {
		return this.direccionLatitud;
	}

	public void setDireccionLatitud(BigDecimal direccionLatitud) {
		this.direccionLatitud = direccionLatitud;
	}

	public BigDecimal getDireccionLongitud() {
		return this.direccionLongitud;
	}

	public void setDireccionLongitud(BigDecimal direccionLongitud) {
		this.direccionLongitud = direccionLongitud;
	}

	public Integer getCarreraAnoIngreso() {
		return this.carreraAnoIngreso;
	}

	public void setCarreraAnoIngreso(Integer carreraAnoIngreso) {
		this.carreraAnoIngreso = carreraAnoIngreso;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public boolean isAceptaConfidencialidad() {
		return this.aceptaConfidencialidad;
	}

	public void setAceptaConfidencialidad(boolean aceptaConfidencialidad) {
		this.aceptaConfidencialidad = aceptaConfidencialidad;
	}

	public Date getFechaAceptacion() {
		return this.fechaAceptacion;
	}

	public void setFechaAceptacion(Date fechaAceptacion) {
		this.fechaAceptacion = fechaAceptacion;
	}

	public String getUsernameCanonical() {
		return this.usernameCanonical;
	}

	public void setUsernameCanonical(String usernameCanonical) {
		this.usernameCanonical = usernameCanonical;
	}

	public String getEmailCanonical() {
		return this.emailCanonical;
	}

	public void setEmailCanonical(String emailCanonical) {
		this.emailCanonical = emailCanonical;
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	public boolean isLocked() {
		return this.locked;
	}

	public void setLocked(boolean locked) {
		this.locked = locked;
	}

	public boolean isExpired() {
		return this.expired;
	}

	public void setExpired(boolean expired) {
		this.expired = expired;
	}

	public Date getExpiresAt() {
		return this.expiresAt;
	}

	public void setExpiresAt(Date expiresAt) {
		this.expiresAt = expiresAt;
	}

	public String getConfirmationToken() {
		return this.confirmationToken;
	}

	public void setConfirmationToken(String confirmationToken) {
		this.confirmationToken = confirmationToken;
	}

	public Date getPasswordRequestedAt() {
		return this.passwordRequestedAt;
	}

	public void setPasswordRequestedAt(Date passwordRequestedAt) {
		this.passwordRequestedAt = passwordRequestedAt;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public boolean isCredentialsExpired() {
		return this.credentialsExpired;
	}

	public void setCredentialsExpired(boolean credentialsExpired) {
		this.credentialsExpired = credentialsExpired;
	}

	public Date getCredentialsExpireAt() {
		return this.credentialsExpireAt;
	}

	public void setCredentialsExpireAt(Date credentialsExpireAt) {
		this.credentialsExpireAt = credentialsExpireAt;
	}

	public List<UsuarioXTest> getUsuarioXTests() {
		return this.usuarioXTests;
	}

	public void setUsuarioXTests(List<UsuarioXTest> usuarioXTests) {
		this.usuarioXTests = usuarioXTests;
	}

	public List<UsuarioXFaseXAplicacion> getUsuarioXFaseXAplicacions() {
		return this.usuarioXFaseXAplicacions;
	}

	public void setUsuarioXFaseXAplicacions(List<UsuarioXFaseXAplicacion> usuarioXFaseXAplicacions) {
		this.usuarioXFaseXAplicacions = usuarioXFaseXAplicacions;
	}

	public List<UsuarioXAplicacionXNivel> getUsuarioXAplicacionXNivels() {
		return this.usuarioXAplicacionXNivels;
	}

	public void setUsuarioXAplicacionXNivels(List<UsuarioXAplicacionXNivel> usuarioXAplicacionXNivels) {
		this.usuarioXAplicacionXNivels = usuarioXAplicacionXNivels;
	}

	public List<Nivel> getNivels() {
		return this.nivels;
	}

	public void setNivels(List<Nivel> nivels) {
		this.nivels = nivels;
	}

	public List<UsuarioXCo> getUsuarioXCos() {
		return this.usuarioXCos;
	}

	public void setUsuarioXCos(List<UsuarioXCo> usuarioXCos) {
		this.usuarioXCos = usuarioXCos;
	}

	public List<HistorialCambios> getHistorialCambios() {
		return this.historialCambios;
	}

	public void setHistorialCambios(List<HistorialCambios> historialCambios) {
		this.historialCambios = historialCambios;
	}

	public List<Aviso> getAvisos() {
		return this.avisos;
	}

	public void setAvisos(List<Aviso> avisos) {
		this.avisos = avisos;
	}

	public List<UsuarioXRequisito> getUsuarioXRequisitos() {
		return this.usuarioXRequisitos;
	}

	public void setUsuarioXRequisitos(List<UsuarioXRequisito> usuarioXRequisitos) {
		this.usuarioXRequisitos = usuarioXRequisitos;
	}

	public List<Transporte> getTransportes() {
		return this.transportes;
	}

	public void setTransportes(List<Transporte> transportes) {
		this.transportes = transportes;
	}

	public List<Actividad> getActividads() {
		return this.actividads;
	}

	public void setActividads(List<Actividad> actividads) {
		this.actividads = actividads;
	}

	public List<MaterialHistorial> getMaterialHistorials() {
		return this.materialHistorials;
	}

	public void setMaterialHistorials(List<MaterialHistorial> materialHistorials) {
		this.materialHistorials = materialHistorials;
	}

	public List<RutaXEstablecimiento> getRutaXEstablecimientos() {
		return this.rutaXEstablecimientos;
	}

	public void setRutaXEstablecimientos(List<RutaXEstablecimiento> rutaXEstablecimientos) {
		this.rutaXEstablecimientos = rutaXEstablecimientos;
	}

	public List<SuplenteXCo> getSuplenteXCos() {
		return this.suplenteXCos;
	}

	public void setSuplenteXCos(List<SuplenteXCo> suplenteXCos) {
		this.suplenteXCos = suplenteXCos;
	}

	public List<JrXCentroRegional> getJrXCentroRegionals() {
		return this.jrXCentroRegionals;
	}

	public void setJrXCentroRegionals(List<JrXCentroRegional> jrXCentroRegionals) {
		this.jrXCentroRegionals = jrXCentroRegionals;
	}

	public List<Mensaje> getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(List<Mensaje> mensajes) {
		this.mensajes = mensajes;
	}

	public List<Sesion> getSesions() {
		return this.sesions;
	}

	public void setSesions(List<Sesion> sesions) {
		this.sesions = sesions;
	}

	public List<UsuarioXComuna> getUsuarioXComunas() {
		return this.usuarioXComunas;
	}

	public void setUsuarioXComunas(List<UsuarioXComuna> usuarioXComunas) {
		this.usuarioXComunas = usuarioXComunas;
	}

	public List<UsuarioXCcCapacitacion> getUsuarioXCcCapacitacions() {
		return this.usuarioXCcCapacitacions;
	}

	public void setUsuarioXCcCapacitacions(List<UsuarioXCcCapacitacion> usuarioXCcCapacitacions) {
		this.usuarioXCcCapacitacions = usuarioXCcCapacitacions;
	}

	public List<UsuarioXActividad> getUsuarioXActividads() {
		return this.usuarioXActividads;
	}

	public void setUsuarioXActividads(List<UsuarioXActividad> usuarioXActividads) {
		this.usuarioXActividads = usuarioXActividads;
	}

	public List<JzXZona> getJzXZonas() {
		return this.jzXZonas;
	}

	public void setJzXZonas(List<JzXZona> jzXZonas) {
		this.jzXZonas = jzXZonas;
	}

	public List<Ruta> getRutas() {
		return this.rutas;
	}

	public void setRutas(List<Ruta> rutas) {
		this.rutas = rutas;
	}

	public List<JoXCo> getJoXCos() {
		return this.joXCos;
	}

	public void setJoXCos(List<JoXCo> joXCos) {
		this.joXCos = joXCos;
	}

	public List<UsuarioXEstablecimiento> getUsuarioXEstablecimientos() {
		return this.usuarioXEstablecimientos;
	}

	public void setUsuarioXEstablecimientos(List<UsuarioXEstablecimiento> usuarioXEstablecimientos) {
		this.usuarioXEstablecimientos = usuarioXEstablecimientos;
	}

	public UserDTO getUserDTO() {
		UserDTO udto = new UserDTO();
		udto.setId(id);
		udto.setEmail(email);
		udto.setUsername(username);
		udto.setNombres(nombres);
		udto.setApellidoPaterno(apellidoPaterno);
		udto.setApellidoMaterno(apellidoMaterno);
		return udto;
	}

	public SupervisorDTO getSupervisorDTO() {
		SupervisorDTO sdto = new SupervisorDTO();
		sdto.setId(id);
		sdto.setEmail(email);
		sdto.setNombres(nombres);
		sdto.setApellidoPaterno(apellidoPaterno);
		sdto.setApellidoMaterno(apellidoMaterno);
		return sdto;
	}

}
