package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

/**
 * UsuarioXEstablecimiento generated by hbm2java
 */
public class UsuarioXEstablecimiento implements java.io.Serializable {

	private int id;
	private Usuario usuario;
	private Establecimiento establecimiento;
	private boolean inhabilitado;
	private Integer distancia;
	private Integer tiempo;
	private Integer prioridad;

	public UsuarioXEstablecimiento() {
	}

	public UsuarioXEstablecimiento(int id, boolean inhabilitado) {
		this.id = id;
		this.inhabilitado = inhabilitado;
	}

	public UsuarioXEstablecimiento(int id, Usuario usuario,
			Establecimiento establecimiento, boolean inhabilitado,
			Integer distancia, Integer tiempo, Integer prioridad) {
		this.id = id;
		this.usuario = usuario;
		this.establecimiento = establecimiento;
		this.inhabilitado = inhabilitado;
		this.distancia = distancia;
		this.tiempo = tiempo;
		this.prioridad = prioridad;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	public boolean isInhabilitado() {
		return this.inhabilitado;
	}

	public void setInhabilitado(boolean inhabilitado) {
		this.inhabilitado = inhabilitado;
	}

	public Integer getDistancia() {
		return this.distancia;
	}

	public void setDistancia(Integer distancia) {
		this.distancia = distancia;
	}

	public Integer getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(Integer tiempo) {
		this.tiempo = tiempo;
	}

	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

}
