package com.dreamer8.yosimce.server.hibernate.pojo;

// Generated 01-08-2013 04:51:27 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UsuarioTipo generated by hbm2java
 */
public class UsuarioTipo implements java.io.Serializable {

	public static final String ADMINISTRADOR = "Administrador";
	public static final String MINISTERIO = "Ministerio";
	public static final String MINISTERIO_TIC = "Ministerio TIC";
	public static final String JEFE_PROYECTO = "Jefe de Proyecto";
	public static final String JEFE_REGIONAL = "Jefe Regional";
	public static final String JEFE_ZONAL = "Jefe Zonal";
	public static final String LOGISTICA_Y_SOPORTE = "Encargado de Logística y Soporte Técnico";
	public static final String JEFE_CENTRO_OPERACIONES = "Jefe de Centro de Operaciones";
	public static final String SUPERVISOR = "Supervisor";
	public static final String EXAMINADOR = "Examinador";
	public static final String EXAMINADOR_NEE = "Examinador NEE";
	public static final String EXAMINADOR_SUPLENTE = "Examinador Suplente";
	public static final String SUPERVISOR_LISTA_ESPERA = "Supervisor Lista de Espera";
	public static final String EXAMINADOR_LISTA_ESPERA = "Examinador Lista de Espera";
	public static final String OPERADOR_CENTRO_LLAMADOS = "Operador Centro de Llamados";
	public static final String CAPACITADOR = "Capacitador";
	public static final String EDITOR = "Editor";
	public static final String COORDINADOR_COMPUTACION = "Coordinador Empresa Computación";

	private int id;
	private String nombre;
	private boolean firmaContrato;
	private Integer ccCapacidad;
	private String rol;
	private Set ccCapacitacions = new HashSet(0);
	private Set aplicacionXNivelXUsuarioTipos = new HashSet(0);
	private Set faseXAplicacionXTestXNivelXTipoUsuarios = new HashSet(0);
	private Set usuarioPreseleccions = new HashSet(0);
	private Set aplicacionXUsuarioTipos = new HashSet(0);
	private Set usuarioSeleccions = new HashSet(0);

	public UsuarioTipo() {
	}

	public UsuarioTipo(int id, boolean firmaContrato) {
		this.id = id;
		this.firmaContrato = firmaContrato;
	}

	public UsuarioTipo(int id, String nombre, boolean firmaContrato,
			Integer ccCapacidad, String rol, Set ccCapacitacions,
			Set aplicacionXNivelXUsuarioTipos,
			Set faseXAplicacionXTestXNivelXTipoUsuarios,
			Set usuarioPreseleccions, Set aplicacionXUsuarioTipos,
			Set usuarioSeleccions) {
		this.id = id;
		this.nombre = nombre;
		this.firmaContrato = firmaContrato;
		this.ccCapacidad = ccCapacidad;
		this.rol = rol;
		this.ccCapacitacions = ccCapacitacions;
		this.aplicacionXNivelXUsuarioTipos = aplicacionXNivelXUsuarioTipos;
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
		this.usuarioPreseleccions = usuarioPreseleccions;
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
		this.usuarioSeleccions = usuarioSeleccions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isFirmaContrato() {
		return this.firmaContrato;
	}

	public void setFirmaContrato(boolean firmaContrato) {
		this.firmaContrato = firmaContrato;
	}

	public Integer getCcCapacidad() {
		return this.ccCapacidad;
	}

	public void setCcCapacidad(Integer ccCapacidad) {
		this.ccCapacidad = ccCapacidad;
	}

	public String getRol() {
		return this.rol;
	}

	public void setRol(String rol) {
		this.rol = rol;
	}

	public Set getCcCapacitacions() {
		return this.ccCapacitacions;
	}

	public void setCcCapacitacions(Set ccCapacitacions) {
		this.ccCapacitacions = ccCapacitacions;
	}

	public Set getAplicacionXNivelXUsuarioTipos() {
		return this.aplicacionXNivelXUsuarioTipos;
	}

	public void setAplicacionXNivelXUsuarioTipos(
			Set aplicacionXNivelXUsuarioTipos) {
		this.aplicacionXNivelXUsuarioTipos = aplicacionXNivelXUsuarioTipos;
	}

	public Set getFaseXAplicacionXTestXNivelXTipoUsuarios() {
		return this.faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public void setFaseXAplicacionXTestXNivelXTipoUsuarios(
			Set faseXAplicacionXTestXNivelXTipoUsuarios) {
		this.faseXAplicacionXTestXNivelXTipoUsuarios = faseXAplicacionXTestXNivelXTipoUsuarios;
	}

	public Set getUsuarioPreseleccions() {
		return this.usuarioPreseleccions;
	}

	public void setUsuarioPreseleccions(Set usuarioPreseleccions) {
		this.usuarioPreseleccions = usuarioPreseleccions;
	}

	public Set getAplicacionXUsuarioTipos() {
		return this.aplicacionXUsuarioTipos;
	}

	public void setAplicacionXUsuarioTipos(Set aplicacionXUsuarioTipos) {
		this.aplicacionXUsuarioTipos = aplicacionXUsuarioTipos;
	}

	public Set getUsuarioSeleccions() {
		return this.usuarioSeleccions;
	}

	public void setUsuarioSeleccions(Set usuarioSeleccions) {
		this.usuarioSeleccions = usuarioSeleccions;
	}

}
